/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { SqliteTabularStorage } from "@workglow/sqlite/storage";
import { Sqlite } from "@workglow/sqlite/storage";
import { setLogger, uuid4 } from "@workglow/util";
import { describe, expect, it } from "vitest";
import { getTestingLogger } from "../../binding/TestingLogger";
import {
  AllTypesPrimaryKeyNames,
  AllTypesSchema,
  AutoIncrementPrimaryKeyNames,
  AutoIncrementSchema,
  CompoundPrimaryKeyNames,
  CompoundSchema,
  runAutoGeneratedKeyTests,
  runGenericTabularStorageTests,
  SearchPrimaryKeyNames,
  SearchSchema,
  UuidPrimaryKeyNames,
  UuidSchema,
} from "./genericTabularStorageTests";

describe("SqliteTabularStorage", async () => {
  await Sqlite.init();
  let logger = getTestingLogger();
  setLogger(logger);
  runGenericTabularStorageTests(
    async () =>
      new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        CompoundSchema,
        CompoundPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        SearchSchema,
        SearchPrimaryKeyNames,
        ["category", ["category", "subcategory"], ["subcategory", "category"], "value"]
      ),
    async () => {
      const repo = new SqliteTabularStorage<typeof AllTypesSchema, typeof AllTypesPrimaryKeyNames>(
        ":memory:",
        `all_types_test_${uuid4().replace(/-/g, "_")}`,
        AllTypesSchema,
        AllTypesPrimaryKeyNames
      );
      await repo.setupDatabase();
      return repo;
    }
  );

  runAutoGeneratedKeyTests(
    async () =>
      new SqliteTabularStorage<typeof AutoIncrementSchema, typeof AutoIncrementPrimaryKeyNames>(
        ":memory:",
        `autoinc_test_${uuid4().replace(/-/g, "_")}`,
        AutoIncrementSchema,
        AutoIncrementPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof UuidSchema, typeof UuidPrimaryKeyNames>(
        ":memory:",
        `uuid_test_${uuid4().replace(/-/g, "_")}`,
        UuidSchema,
        UuidPrimaryKeyNames
      )
  );
});

describe("SqliteTabularStorage.queryIndex", () => {
  it("returns projected rows containing only requested columns", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex",
      SearchSchema,
      SearchPrimaryKeyNames,
      [["category", "subcategory"]]
    );
    await storage.setupDatabase();
    await storage.put({
      id: "k1",
      category: "a",
      subcategory: "x",
      value: 1,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-01-01T00:00:00Z",
    });
    const rows = await storage.queryIndex(
      { category: "a" },
      { select: ["id", "category"], orderBy: [{ column: "subcategory", direction: "ASC" }] }
    );
    expect(rows).toHaveLength(1);
    expect(Object.keys(rows[0]).sort()).toEqual(["category", "id"]);
    expect((rows[0] as any).value).toBeUndefined();
  });

  it("throws CoveringIndexMissingError when no covering index exists", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex_noindex",
      SearchSchema,
      SearchPrimaryKeyNames,
      []
    );
    await storage.setupDatabase();
    await expect(storage.queryIndex({ category: "a" }, { select: ["id"] })).rejects.toThrow(
      /CoveringIndexMissingError|No covering index/
    );
  });

  it("returns empty array (not undefined) on no matches", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex_empty",
      SearchSchema,
      SearchPrimaryKeyNames,
      [["category"]]
    );
    await storage.setupDatabase();
    const rows = await storage.queryIndex({ category: "missing" }, { select: ["id"] });
    expect(rows).toEqual([]);
  });
});

describe("SqliteTabularStorage.withTransaction", () => {
  async function makeStorage() {
    const storage = new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
      ":memory:",
      `tx_test_${uuid4().replace(/-/g, "_")}`,
      CompoundSchema,
      CompoundPrimaryKeyNames
    );
    await storage.setupDatabase();
    return storage;
  }

  it("rolls back all writes when the callback throws", async () => {
    const storage = await makeStorage();

    await expect(
      storage.withTransaction(async (tx) => {
        await tx.put({ name: "a", type: "x", option: "v1", success: true });
        await tx.put({ name: "b", type: "x", option: "v2", success: true });
        throw new Error("boom");
      })
    ).rejects.toThrow("boom");

    expect(await storage.get({ name: "a", type: "x" })).toBeUndefined();
    expect(await storage.get({ name: "b", type: "x" })).toBeUndefined();
  });

  it("rejects nested withTransaction calls instead of corrupting the outer transaction", async () => {
    const storage = await makeStorage();

    await expect(
      storage.withTransaction(async (tx) => {
        await tx.put({ name: "outer", type: "x", option: "v", success: true });
        await tx.withTransaction(async () => {
          // unreachable
        });
      })
    ).rejects.toThrow(/does not support nesting/);

    // Outer transaction was rolled back as a result of the nested-call error.
    expect(await storage.get({ name: "outer", type: "x" })).toBeUndefined();
  });
});
