/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { Sqlite, SqliteTabularStorage } from "@workglow/sqlite/storage";
import { ConnectionReentryError, StorageValidationError } from "@workglow/storage";
import { setLogger, uuid4 } from "@workglow/util";
import type { DataPortSchemaObject } from "@workglow/util/schema";
import { getTestingLogger } from "@workglow/util/test";
import { describe, expect, it, vi } from "vitest";
import {
  runTabularStorageContract,
  VectorItemPrimaryKeyNames,
  VectorItemSchema,
} from "../../contract/tabular-storage/runTabularStorageContract";
import { runSqlBulkPutTests } from "./genericSqlBulkPutTests";
import {
  AllTypesPrimaryKeyNames,
  AllTypesSchema,
  AutoIncrementPrimaryKeyNames,
  AutoIncrementSchema,
  CompoundPrimaryKeyNames,
  CompoundSchema,
  PAYLOADS,
  runAutoGeneratedKeyTests,
  runGenericTabularStorageTests,
  SearchPrimaryKeyNames,
  SearchSchema,
  UuidPrimaryKeyNames,
  UuidSchema,
} from "./genericTabularStorageTests";

describe("SqliteTabularStorage", async () => {
  await Sqlite.init();
  let logger = getTestingLogger();
  setLogger(logger);
  runGenericTabularStorageTests(
    async () =>
      new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        CompoundSchema,
        CompoundPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        SearchSchema,
        SearchPrimaryKeyNames,
        [
          "category",
          ["category", "subcategory"],
          ["subcategory", "category"],
          "value",
          "tag",
          ["category", "tag"],
        ]
      ),
    async () => {
      const repo = new SqliteTabularStorage<typeof AllTypesSchema, typeof AllTypesPrimaryKeyNames>(
        ":memory:",
        `all_types_test_${uuid4().replace(/-/g, "_")}`,
        AllTypesSchema,
        AllTypesPrimaryKeyNames
      );
      await repo.setupDatabase();
      return repo;
    }
  );

  runAutoGeneratedKeyTests(
    async () =>
      new SqliteTabularStorage<typeof AutoIncrementSchema, typeof AutoIncrementPrimaryKeyNames>(
        ":memory:",
        `autoinc_test_${uuid4().replace(/-/g, "_")}`,
        AutoIncrementSchema,
        AutoIncrementPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof UuidSchema, typeof UuidPrimaryKeyNames>(
        ":memory:",
        `uuid_test_${uuid4().replace(/-/g, "_")}`,
        UuidSchema,
        UuidPrimaryKeyNames
      )
  );

  runSqlBulkPutTests(async () => {
    const repo = new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
      ":memory:",
      `bulk_sql_test_${uuid4().replace(/-/g, "_")}`,
      CompoundSchema,
      CompoundPrimaryKeyNames
    );
    await repo.setupDatabase();
    return repo;
  });

  it("putBulk ignores client-supplied auto-generated keys under clientProvidedKeys 'never'", async () => {
    const storage = new SqliteTabularStorage<
      typeof AutoIncrementSchema,
      typeof AutoIncrementPrimaryKeyNames
    >(
      ":memory:",
      `never_bulk_${uuid4().replace(/-/g, "_")}`,
      AutoIncrementSchema,
      AutoIncrementPrimaryKeyNames,
      [],
      "never"
    );
    await storage.setupDatabase();

    const returned = await storage.putBulk([
      { id: 999, name: "a", email: "a@x" } as never,
      { id: 999, name: "b", email: "b@x" } as never,
    ]);

    // Both client ids (999) are ignored; the database assigns distinct keys.
    expect(returned).toHaveLength(2);
    expect((returned[0] as { id: number }).id).not.toEqual(999);
    expect((returned[1] as { id: number }).id).not.toEqual(999);
    expect((returned[0] as { id: number }).id).not.toEqual((returned[1] as { id: number }).id);
    expect(await storage.get({ id: 999 } as never)).toBeUndefined();
    expect(await storage.size()).toEqual(2);
  });

  runTabularStorageContract({
    name: "SqliteTabularStorage",
    createStorage: async () => {
      const storage = new SqliteTabularStorage<
        typeof CompoundSchema,
        typeof CompoundPrimaryKeyNames
      >(
        ":memory:",
        `contract_test_${uuid4().replace(/-/g, "_")}`,
        CompoundSchema,
        CompoundPrimaryKeyNames
      );
      await storage.setupDatabase();
      return storage;
    },
    capabilities: {
      supportsSubscriptions: false,
      supportsVectorColumns: true,
      supportsTransactions: true,
      supportsQuery: true,
    },
    createVectorStorage: async () => {
      const storage = new SqliteTabularStorage<
        typeof VectorItemSchema,
        typeof VectorItemPrimaryKeyNames
      >(
        ":memory:",
        `contract_vec_${uuid4().replace(/-/g, "_")}`,
        VectorItemSchema,
        VectorItemPrimaryKeyNames
      );
      await storage.setupDatabase();
      return storage;
    },
  });

  it("rejects adversarial page orderBy before executing SQL", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      `sql_test_${uuid4().replace(/-/g, "_")}`,
      SearchSchema,
      SearchPrimaryKeyNames,
      ["category"]
    );
    await storage.setupDatabase();

    const prepareSpy = vi.spyOn((storage as any).db, "prepare");
    prepareSpy.mockClear();
    try {
      await expect(
        storage.getPage({ orderBy: [{ column: PAYLOADS[0] as any, direction: "ASC" }] })
      ).rejects.toThrow(StorageValidationError);
      await expect(
        storage.queryPage(
          { category: "electronics" },
          { orderBy: [{ column: "id", direction: "ASC; DROP--" as any }] }
        )
      ).rejects.toThrow(StorageValidationError);

      expect(prepareSpy).not.toHaveBeenCalled();
    } finally {
      prepareSpy.mockRestore();
      await storage.deleteAll();
      storage.destroy();
    }
  });
});

describe("SqliteTabularStorage.queryIndex", () => {
  it("returns projected rows containing only requested columns", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex",
      SearchSchema,
      SearchPrimaryKeyNames,
      [["category", "subcategory"]]
    );
    await storage.setupDatabase();
    await storage.put({
      id: "k1",
      category: "a",
      subcategory: "x",
      value: 1,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-01-01T00:00:00Z",
    });
    const rows = await storage.queryIndex(
      { category: "a" },
      { select: ["id", "category"], orderBy: [{ column: "subcategory", direction: "ASC" }] }
    );
    expect(rows).toHaveLength(1);
    expect(Object.keys(rows[0]).sort()).toEqual(["category", "id"]);
    expect((rows[0] as any).value).toBeUndefined();
  });

  it("throws CoveringIndexMissingError when no covering index exists", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex_noindex",
      SearchSchema,
      SearchPrimaryKeyNames,
      []
    );
    await storage.setupDatabase();
    await expect(storage.queryIndex({ category: "a" }, { select: ["id"] })).rejects.toThrow(
      /CoveringIndexMissingError|No covering index/
    );
  });

  it("returns empty array (not undefined) on no matches", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex_empty",
      SearchSchema,
      SearchPrimaryKeyNames,
      [["category"]]
    );
    await storage.setupDatabase();
    const rows = await storage.queryIndex({ category: "missing" }, { select: ["id"] });
    expect(rows).toEqual([]);
  });
});

describe("SqliteTabularStorage.withTransaction", () => {
  async function makeStorage() {
    const storage = new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
      ":memory:",
      `tx_test_${uuid4().replace(/-/g, "_")}`,
      CompoundSchema,
      CompoundPrimaryKeyNames
    );
    await storage.setupDatabase();
    return storage;
  }

  it("rolls back all writes when the callback throws", async () => {
    const storage = await makeStorage();

    await expect(
      storage.withTransaction(async (tx) => {
        await tx.put({ name: "a", type: "x", option: "v1", success: true });
        await tx.put({ name: "b", type: "x", option: "v2", success: true });
        throw new Error("boom");
      })
    ).rejects.toThrow("boom");

    expect(await storage.get({ name: "a", type: "x" })).toBeUndefined();
    expect(await storage.get({ name: "b", type: "x" })).toBeUndefined();
  });

  it("rejects nested withTransaction calls instead of corrupting the outer transaction", async () => {
    const storage = await makeStorage();

    await expect(
      storage.withTransaction(async (tx) => {
        await tx.put({ name: "outer", type: "x", option: "v", success: true });
        await tx.withTransaction(async () => {
          // unreachable
        });
      })
    ).rejects.toThrow(/does not support nesting/);

    // Outer transaction was rolled back as a result of the nested-call error.
    expect(await storage.get({ name: "outer", type: "x" })).toBeUndefined();
  });

  it("defers put events until COMMIT and discards them on ROLLBACK", async () => {
    const storage = await makeStorage();
    const observed: string[] = [];
    storage.on("put", (entity) => observed.push(entity.name));

    await storage.withTransaction(async (tx) => {
      await tx.put({ name: "committed", type: "x", option: "v", success: true });
      // No events should have been observed yet
      expect(observed).toEqual([]);
    });
    expect(observed).toEqual(["committed"]);

    observed.length = 0;

    await expect(
      storage.withTransaction(async (tx) => {
        await tx.put({ name: "doomed", type: "x", option: "v", success: true });
        throw new Error("rollback");
      })
    ).rejects.toThrow("rollback");

    // The doomed put should never have been observed by listeners.
    expect(observed).toEqual([]);
  });

  it("serializes external put() calls behind a running withTransaction (rollback case)", async () => {
    // The concurrency contract: while withTransaction is awaiting its callback,
    // an unrelated `storage.put()` invoked from outside `fn` must NOT slip into
    // the open transaction. The mutex enforces this — the external put queues
    // until COMMIT/ROLLBACK releases the lock.
    const storage = await makeStorage();

    let releaseInner: () => void = () => {};
    const innerCanFinish = new Promise<void>((resolve) => {
      releaseInner = resolve;
    });

    const txPromise = storage.withTransaction(async (tx) => {
      await tx.put({ name: "tx-row", type: "x", option: "tx", success: true });
      // Hold the transaction open until the external caller has been queued.
      await innerCanFinish;
      throw new Error("rollback");
    });

    // Yield enough microtasks for the external put() to observe withTransaction's mutex hold.
    await Promise.resolve();
    await Promise.resolve();

    const externalPut = storage.put({
      name: "external-row",
      type: "x",
      option: "external",
      success: true,
    });

    // Let the inner callback throw, triggering ROLLBACK.
    releaseInner();
    await expect(txPromise).rejects.toThrow("rollback");

    // External put runs *after* ROLLBACK and is its own committed write.
    await externalPut;

    // tx-row was rolled back, external-row was committed independently.
    expect(await storage.get({ name: "tx-row", type: "x" })).toBeUndefined();
    const ext = await storage.get({ name: "external-row", type: "x" });
    expect(ext?.option).toEqual("external");
  });
});

describe("SqliteTabularStorage regressions", () => {
  const JunctionSchema = {
    type: "object",
    properties: { a: { type: "string" }, b: { type: "string" } },
    required: ["a", "b"],
    additionalProperties: false,
  } as const satisfies DataPortSchemaObject;

  it("putBulk re-put of an existing row on an all-primary-key table is an upsert, not an error", async () => {
    const storage = new SqliteTabularStorage<typeof JunctionSchema, readonly ["a", "b"]>(
      ":memory:",
      `junction_bulk_${uuid4().replace(/-/g, "_")}`,
      JunctionSchema,
      ["a", "b"] as const
    );
    await storage.setupDatabase();
    await storage.putBulk([{ a: "x", b: "y" }]);
    const again = await storage.putBulk([{ a: "x", b: "y" }]);
    expect(again).toEqual([{ a: "x", b: "y" }]);
    expect(await storage.size()).toBe(1);
  });
});

describe("SqliteTabularStorage BigInt primary keys", () => {
  const BigIntSchema = {
    type: "object",
    properties: {
      id: { type: "integer", minimum: 0 },
      label: { type: "string" },
    },
    required: ["id", "label"],
    additionalProperties: false,
  } as const satisfies DataPortSchemaObject;
  const BigIntPrimaryKeyNames = ["id"] as const;

  it("aligns putBulk rows keyed by BigInt values above Number.MAX_SAFE_INTEGER", async () => {
    const storage = new SqliteTabularStorage<typeof BigIntSchema, typeof BigIntPrimaryKeyNames>(
      ":memory:",
      `bigint_pk_${uuid4().replace(/-/g, "_")}`,
      BigIntSchema,
      BigIntPrimaryKeyNames
    );
    await storage.setupDatabase();

    // 9007199254740993n is Number.MAX_SAFE_INTEGER + 2; it survives BigInt but
    // would collide with 9007199254740992 (MAX_SAFE_INTEGER + 1 rounded) once
    // coerced to a JS number.
    const rows = await storage.putBulk([
      { id: 9007199254740993n as unknown as number, label: "big-1" },
      { id: 9007199254740995n as unknown as number, label: "big-2" },
    ]);
    expect(rows).toHaveLength(2);
    expect(rows.map((r) => r.label)).toEqual(["big-1", "big-2"]);
  });

  it("collapses duplicate BigInt PKs last-wins in putBulk", async () => {
    const storage = new SqliteTabularStorage<typeof BigIntSchema, typeof BigIntPrimaryKeyNames>(
      ":memory:",
      `bigint_pk_dup_${uuid4().replace(/-/g, "_")}`,
      BigIntSchema,
      BigIntPrimaryKeyNames
    );
    await storage.setupDatabase();

    const returned = await storage.putBulk([
      { id: 9007199254740993n as unknown as number, label: "first" },
      { id: 9007199254740993n as unknown as number, label: "second" },
    ]);
    // Both input rows point at the same row after last-wins dedupe.
    expect(returned).toHaveLength(2);
    expect(returned[0].label).toEqual("second");
    expect(returned[1].label).toEqual("second");
    expect(await storage.size()).toEqual(1);
  });
});

describe("SqliteTabularStorage shared-connection safety", () => {
  async function makeSharedPair(): Promise<
    readonly [
      SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>,
      SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>,
      Sqlite.Database,
    ]
  > {
    const db = new Sqlite.Database(":memory:");
    const tableA = `shared_a_${uuid4().replace(/-/g, "_")}`;
    const tableB = `shared_b_${uuid4().replace(/-/g, "_")}`;
    const a = new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
      db,
      tableA,
      CompoundSchema,
      CompoundPrimaryKeyNames
    );
    const b = new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
      db,
      tableB,
      CompoundSchema,
      CompoundPrimaryKeyNames
    );
    await a.setupDatabase();
    await b.setupDatabase();
    return [a, b, db] as const;
  }

  it("sibling single-op throws ConnectionReentryError during a transaction on the same handle", async () => {
    const [a, b] = await makeSharedPair();
    let releaseInner: () => void = () => {};
    const innerCanFinish = new Promise<void>((resolve) => {
      releaseInner = resolve;
    });
    let signalTxStarted: () => void = () => {};
    const txStarted = new Promise<void>((resolve) => {
      signalTxStarted = resolve;
    });

    const txPromise = a.withTransaction(async (tx) => {
      // After this awaited put returns, we are provably inside the tx body,
      // which means the shared ConnectionMutex has already set
      // `state.txOwner = a`.
      await tx.put({ name: "tx-row", type: "x", option: "tx", success: true });
      signalTxStarted();
      await innerCanFinish;
    });

    await txStarted;

    // A sibling put from a *different* storage instance on the same handle
    // must fail fast, not sneak into the tx BEGIN/COMMIT window and not
    // block silently. The connection mutex throws ConnectionReentryError
    // synchronously with mode="sibling-op".
    let siblingErr: unknown;
    await b.put({ name: "sibling-row", type: "x", option: "sib", success: true }).catch((err) => {
      siblingErr = err;
    });

    expect(siblingErr).toBeInstanceOf(ConnectionReentryError);
    const reentry = siblingErr as ConnectionReentryError;
    expect(reentry.mode).toBe("sibling-op");
    expect(reentry.message).toContain("sibling operation");
    expect(reentry.message).toContain("'tx' proxy");
    expect(reentry.message).toContain("SAVEPOINT");
    expect(reentry.message).toContain("single storage instance");

    releaseInner();
    await txPromise;

    // The outer tx still commits cleanly, and the shared connection is
    // released so a normal sibling put now succeeds.
    expect(await a.get({ name: "tx-row", type: "x" })).toBeDefined();
    await b.put({ name: "post-tx-row", type: "x", option: "sib", success: true });
    expect(await b.get({ name: "post-tx-row", type: "x" })).toBeDefined();
  });

  it("rejects cross-instance nested withTransaction within 500ms (no hang)", async () => {
    const [a, b] = await makeSharedPair();
    const start = Date.now();
    let caught: unknown;
    try {
      await a.withTransaction(async () => {
        // From inside a's transaction, another instance (b) tries to open its own
        // withTransaction on the shared handle. This must fail, not deadlock.
        await b.withTransaction(async () => {
          // unreachable
        });
      });
    } catch (err) {
      caught = err;
    }
    expect(caught).toBeInstanceOf(ConnectionReentryError);
    const reentry = caught as ConnectionReentryError;
    expect(reentry.mode).toBe("nested-transaction");
    expect(reentry.message).toContain("open its own transaction");
    expect(reentry.message).toContain("'tx' proxy");
    expect(reentry.message).toContain("SAVEPOINT");
    expect(reentry.message).toContain("single storage instance");
    expect(Date.now() - start).toBeLessThan(500);
  });

  it("same-instance nested writes via tx proxy still work", async () => {
    const [a] = await makeSharedPair();
    await a.withTransaction(async (tx) => {
      await tx.put({ name: "n1", type: "x", option: "v1", success: true });
      await tx.putBulk([
        { name: "n2", type: "x", option: "v2", success: true },
        { name: "n3", type: "x", option: "v3", success: true },
      ]);
    });
    expect(await a.get({ name: "n1", type: "x" })).toBeDefined();
    expect(await a.get({ name: "n2", type: "x" })).toBeDefined();
    expect(await a.get({ name: "n3", type: "x" })).toBeDefined();
  });
});

describe("SqliteTabularStorage entity prototypes", () => {
  const row = {
    id: "p1",
    category: "a",
    subcategory: "x",
    value: 1,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  };

  // Each storage opens its own `:memory:` database, so one fixed table name
  // cannot collide with another test's.
  async function makeStorage(): Promise<
    SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>
  > {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "proto_probe",
      SearchSchema,
      SearchPrimaryKeyNames
    );
    await storage.setupDatabase();
    return storage;
  }

  it("returns get() entities as plain objects", async () => {
    const storage = await makeStorage();
    try {
      await storage.put(row);
      const got = await storage.get({ id: "p1" });
      // The driver hands back null-prototype rows; anything that reaches a caller
      // has to look like the plain objects every other backend returns.
      expect(Object.getPrototypeOf(got)).toBe(Object.prototype);
      // Every nullable column SearchSchema declares comes back as an explicit
      // null, `tag` included -- a column added to the schema has to be listed
      // here or toStrictEqual fails on the extra key.
      expect(got).toStrictEqual({ ...row, kind: null, tag: null });
    } finally {
      // A failed expectation must not strand the connection for the rest of the run.
      storage.destroy();
    }
  });

  it("returns updateWhere() entities as plain objects", async () => {
    const storage = await makeStorage();
    try {
      await storage.put(row);
      const updated = await storage.updateWhere({ id: "p1" }, { value: 42 });
      expect(Object.getPrototypeOf(updated)).toBe(Object.prototype);
      expect(updated).toStrictEqual({ ...row, kind: null, tag: null, value: 42 });
    } finally {
      storage.destroy();
    }
  });
});
