/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { Sqlite, SqliteTabularStorage } from "@workglow/sqlite/storage";
import { StorageValidationError } from "@workglow/storage";
import { setLogger, uuid4 } from "@workglow/util";
import { describe, expect, it, vi } from "vitest";
import { getTestingLogger } from "../../binding/TestingLogger";
import {
  AllTypesPrimaryKeyNames,
  AllTypesSchema,
  AutoIncrementPrimaryKeyNames,
  AutoIncrementSchema,
  CompoundPrimaryKeyNames,
  CompoundSchema,
  PAYLOADS,
  runAutoGeneratedKeyTests,
  runGenericTabularStorageTests,
  SearchPrimaryKeyNames,
  SearchSchema,
  UuidPrimaryKeyNames,
  UuidSchema,
} from "./genericTabularStorageTests";

describe("SqliteTabularStorage", async () => {
  await Sqlite.init();
  let logger = getTestingLogger();
  setLogger(logger);
  runGenericTabularStorageTests(
    async () =>
      new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        CompoundSchema,
        CompoundPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        SearchSchema,
        SearchPrimaryKeyNames,
        ["category", ["category", "subcategory"], ["subcategory", "category"], "value"]
      ),
    async () => {
      const repo = new SqliteTabularStorage<typeof AllTypesSchema, typeof AllTypesPrimaryKeyNames>(
        ":memory:",
        `all_types_test_${uuid4().replace(/-/g, "_")}`,
        AllTypesSchema,
        AllTypesPrimaryKeyNames
      );
      await repo.setupDatabase();
      return repo;
    }
  );

  runAutoGeneratedKeyTests(
    async () =>
      new SqliteTabularStorage<typeof AutoIncrementSchema, typeof AutoIncrementPrimaryKeyNames>(
        ":memory:",
        `autoinc_test_${uuid4().replace(/-/g, "_")}`,
        AutoIncrementSchema,
        AutoIncrementPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof UuidSchema, typeof UuidPrimaryKeyNames>(
        ":memory:",
        `uuid_test_${uuid4().replace(/-/g, "_")}`,
        UuidSchema,
        UuidPrimaryKeyNames
      )
  );

  it("rejects adversarial page orderBy before executing SQL", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      `sql_test_${uuid4().replace(/-/g, "_")}`,
      SearchSchema,
      SearchPrimaryKeyNames,
      ["category"]
    );
    await storage.setupDatabase();

    const prepareSpy = vi.spyOn((storage as any).db, "prepare");
    prepareSpy.mockClear();
    try {
      await expect(
        storage.getPage({ orderBy: [{ column: PAYLOADS[0] as any, direction: "ASC" }] })
      ).rejects.toThrow(StorageValidationError);
      await expect(
        storage.queryPage(
          { category: "electronics" },
          { orderBy: [{ column: "id", direction: "ASC; DROP--" as any }] }
        )
      ).rejects.toThrow(StorageValidationError);

      expect(prepareSpy).not.toHaveBeenCalled();
    } finally {
      prepareSpy.mockRestore();
      await storage.deleteAll();
      storage.destroy();
    }
  });
});

describe("SqliteTabularStorage.queryIndex", () => {
  it("returns projected rows containing only requested columns", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex",
      SearchSchema,
      SearchPrimaryKeyNames,
      [["category", "subcategory"]]
    );
    await storage.setupDatabase();
    await storage.put({
      id: "k1",
      category: "a",
      subcategory: "x",
      value: 1,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-01-01T00:00:00Z",
    });
    const rows = await storage.queryIndex(
      { category: "a" },
      { select: ["id", "category"], orderBy: [{ column: "subcategory", direction: "ASC" }] }
    );
    expect(rows).toHaveLength(1);
    expect(Object.keys(rows[0]).sort()).toEqual(["category", "id"]);
    expect((rows[0] as any).value).toBeUndefined();
  });

  it("throws CoveringIndexMissingError when no covering index exists", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex_noindex",
      SearchSchema,
      SearchPrimaryKeyNames,
      []
    );
    await storage.setupDatabase();
    await expect(storage.queryIndex({ category: "a" }, { select: ["id"] })).rejects.toThrow(
      /CoveringIndexMissingError|No covering index/
    );
  });

  it("returns empty array (not undefined) on no matches", async () => {
    const storage = new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
      ":memory:",
      "test_queryindex_empty",
      SearchSchema,
      SearchPrimaryKeyNames,
      [["category"]]
    );
    await storage.setupDatabase();
    const rows = await storage.queryIndex({ category: "missing" }, { select: ["id"] });
    expect(rows).toEqual([]);
  });
});

describe("SqliteTabularStorage.withTransaction", () => {
  async function makeStorage() {
    const storage = new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
      ":memory:",
      `tx_test_${uuid4().replace(/-/g, "_")}`,
      CompoundSchema,
      CompoundPrimaryKeyNames
    );
    await storage.setupDatabase();
    return storage;
  }

  it("rolls back all writes when the callback throws", async () => {
    const storage = await makeStorage();

    await expect(
      storage.withTransaction(async (tx) => {
        await tx.put({ name: "a", type: "x", option: "v1", success: true });
        await tx.put({ name: "b", type: "x", option: "v2", success: true });
        throw new Error("boom");
      })
    ).rejects.toThrow("boom");

    expect(await storage.get({ name: "a", type: "x" })).toBeUndefined();
    expect(await storage.get({ name: "b", type: "x" })).toBeUndefined();
  });

  it("rejects nested withTransaction calls instead of corrupting the outer transaction", async () => {
    const storage = await makeStorage();

    await expect(
      storage.withTransaction(async (tx) => {
        await tx.put({ name: "outer", type: "x", option: "v", success: true });
        await tx.withTransaction(async () => {
          // unreachable
        });
      })
    ).rejects.toThrow(/does not support nesting/);

    // Outer transaction was rolled back as a result of the nested-call error.
    expect(await storage.get({ name: "outer", type: "x" })).toBeUndefined();
  });

  it("defers put events until COMMIT and discards them on ROLLBACK", async () => {
    const storage = await makeStorage();
    const observed: string[] = [];
    storage.on("put", (entity) => observed.push(entity.name));

    await storage.withTransaction(async (tx) => {
      await tx.put({ name: "committed", type: "x", option: "v", success: true });
      // No events should have been observed yet
      expect(observed).toEqual([]);
    });
    expect(observed).toEqual(["committed"]);

    observed.length = 0;

    await expect(
      storage.withTransaction(async (tx) => {
        await tx.put({ name: "doomed", type: "x", option: "v", success: true });
        throw new Error("rollback");
      })
    ).rejects.toThrow("rollback");

    // The doomed put should never have been observed by listeners.
    expect(observed).toEqual([]);
  });

  it("serializes external put() calls behind a running withTransaction (rollback case)", async () => {
    // The concurrency contract: while withTransaction is awaiting its callback,
    // an unrelated `storage.put()` invoked from outside `fn` must NOT slip into
    // the open transaction. The mutex enforces this — the external put queues
    // until COMMIT/ROLLBACK releases the lock.
    const storage = await makeStorage();

    let releaseInner: () => void = () => {};
    const innerCanFinish = new Promise<void>((resolve) => {
      releaseInner = resolve;
    });

    const txPromise = storage.withTransaction(async (tx) => {
      await tx.put({ name: "tx-row", type: "x", option: "tx", success: true });
      // Hold the transaction open until the external caller has been queued.
      await innerCanFinish;
      throw new Error("rollback");
    });

    // Yield enough microtasks for the external put() to observe withTransaction's mutex hold.
    await Promise.resolve();
    await Promise.resolve();

    const externalPut = storage.put({
      name: "external-row",
      type: "x",
      option: "external",
      success: true,
    });

    // Let the inner callback throw, triggering ROLLBACK.
    releaseInner();
    await expect(txPromise).rejects.toThrow("rollback");

    // External put runs *after* ROLLBACK and is its own committed write.
    await externalPut;

    // tx-row was rolled back, external-row was committed independently.
    expect(await storage.get({ name: "tx-row", type: "x" })).toBeUndefined();
    const ext = await storage.get({ name: "external-row", type: "x" });
    expect(ext?.option).toEqual("external");
  });
});
