/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import type { Sqlite } from "@workglow/sqlite/storage";
import type {
  AutoGeneratedKeys,
  InsertEntity,
  IVectorStorage,
  VectorSearchOptions,
} from "@workglow/storage";
import {
  assertVectorShape,
  emitSimilaritySearch,
  getMetadataProperty,
  getVectorProperty,
  matchesFilter,
  validateVectorEntities,
} from "@workglow/storage";
import type {
  DataPortSchemaObject,
  FromSchema,
  TypedArray,
  TypedArrayConstructor,
  TypedArraySchemaOptions,
} from "@workglow/util/schema";
import { cosineSimilarity } from "@workglow/util/schema";
import { SqliteTabularStorage } from "./SqliteTabularStorage";

/**
 * SQLite vector repository implementation using tabular storage underneath.
 * Stores vectors as JSON-encoded arrays with metadata.
 *
 * @template Schema - The schema for the vector
 * @template PrimaryKeyNames - The primary key names for the vector
 * @template VectorCtor - Constructor for stored vectors (default {@link typeof Float32Array})
 * @template Metadata - The metadata type for the vector
 * @template Entity - The entity type for the vector
 */
export class SqliteVectorStorage<
  Schema extends DataPortSchemaObject,
  PrimaryKeyNames extends ReadonlyArray<keyof Schema["properties"]>,
  Metadata extends Record<string, unknown> | undefined = Record<string, unknown>,
  Entity = FromSchema<Schema, TypedArraySchemaOptions>,
  InsertType extends InsertEntity<Entity, AutoGeneratedKeys<Schema>> = InsertEntity<
    Entity,
    AutoGeneratedKeys<Schema>
  >,
>
  extends SqliteTabularStorage<Schema, PrimaryKeyNames, Entity>
  implements IVectorStorage<Metadata, Schema, Entity, PrimaryKeyNames>
{
  private vectorDimensions: number;
  private readonly vectorCtor: TypedArrayConstructor;
  private vectorPropertyName: keyof Entity;
  private metadataPropertyName: keyof Entity | undefined;

  /**
   * Creates a new SQLite vector repository
   * @param dbOrPath - Either a Database instance or a path to the SQLite database file
   * @param table - The name of the table to use for storage (defaults to 'vectors')
   * @param schema - The schema for the entity
   * @param primaryKeyNames - Array of property names forming the primary key
   * @param indexes - Array of columns to index
   * @param dimensions - The number of dimensions of the vector
   * @param vectorCtor - TypedArray constructor used when deserializing JSON vectors (e.g. {@link Float32Array})
   */
  constructor(
    dbOrPath: string | Sqlite.Database,
    table: string = "vectors",
    schema: Schema,
    primaryKeyNames: PrimaryKeyNames,
    indexes: readonly (keyof NoInfer<Entity> | readonly (keyof NoInfer<Entity>)[])[] = [],
    dimensions: number,
    vectorCtor: TypedArrayConstructor = Float32Array
  ) {
    super(dbOrPath, table, schema, primaryKeyNames, indexes);

    this.vectorDimensions = dimensions;
    this.vectorCtor = vectorCtor;

    // Cache vector and metadata property names from schema
    const vectorProp = getVectorProperty(schema);
    if (!vectorProp) {
      throw new Error("Schema must have a property with type array and format TypedArray");
    }
    this.vectorPropertyName = vectorProp as keyof Entity;
    this.metadataPropertyName = getMetadataProperty(schema) as keyof Entity | undefined;
  }

  getVectorDimensions(): number {
    return this.vectorDimensions;
  }

  /**
   * The stored vector as a TypedArray, from whichever form the read produced.
   *
   * SQLite holds it as a JSON string, but the tabular read this class inherits
   * already decodes a `TypedArraySchema` column back to a TypedArray — so by
   * the time a row reaches `similaritySearch` the column is usually decoded
   * and occasionally not (a row written by an older release, a caller handing
   * back a raw row). Accepting both is what makes this correct in either case
   * rather than in whichever one the read layer happens to do today.
   */
  private toVector(stored: unknown): TypedArray {
    if (typeof stored === "string") {
      return new this.vectorCtor(JSON.parse(stored) as number[]);
    }
    if (Array.isArray(stored)) {
      return new this.vectorCtor(stored);
    }
    return stored as TypedArray;
  }

  /**
   * Validate every entity's vector before delegating to the tabular upsert.
   * Without this, a malformed vector reaches the JSON encoder downstream and
   * the store silently persists garbage that no `similaritySearch` can recover.
   */
  override async put(entity: InsertType): Promise<Entity> {
    validateVectorEntities(
      [entity as Record<string, unknown>],
      this.vectorPropertyName as string,
      this.vectorDimensions
    );
    return super.put(entity);
  }

  override async putBulk(entities: InsertType[]): Promise<Entity[]> {
    validateVectorEntities(
      entities as ReadonlyArray<Record<string, unknown>>,
      this.vectorPropertyName as string,
      this.vectorDimensions
    );
    return super.putBulk(entities);
  }

  async similaritySearch(query: TypedArray, options: VectorSearchOptions<Metadata> = {}) {
    assertVectorShape(query, this.vectorDimensions, "query");
    const { topK = 10, filter, scoreThreshold = 0 } = options;
    const results: Array<Entity & { score: number }> = [];

    const allEntities = (await this.getAll()) || [];

    for (const entity of allEntities) {
      const vector = this.toVector(entity[this.vectorPropertyName]);
      const metadata = this.metadataPropertyName
        ? (entity[this.metadataPropertyName] as Metadata)
        : ({} as Metadata);

      // Apply filter if provided
      if (filter && !matchesFilter(metadata, filter)) {
        continue;
      }

      // Calculate similarity
      const score = cosineSimilarity(query, vector);

      // Apply threshold
      if (score < scoreThreshold) {
        continue;
      }

      results.push({
        ...entity,
        score,
      } as Entity & { score: number });
    }

    // Sort by score descending and take top K
    results.sort((a, b) => b.score - a.score);
    const topResults = results.slice(0, topK);

    return emitSimilaritySearch(this.events, query, topResults);
  }
}
