/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { TaskOutputRepository } from "../storage/TaskOutputRepository";
import type { TaskInput, TaskOutput } from "../task/TaskTypes";

export interface RunPrivateCacheRepoOptions {
  backing: TaskOutputRepository;
  runId: string;
}

/**
 * Wraps a TaskOutputRepository so that all entries are namespaced by `runId`.
 *
 * Run scoping is delegated to the backing repository's run-scoped methods
 * ({@link TaskOutputRepository.saveOutputForRun} etc.): {@link CacheCoordinator}
 * passes each task's instance `id` as the entry's `taskType`, and this wrapper
 * threads its `runId` so the backing stores it as a first-class column under a
 * runId-leading primary key. The input fingerprint is unchanged for resume
 * lookups within the same node. The backing must be a run-private repository
 * (e.g. `RunPrivateTaskOutputRepository`).
 *
 * - Two wrappers with the same `runId` (e.g., a restart after a crash) see each
 *   other's writes via the backing store — that's the restart-survival contract.
 * - Two wrappers with different `runId`s see only their own entries.
 *
 * Durable restart-resume requires deterministic task ids. When a task does not
 * pin `config.id` to a stable value the default constructor mints a fresh v4
 * UUID per process, so the cache key would change across restarts and orphan
 * every row. In that case {@link CacheCoordinator} keys by task type instead
 * and signals the fallback via {@link noteFallbackKey}; this wrapper warns once
 * per process to tell the operator that the cache is best-effort intra-process
 * only until task ids are pinned.
 */
export class RunPrivateCacheRepo extends TaskOutputRepository {
  private static fallbackWarned = false;

  private readonly backing: TaskOutputRepository;
  private readonly runId: string;
  private observedFallback: boolean = false;

  constructor({ backing, runId }: RunPrivateCacheRepoOptions) {
    super({ outputCompression: backing.outputCompression });
    this.backing = backing;
    this.runId = runId;
  }

  /**
   * Called by {@link CacheCoordinator} the first time it has to key a private
   * cache entry by task type because the task id is autogenerated. Emits a
   * single `console.warn` per process so deployments without pinned ids learn
   * that crash-resume is degraded; subsequent fallbacks are silent.
   */
  public noteFallbackKey(): void {
    this.observedFallback = true;
    if (RunPrivateCacheRepo.fallbackWarned) return;
    RunPrivateCacheRepo.fallbackWarned = true;
    console.warn(
      "[RunPrivateCacheRepo] Private cache fell back to taskType keying because " +
        "task.id is autogenerated; pin task.id to enable crash-resume."
    );
  }

  /** @internal Test-only hook for inspecting whether any fallback was observed. */
  public hasObservedFallback(): boolean {
    return this.observedFallback;
  }

  public async saveOutput(
    cacheIdentity: string,
    inputs: TaskInput,
    output: TaskOutput,
    createdAt?: Date
  ): Promise<void> {
    await this.backing.saveOutputForRun(this.runId, cacheIdentity, inputs, output, createdAt);
  }

  public async getOutput(
    cacheIdentity: string,
    inputs: TaskInput
  ): Promise<TaskOutput | undefined> {
    return this.backing.getOutputForRun(this.runId, cacheIdentity, inputs);
  }

  /**
   * Override of `TaskOutputRepository.clear()` that only deletes entries for
   * THIS wrapper's `runId`. Entries from other runs are not touched. Use the
   * backing repository directly if you need a global clear.
   */
  public async clear(): Promise<void> {
    await this.clearRun();
  }

  /**
   * Delete every entry written through this wrapper's `runId`. Called by the
   * graph runner after a successful run. An indexed `deleteSearch({ runId })`
   * on the backing's runId-leading primary key — not a table scan.
   */
  public async clearRun(): Promise<void> {
    await this.backing.deleteRun(this.runId);
  }

  /**
   * Returns the count of entries for THIS wrapper's `runId`. Consistent with
   * `saveOutput`/`getOutput`/`clear()` being run-scoped.
   */
  public async size(): Promise<number> {
    return this.backing.sizeForRun(this.runId);
  }

  /**
   * Override of `TaskOutputRepository.clearOlderThan()` scoped to THIS
   * wrapper's `runId`. Without the scope, the wrapper would prune other runs'
   * private rows. An indexed `deleteSearch({ runId, createdAt: { "<" } })`.
   */
  public async clearOlderThan(olderThanInMs: number): Promise<void> {
    await this.backing.deleteRunOlderThan(this.runId, olderThanInMs);
  }

  public isDurable(): boolean {
    return this.backing.isDurable();
  }
}
