/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  CACHE_REGISTRY,
  DefaultCacheRegistry,
  RunPrivateCacheRepo,
  Task,
  TaskGraph,
  type CachePolicy,
} from "@workglow/task-graph";
import { RunPrivateInMemoryTaskOutputRepository } from "@workglow/task-graph/test";
import { Container, ServiceRegistry } from "@workglow/util";
import type { DataPortSchema } from "@workglow/util/schema";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

class CountingPrivateTask extends Task<{ q: string }, { r: string }> {
  public static override type = "CountingPrivateTask";
  public static override cachePolicy: CachePolicy = { kind: "private" };
  public static runs: { q: string }[] = [];

  public static override inputSchema(): DataPortSchema {
    return {
      type: "object",
      properties: {
        q: { type: "string" },
      },
      required: ["q"],
      additionalProperties: false,
    } as const satisfies DataPortSchema;
  }

  public static override outputSchema(): DataPortSchema {
    return {
      type: "object",
      properties: {
        r: { type: "string" },
      },
      required: ["r"],
      additionalProperties: false,
    } as const satisfies DataPortSchema;
  }

  public override async execute(input: { q: string }): Promise<{ r: string }> {
    CountingPrivateTask.runs.push({ q: input.q });
    return { r: `done:${input.q}` };
  }
}

async function freshRepo(): Promise<RunPrivateInMemoryTaskOutputRepository> {
  const r = new RunPrivateInMemoryTaskOutputRepository();
  await (r as any).setupDatabase?.();
  return r;
}

function freshServices(
  privateRepo: RunPrivateInMemoryTaskOutputRepository | RunPrivateCacheRepo
): ServiceRegistry {
  const services = new ServiceRegistry(new Container());
  services.registerInstance(
    CACHE_REGISTRY,
    new DefaultCacheRegistry({ private: privateRepo as any })
  );
  return services;
}

/**
 * The original autogenerated-uuid bug: two consecutive runs of the same graph
 * (modeling a crash + restart) mint fresh task ids on every construction, so a
 * private cache keyed strictly on `task.id` could never reuse prior rows. With
 * the fallback in place the cache keys on `task.type` and the second run hits.
 */
describe("RunPrivateCacheRepo cache-key fallback for autogenerated task ids", () => {
  let warnSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    CountingPrivateTask.runs = [];
    // Reset the warn-once gate so each test sees fresh behavior.
    (RunPrivateCacheRepo as any).fallbackWarned = false;
    warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
  });

  afterEach(() => {
    warnSpy.mockRestore();
  });

  it("Task.hasDeterministicId(): true for pinned ids, false for autogen v4 UUIDs", () => {
    const pinned = new CountingPrivateTask({
      id: "pinned-node-1",
      defaults: { q: "hello" },
    } as any);
    expect(pinned.hasDeterministicId()).toBe(true);

    const autogen = new CountingPrivateTask({ defaults: { q: "hello" } } as any);
    expect(autogen.hasDeterministicId()).toBe(false);
  });

  it("crash-restart: a fresh graph with autogenerated ids reuses prior run-private rows via the type-key fallback", async () => {
    // Models a real crash: a prior partial run left rows in the run-private
    // namespace. The restart constructs new task instances (so new uuid ids)
    // and expects to find those rows. Without the fallback, the new uuids
    // never match. With the fallback, both rows are keyed by task type and
    // the restart hits cache for both ports.
    const backing = await freshRepo();
    const runId = "crash-restart-run";

    // Seed: write what the prior run would have left under the type-keyed
    // fallback. `__cv` is the cache version sentinel injected by CacheCoordinator.
    const seeder = new RunPrivateCacheRepo({ backing, runId });
    await seeder.saveOutput(
      CountingPrivateTask.type,
      { q: "alpha", __cv: "1" },
      { r: "done:alpha" }
    );

    const services = freshServices(backing);
    const graph = new TaskGraph();
    // Single task instance with an autogenerated id — same shape that the
    // crashed run would have had on restart.
    graph.addTask(new CountingPrivateTask({ defaults: { q: "alpha" } } as any));

    await graph.run({}, { runId, registry: services });

    // The cached row was reused — execute() was never called.
    expect(CountingPrivateTask.runs.length).toBe(0);
  });

  it("pinned-id tasks still key by id (not type) and never trigger the fallback warn", async () => {
    const backing = await freshRepo();
    const runId = "pinned-run";

    // Seed the row under the pinned task-id key; the runtime should find it
    // there and skip execution. (The type-key path would NOT have this row.)
    const seeder = new RunPrivateCacheRepo({ backing, runId });
    await seeder.saveOutput("pinned-node", { q: "stable", __cv: "1" }, { r: "cached" });

    const services = freshServices(backing);
    const graph = new TaskGraph();
    graph.addTask(new CountingPrivateTask({ id: "pinned-node", defaults: { q: "stable" } } as any));

    await graph.run({}, { runId, registry: services });

    // Pinned id matched the seeded row exactly — no re-execution.
    expect(CountingPrivateTask.runs.length).toBe(0);
    // No fallback warn from RunPrivateCacheRepo should appear in console.warn.
    const fallbackWarns = warnSpy.mock.calls.filter((args: unknown[]) =>
      String(args[0] ?? "").includes("[RunPrivateCacheRepo]")
    );
    expect(fallbackWarns.length).toBe(0);
  });

  it("warns exactly once per process across many fallback writes", async () => {
    const backing = await freshRepo();
    const services = freshServices(backing);

    const graph = new TaskGraph();
    // Three autogen-id tasks, none pinned — all should trigger the fallback path
    // on first execution (the cache-save path).
    graph.addTask(new CountingPrivateTask({ defaults: { q: "a" } } as any));
    graph.addTask(new CountingPrivateTask({ defaults: { q: "b" } } as any));
    graph.addTask(new CountingPrivateTask({ defaults: { q: "c" } } as any));

    await graph.run({}, { runId: "warn-once-run-1", registry: services });

    // A second graph + run keeps producing fallbacks — warn must still be once total.
    const graph2 = new TaskGraph();
    graph2.addTask(new CountingPrivateTask({ defaults: { q: "d" } } as any));
    await graph2.run({}, { runId: "warn-once-run-2", registry: services });

    // Filter for our specific fallback warning to ignore unrelated runner warns.
    const fallbackWarns = warnSpy.mock.calls.filter((args: unknown[]) =>
      String(args[0] ?? "").includes("[RunPrivateCacheRepo]")
    );
    expect(fallbackWarns.length).toBe(1);
    expect(String(fallbackWarns[0]?.[0])).toContain("pin task.id to enable crash-resume");
  });
});
