/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { DuckDb, DuckDbDatabase } from "@workglow/duckdb/storage";
import {
  AnyTabularStorage,
  AutoGeneratedKeys,
  BaseSqlTabularStorage,
  buildSearchWhere,
  ClientProvidedKeysOption,
  CoveringIndexQueryOptions,
  DeleteSearchCriteria,
  InsertEntity,
  ITabularMigration,
  ITabularMigrationApplier,
  KeyGenerationStrategy,
  MIGRATIONS_TABLE,
  Page,
  PageRequest,
  pickCoveringIndex,
  PostgresDialect,
  QueryOptions,
  safeEmit,
  SearchCriteria,
  SimplifyPrimaryKey,
  SqlTabularMigrationApplier,
  TabularChangePayload,
  TabularSubscribeOptions,
  TYPED_ARRAY_CTORS,
  ValueOptionType,
} from "@workglow/storage";
import { createServiceToken, uuid4 } from "@workglow/util";
import {
  DataPortSchemaObject,
  FromSchema,
  JsonSchema,
  TypedArraySchemaOptions,
} from "@workglow/util/schema";

export const DUCKDB_TABULAR_REPOSITORY = createServiceToken<AnyTabularStorage>(
  "storage.tabularRepository.duckdb"
);

/**
 * A DuckDB-based tabular repository implementation.
 *
 * DuckDB speaks Postgres-flavored SQL (double-quoted identifiers, `$N`
 * placeholders, `INSERT … ON CONFLICT … RETURNING *`, sequences,
 * `information_schema`), so the SQL here mirrors {@link PostgresTabularStorage}.
 * It is an embedded single-connection engine like SQLite, so concurrency
 * control mirrors {@link SqliteTabularStorage}: a per-instance promise-chain
 * mutex serializes all operations, and `withTransaction` runs raw
 * `BEGIN`/`COMMIT`/`ROLLBACK` on the shared connection.
 *
 * @template Schema - The schema definition for the entity
 * @template PrimaryKeyNames - Array of property names that form the primary key
 */
export class DuckDbTabularStorage<
  Schema extends DataPortSchemaObject,
  PrimaryKeyNames extends ReadonlyArray<keyof Schema["properties"]>,
  // computed types
  Entity = FromSchema<Schema, TypedArraySchemaOptions>,
  PrimaryKey = SimplifyPrimaryKey<Entity, PrimaryKeyNames>,
  Value = Omit<Entity, PrimaryKeyNames[number] & keyof Entity>,
  InsertType extends InsertEntity<Entity, AutoGeneratedKeys<Schema>> = InsertEntity<
    Entity,
    AutoGeneratedKeys<Schema>
  >,
> extends BaseSqlTabularStorage<Schema, PrimaryKeyNames, Entity, PrimaryKey, Value, InsertType> {
  /** Path to open lazily, or the already-open database handle. */
  private readonly dbOrPath: string | DuckDbDatabase;
  /** Memoized open. Opening a DuckDB instance is async, so it happens on first use. */
  private dbPromise: Promise<DuckDbDatabase> | undefined;

  /**
   * Creates a new DuckDB tabular repository.
   *
   * @param dbOrPath - Either an open {@link DuckDbDatabase} or a path to the
   *                   DuckDB database file (`":memory:"` for in-memory)
   * @param table - The name of the table to use for storage (defaults to 'tabular_store')
   * @param schema - Schema defining the structure of the entity
   * @param primaryKeyNames - Array of property names that form the primary key
   * @param indexes - Array of columns or column arrays to make searchable. Each string or single column creates a single-column index,
   *                    while each array creates a compound index with columns in the specified order.
   * @param clientProvidedKeys - How to handle client-provided values for auto-generated keys
   */
  constructor(
    dbOrPath: string | DuckDbDatabase = ":memory:",
    table: string = "tabular_store",
    schema: Schema,
    primaryKeyNames: PrimaryKeyNames,
    indexes: readonly (keyof NoInfer<Entity> | readonly (keyof NoInfer<Entity>)[])[] = [],
    clientProvidedKeys: ClientProvidedKeysOption = "if-missing",
    tabularMigrations?: ReadonlyArray<ITabularMigration>,
    uniqueIndexes: readonly (readonly (keyof NoInfer<Entity>)[])[] = []
  ) {
    super(
      table,
      schema,
      primaryKeyNames,
      indexes,
      clientProvidedKeys,
      tabularMigrations,
      table,
      uniqueIndexes
    );
    this.dbOrPath = dbOrPath;
  }

  /** Opens (or returns) the underlying database handle. */
  protected getDb(): Promise<DuckDbDatabase> {
    return (this.dbPromise ??=
      typeof this.dbOrPath === "string"
        ? DuckDb.open(this.dbOrPath)
        : Promise.resolve(this.dbOrPath));
  }

  /** Name of the sequence backing an autoincrement key. Inputs are DDL-validated. */
  private sequenceName(column: string): string {
    return `${this.table}_${column}_seq`;
  }

  /**
   * Override to back auto-increment keys with a sequence — DuckDB has no
   * SERIAL; the idiom is `CREATE SEQUENCE` + `DEFAULT nextval(...)`.
   * UUID keys are generated client-side (see {@link generateKeyValue}), so
   * they stay plain NOT NULL columns.
   */
  protected override constructPrimaryKeyColumns($delimiter: string = ""): string {
    const cols = Object.entries<JsonSchema>(this.primaryKeySchema.properties)
      .map(([key, typeDef]) => {
        if (this.isAutoGeneratedKey(key) && this.autoGeneratedKeyStrategy === "autoincrement") {
          const sqlType = this.mapTypeToSQL(typeDef);
          return `${$delimiter}${key}${$delimiter} ${sqlType} NOT NULL DEFAULT nextval('${this.sequenceName(key)}')`;
        }
        const sqlType = this.mapTypeToSQL(typeDef);
        return `${$delimiter}${key}${$delimiter} ${sqlType} NOT NULL`;
      })
      .join(", ");
    return cols;
  }

  /**
   * Initializes the database table with the required schema.
   * Creates the table if it doesn't exist with primary key and value columns.
   * Must be called before using any other methods.
   */
  public override async setupDatabase(): Promise<void> {
    if (this.tabularMigrations && this.tabularMigrations.length > 0) {
      // Probe BEFORE creating so we can tell the orchestrator whether the
      // table existed beforehand. We always create the table at the target
      // schema (idempotent via CREATE TABLE IF NOT EXISTS); the `freshTable`
      // flag lets the orchestrator take the mark-all-applied fast path on a
      // brand-new DB instead of running migration ops against a schema that
      // already matches them.
      const exists = await this.tableExistsAsync();
      await this.createTableAndIndexes();
      await this.applyTabularMigrations({ freshTable: !exists });
      // For pre-existing DBs that ran migrations, re-assert declared indexes
      // (idempotent). On fresh DBs we already did this in createTableAndIndexes.
      if (exists) {
        await this.createDeclaredIndexes();
      }
      return;
    }
    await this.createTableAndIndexes();
  }

  private async tableExistsAsync(): Promise<boolean> {
    const db = await this.getDb();
    const r = await db.query<{ x: number }>(
      `SELECT 1 AS x FROM information_schema.tables WHERE table_name = $1 LIMIT 1`,
      [this.table]
    );
    return r.rows.length > 0;
  }

  private async createTableAndIndexes(): Promise<void> {
    const db = await this.getDb();
    // Sequences backing autoincrement keys must exist before the CREATE TABLE
    // that references them in a DEFAULT clause.
    if (this.hasAutoGeneratedKey() && this.autoGeneratedKeyStrategy === "autoincrement") {
      for (const key of Object.keys(this.primaryKeySchema.properties)) {
        if (this.isAutoGeneratedKey(key)) {
          await db.query(`CREATE SEQUENCE IF NOT EXISTS "${this.sequenceName(key)}" START 1`);
        }
      }
    }
    const sql = `
      CREATE TABLE IF NOT EXISTS "${this.table}" (
        ${this.constructPrimaryKeyColumns('"')} ${this.constructValueColumns('"')},
        PRIMARY KEY (${this.primaryKeyColumnList('"')})
      )
    `;
    await db.query(sql);
    await this.createDeclaredIndexes();
  }

  /**
   * Index-creation loop, idempotent (`CREATE INDEX IF NOT EXISTS`) so the
   * migration path can re-run it after migrations.
   */
  private async createDeclaredIndexes(): Promise<void> {
    const db = await this.getDb();
    const pkColumns = this.primaryKeyColumns();
    const createdIndexes = new Set<string>();
    for (const searchSpec of this.indexes) {
      const columns = Array.isArray(searchSpec) ? searchSpec : [searchSpec];
      if (columns.length <= pkColumns.length) {
        const isPkPrefix = columns.every((col, idx) => col === (pkColumns[idx] as string));
        if (isPkPrefix) continue;
      }
      const indexName = `${this.table}_${columns.join("_")}`;
      const columnList = columns.map((col) => `"${String(col)}"`).join(", ");
      const columnKey = columns.join(",");
      if (createdIndexes.has(columnKey)) continue;
      const isRedundant = Array.from(createdIndexes).some((existing) => {
        const existingCols = existing.split(",");
        return (
          existingCols.length >= columns.length &&
          columns.every((col, idx) => col === existingCols[idx])
        );
      });
      if (!isRedundant) {
        await db.query(
          `CREATE INDEX IF NOT EXISTS "${indexName}" ON "${this.table}" (${columnList})`
        );
        createdIndexes.add(columnKey);
      }
    }
    await this.createDeclaredUniqueIndexes();
  }

  /**
   * Emit `CREATE UNIQUE INDEX IF NOT EXISTS` for each declared unique tuple.
   * Index name: `${table}_uniq_${cols.join("_")}` — distinct from the
   * non-unique `${table}_${cols.join("_")}` pattern above so a tuple can carry
   * both a search index and a UNIQUE constraint without name collision.
   */
  private async createDeclaredUniqueIndexes(): Promise<void> {
    const db = await this.getDb();
    for (const columns of this.uniqueIndexes) {
      const indexName = `${this.table}_uniq_${columns.map(String).join("_")}`;
      const columnList = columns.map((col) => `"${String(col)}"`).join(", ");
      await db.query(
        `CREATE UNIQUE INDEX IF NOT EXISTS "${indexName}" ON "${this.table}" (${columnList})`
      );
    }
  }

  public override getMigrationApplier(): ITabularMigrationApplier | null {
    return new DuckDbTabularMigrationApplierImpl(this);
  }

  /**
   * Maps JSON Schema types to DuckDB column types.
   *
   * DuckDB has rich native types; the choices here favor lossless JS
   * round-trips: date-times stay VARCHAR (ISO strings, like the SQLite
   * backend), integers use BIGINT (converted back from JS bigint on read),
   * arrays/objects are serialized JSON text.
   */
  protected mapTypeToSQL(typeDef: JsonSchema): string {
    const actualType = this.getNonNullType(typeDef);
    if (typeof actualType === "boolean") {
      return "VARCHAR /* boolean schema */";
    }

    if (actualType.contentEncoding === "blob") return "BLOB";

    switch (actualType.type) {
      case "string":
        // ISO strings round-trip byte-for-byte; native TIMESTAMP would
        // re-format them on read.
        if (actualType.format === "date-time") return "VARCHAR";
        if (actualType.format === "date") return "VARCHAR";
        if (typeof actualType.maxLength === "number") {
          return `VARCHAR /* VARCHAR(${actualType.maxLength}) */`;
        }
        return "VARCHAR";

      case "number":
      case "integer":
        // multipleOf === 1 means whole-number multiples, i.e. integers.
        if (actualType.multipleOf === 1 || actualType.type === "integer") {
          return "BIGINT";
        }
        return "DOUBLE";

      case "boolean":
        return "BOOLEAN";

      case "array":
      case "object":
        return "VARCHAR /* JSON */";

      default:
        return "VARCHAR /* unknown type */";
    }
  }

  /**
   * Generates a key value for string UUID keys.
   * Integer keys are generated by the backing sequence in the database.
   */
  protected override generateKeyValue(
    columnName: string,
    strategy: KeyGenerationStrategy
  ): string | number {
    if (strategy === "uuid") {
      return uuid4();
    }
    throw new Error(
      `DuckDB autoincrement keys are generated by the database sequence, not client-side. Column: ${columnName}`
    );
  }

  /**
   * Convert JS values to DuckDB-compatible values. Objects and arrays
   * (including TypedArrays) are serialized to JSON text; booleans stay native.
   */
  protected override jsToSqlValue(column: string, value: Entity[keyof Entity]): ValueOptionType {
    if (value !== null && value !== undefined && typeof value === "object") {
      if (value instanceof Date) {
        return super.jsToSqlValue(column, value);
      }
      if (value instanceof Uint8Array) {
        return super.jsToSqlValue(column, value);
      }
      if (typeof Buffer !== "undefined" && value instanceof Buffer) {
        return super.jsToSqlValue(column, value);
      }
      // Serialize TypedArrays as JSON arrays (not the integer-keyed object JSON.stringify produces)
      if (ArrayBuffer.isView(value) && !(value instanceof DataView)) {
        return JSON.stringify(Array.from(value as unknown as ArrayLike<number>)) as ValueOptionType;
      }
      // Convert ALL other objects and arrays to JSON string
      return JSON.stringify(value) as ValueOptionType;
    }

    if (value === null) {
      const typeDef = this.schema.properties[column as keyof typeof this.schema.properties] as
        JsonSchema | undefined;
      if (typeDef && this.isNullable(typeDef)) {
        return null;
      }
    }

    const typeDef = this.schema.properties[column as keyof typeof this.schema.properties] as
      JsonSchema | undefined;
    if (typeDef) {
      const actualType = this.getNonNullType(typeDef);
      const isBoolean =
        typeDef === true || (typeof actualType !== "boolean" && actualType.type === "boolean");
      if (isBoolean) {
        if (typeof value === "boolean") return value;
        if (typeof value === "number") return value !== 0;
        if (typeof value === "string") return value === "1" || value.toLowerCase() === "true";
      }
    }

    return super.jsToSqlValue(column, value);
  }

  /**
   * Convert DuckDB values to JS values. The driver wrapper already
   * normalizes bigint → number and blob objects → Uint8Array; this layer
   * re-hydrates JSON text into arrays/objects/TypedArrays per the schema.
   */
  protected override sqlToJsValue(column: string, value: ValueOptionType): Entity[keyof Entity] {
    const typeDef = this.schema.properties[column as keyof typeof this.schema.properties] as
      JsonSchema | undefined;
    if (typeDef) {
      if (value === null && this.isNullable(typeDef)) {
        return null as Entity[keyof Entity];
      }
      const actualType = this.getNonNullType(typeDef);
      const isObject =
        typeDef === true || (typeof actualType !== "boolean" && actualType.type === "object");
      const isArray =
        typeDef === true || (typeof actualType !== "boolean" && actualType.type === "array");
      const isBoolean =
        typeDef === true || (typeof actualType !== "boolean" && actualType.type === "boolean");
      const isNumeric =
        typeof actualType !== "boolean" &&
        (actualType.type === "number" || actualType.type === "integer");

      if (isBoolean) {
        if (typeof value === "boolean") return value as Entity[keyof Entity];
        if (typeof value === "number") return (value !== 0) as Entity[keyof Entity];
        if (typeof value === "string")
          return (value === "1" || value.toLowerCase() === "true") as Entity[keyof Entity];
      }

      if (isNumeric) {
        if (typeof value === "number") return value as Entity[keyof Entity];
        if (typeof value === "bigint") return Number(value) as Entity[keyof Entity];
        if (typeof value === "string") {
          const parsed = Number(value);
          if (!isNaN(parsed)) return parsed as Entity[keyof Entity];
        }
      }

      if (isArray || isObject) {
        if (typeof value === "string") {
          try {
            const parsed = JSON.parse(value) as unknown;
            // Reconstruct TypedArray if schema specifies it
            if (isArray && typeof actualType !== "boolean") {
              const fmt = typeof actualType.format === "string" ? actualType.format : "";
              if (fmt.startsWith("TypedArray")) {
                const ctorName =
                  fmt === "TypedArray" ? "Float32Array" : fmt.slice("TypedArray:".length);
                const Ctor = TYPED_ARRAY_CTORS[ctorName];
                if (Ctor) {
                  const nums: number[] = Array.isArray(parsed)
                    ? (parsed as number[])
                    : Object.values(parsed as Record<string, number>);
                  return new Ctor(nums) as Entity[keyof Entity];
                }
              }
            }
            return parsed as Entity[keyof Entity];
          } catch {
            // If parsing fails, return the value as-is (might be a string that looks like JSON)
            return value as Entity[keyof Entity];
          }
        }
        return value as Entity[keyof Entity];
      }
    }
    return super.sqlToJsValue(column, value);
  }

  /** Hydrate a row returned by DuckDB back into entity-shaped JS values. */
  private hydrateRow(row: unknown): Entity {
    const entity = row as Entity;
    const record = entity as Record<string, unknown>;
    for (const key in this.schema.properties) {
      record[key] = this.sqlToJsValue(key, record[key] as ValueOptionType);
    }
    return entity;
  }

  /**
   * Builds the parameterized `INSERT … ON CONFLICT … RETURNING *` SQL for a
   * single entity, applying the auto-generated-key policy. Shared by
   * {@link put} and {@link putBulk}.
   */
  private buildPutSql(entity: InsertType): { sql: string; params: ValueOptionType[] } {
    const columnsToInsert: string[] = [];
    const paramsToInsert: ValueOptionType[] = [];

    const pkColumns = this.primaryKeyColumns();
    const entityRecord = entity as Record<string, unknown>;
    for (const col of pkColumns) {
      const colStr = String(col);

      if (this.isAutoGeneratedKey(colStr)) {
        const clientProvidedValue = entityRecord[colStr];
        const hasClientValue = clientProvidedValue !== undefined && clientProvidedValue !== null;

        let shouldUseClientValue = false;
        if (this.clientProvidedKeys === "never") {
          shouldUseClientValue = false;
        } else if (this.clientProvidedKeys === "always") {
          if (!hasClientValue) {
            throw new Error(
              `Auto-generated key "${colStr}" is required when clientProvidedKeys is "always"`
            );
          }
          shouldUseClientValue = true;
        } else {
          // "if-missing" - use client value if provided
          shouldUseClientValue = hasClientValue;
        }

        if (shouldUseClientValue) {
          columnsToInsert.push(colStr);
          paramsToInsert.push(
            this.jsToSqlValue(colStr, clientProvidedValue as Entity[keyof Entity])
          );
        } else if (this.autoGeneratedKeyStrategy === "uuid") {
          // Client-side UUID generation (DuckDB has gen_random_uuid(), but
          // generating here keeps the returned entity identical to the row
          // without an extra round-trip and matches the SQLite backend).
          columnsToInsert.push(colStr);
          paramsToInsert.push(this.generateKeyValue(colStr, "uuid"));
        }
        // Otherwise skip it — the backing sequence generates the value.
        continue;
      }

      columnsToInsert.push(colStr);
      const value = entityRecord[colStr];
      paramsToInsert.push(this.jsToSqlValue(colStr, value as Entity[keyof Entity]));
    }

    const valueColumns = this.valueColumns();
    for (const col of valueColumns) {
      const colStr = String(col);
      columnsToInsert.push(colStr);
      const value = entityRecord[colStr];
      paramsToInsert.push(this.jsToSqlValue(colStr, value as Entity[keyof Entity]));
    }

    const columnList = columnsToInsert.map((c) => `"${c}"`).join(", ");
    const placeholders = columnsToInsert.map((_, i) => `$${i + 1}`).join(", ");

    // PK-scoped upsert. DuckDB raises a constraint error for any non-PK
    // uniqueness violation (declared via `uniqueIndexes`) instead of
    // silently replacing rows.
    const conflictClause =
      valueColumns.length > 0
        ? `
      ON CONFLICT (${this.primaryKeyColumnList('"')}) DO UPDATE
      SET
      ${(valueColumns as string[])
        .map((col) => {
          const colIdx = columnsToInsert.indexOf(String(col));
          return `"${col}" = $${colIdx + 1}`;
        })
        .join(", ")}
      `
        : "";

    const sql = `
      INSERT INTO "${this.table}" (${columnList})
      VALUES (${placeholders})
      ${conflictClause}
      RETURNING *
    `;

    return { sql, params: paramsToInsert };
  }

  /**
   * Per-instance promise-chain mutex. DuckDB runs every statement on one
   * shared connection, so all public read/write methods queue behind the
   * previous holder; `withTransaction` holds the lock for the duration of
   * the user's callback so concurrent calls from outside `fn` queue behind
   * the transaction instead of slipping into it.
   *
   * The Proxy returned by {@link createTxView} routes back to the private
   * `_*Internal` methods directly, so calls made *through* the `tx` handle
   * inside `fn` do not deadlock against the mutex held by `withTransaction`.
   */
  private mutexChain: Promise<void> = Promise.resolve();
  protected async mutex<T>(fn: () => Promise<T>): Promise<T> {
    const prev = this.mutexChain;
    let release!: () => void;
    this.mutexChain = new Promise<void>((resolve) => {
      release = resolve;
    });
    await prev;
    try {
      return await fn();
    } finally {
      release();
    }
  }

  /**
   * True while the instance is between `BEGIN` and `COMMIT`/`ROLLBACK`. Used
   * to fail fast when `fn` captures the *original* storage instead of the
   * `tx` handle and recursively calls `withTransaction` — that would
   * deadlock against its own mutex. Calls routed through `tx` hit the
   * proxy's `withTransaction` override before reaching here.
   */
  private inTransaction: boolean = false;

  /**
   * Emits a `put` event. Overridden on the {@link createTxView} proxy to
   * push into a per-transaction buffer instead, so listeners never observe
   * rows that are about to roll back.
   */
  protected emitPut(entity: Entity): void {
    safeEmit(this.events, "put", entity);
  }

  /**
   * Stores or updates a row in the database.
   * Uses UPSERT (INSERT ... ON CONFLICT DO UPDATE) for atomic operations.
   *
   * @param entity - The entity to store (may be missing auto-generated keys)
   * @returns The entity with any server-generated fields updated
   * @emits "put" event with the updated entity when successful (deferred until
   *        commit if inside a {@link withTransaction})
   */
  async put(entity: InsertType): Promise<Entity> {
    return this.mutex(() => this._putInternal(entity));
  }

  private async _putInternal(entity: InsertType): Promise<Entity> {
    const db = await this.getDb();
    const { sql, params } = this.buildPutSql(entity);
    const result = await db.query(sql, params);
    const updatedEntity = this.hydrateRow(result.rows[0]);
    this.emitPut(updatedEntity);
    return updatedEntity;
  }

  /**
   * Stores multiple rows atomically inside a single `BEGIN` / `COMMIT` on
   * the shared connection, giving all-or-nothing semantics and one commit
   * for the whole batch.
   *
   * `put` events are deferred until after `COMMIT` so listeners do not see
   * rows that are about to roll back. When this call is nested inside a
   * {@link withTransaction}, deferral extends to that outer commit.
   */
  async putBulk(entities: InsertType[]): Promise<Entity[]> {
    return this.mutex(() => this._putBulkInternal(entities));
  }

  private async _putBulkInternal(entities: InsertType[]): Promise<Entity[]> {
    if (entities.length === 0) return [];
    const db = await this.getDb();

    // Already inside an outer transaction (called via the `tx` view inside
    // `withTransaction`)? Skip our own BEGIN/COMMIT — the inner COMMIT would
    // commit the OUTER transaction prematurely.
    if (this.inTransaction) {
      const updated: Entity[] = [];
      for (const entity of entities) {
        const { sql, params } = this.buildPutSql(entity);
        const result = await db.query(sql, params);
        updated.push(this.hydrateRow(result.rows[0]));
      }
      for (const entity of updated) this.emitPut(entity);
      return updated;
    }

    const updatedEntities: Entity[] = [];
    await db.query("BEGIN");
    try {
      for (const entity of entities) {
        const { sql, params } = this.buildPutSql(entity);
        const result = await db.query(sql, params);
        updatedEntities.push(this.hydrateRow(result.rows[0]));
      }
      await db.query("COMMIT");
    } catch (err) {
      try {
        await db.query("ROLLBACK");
      } catch {
        // prefer the original error if rollback fails
      }
      // All-or-nothing: on ROLLBACK no row persisted and no `put` event
      // fired (those are deferred until after COMMIT), so `ids` is empty.
      safeEmit(this.events, "rollback", { op: "putBulk", error: err, ids: [] });
      throw err;
    }

    for (const entity of updatedEntities) this.emitPut(entity);
    return updatedEntities;
  }

  /**
   * Build a Proxy view of `this` for the `withTransaction` callback. The
   * proxy:
   *
   *   - Routes any public method `foo` whose private sibling `_fooInternal`
   *     exists to that sibling, so calls made *through* `tx` bypass the
   *     mutex held by `withTransaction` and do not deadlock. The naming
   *     convention is the only sync mechanism — adding a new public method
   *     with a matching `_fooInternal` is enough; no map to keep in step.
   *   - Reports `inTransaction === true`, which {@link _putBulkInternal}
   *     keys off to skip its own BEGIN/COMMIT.
   *   - Overrides {@link emitPut} so events emitted inside `fn` queue on a
   *     per-transaction buffer instead of firing immediately, then get
   *     flushed by `withTransaction` after `COMMIT` (or discarded on
   *     `ROLLBACK`).
   *   - Throws on nested `withTransaction` — DuckDB has no autonomous
   *     `BEGIN`. Use SAVEPOINT-style refactoring for nested boundaries.
   */
  private createTxView(deferredPutEvents: Entity[]): this {
    return new Proxy(this, {
      get(t, prop, receiver) {
        if (prop === "withTransaction") {
          return () => {
            throw new Error(
              "DuckDbTabularStorage.withTransaction does not support nesting. " +
                "Refactor to a single transaction."
            );
          };
        }
        if (prop === "inTransaction") return true;
        if (prop === "emitPut") {
          return (entity: Entity) => deferredPutEvents.push(entity);
        }
        if (typeof prop === "string") {
          const internal = (t as unknown as Record<string, unknown>)[`_${prop}Internal`];
          if (typeof internal === "function") {
            return (...args: unknown[]) =>
              (internal as (...a: unknown[]) => unknown).apply(receiver, args);
          }
        }
        const value = Reflect.get(t, prop, receiver);
        return typeof value === "function" ? value.bind(receiver) : value;
      },
    }) as this;
  }

  /**
   * Runs `fn` inside a single DuckDB transaction on the shared connection.
   *
   * Concurrent ops on the same storage instance from *outside* `fn` queue
   * on this storage's mutex until the transaction commits or rolls back.
   * The `tx` handle passed to `fn` is a Proxy that routes back to internal
   * (unlocked) implementations, so calls *through* `tx` inside `fn` do not
   * deadlock.
   *
   * `put` events emitted from inside `fn` are buffered and flushed to the
   * event emitter after `COMMIT`; if `fn` throws, the buffer is discarded
   * along with the rolled-back rows.
   */
  override async withTransaction<T>(fn: (tx: this) => Promise<T>): Promise<T> {
    if (this.inTransaction) {
      throw new Error(
        "DuckDbTabularStorage.withTransaction does not support nesting. " +
          "Refactor to a single transaction."
      );
    }
    return this.mutex(async () => {
      const db = await this.getDb();
      const deferredPutEvents: Entity[] = [];
      this.inTransaction = true;
      try {
        await db.query("BEGIN");
        let result: T;
        try {
          result = await fn(this.createTxView(deferredPutEvents));
          await db.query("COMMIT");
        } catch (err) {
          try {
            await db.query("ROLLBACK");
          } catch {
            // prefer the original error if rollback fails
          }
          throw err;
        }
        // Flush deferred events only on commit success.
        for (const entity of deferredPutEvents) safeEmit(this.events, "put", entity);
        return result;
      } finally {
        this.inTransaction = false;
      }
    });
  }

  /**
   * Retrieves a value from the database by its primary key.
   *
   * @param key - The primary key object to look up
   * @returns The stored value or undefined if not found
   * @emits "get" event with the key when successful
   */
  async get(key: PrimaryKey): Promise<Entity | undefined> {
    return this.mutex(() => this._getInternal(key));
  }

  private async _getInternal(key: PrimaryKey): Promise<Entity | undefined> {
    const db = await this.getDb();
    const whereClauses = (this.primaryKeyColumns() as string[])
      .map((col, i) => `"${col}" = $${i + 1}`)
      .join(" AND ");

    const sql = `SELECT * FROM "${this.table}" WHERE ${whereClauses}`;
    const params = this.getPrimaryKeyAsOrderedArray(key);
    const result = await db.query(sql, params);

    let val: Entity | undefined;
    if (result.rows.length > 0) {
      val = this.hydrateRow(result.rows[0]);
    } else {
      val = undefined;
    }
    safeEmit(this.events, "get", key, val);
    return val;
  }

  /**
   * Fetch multiple rows by primary key in a single statement. Single-column
   * keys emit `WHERE pk IN ($1,$2,...)`. Compound keys emit
   * `WHERE (pk1,pk2,...) IN (($1,$2,...),($3,$4,...),...)`. Values bind
   * through `jsToSqlValue` for parity with `query()` and `get()`.
   *
   * Large inputs are chunked so a single statement never carries an
   * excessive parameter list.
   */
  override async getBulk(keys: readonly PrimaryKey[]): Promise<Entity[]> {
    if (keys.length === 0) return [];
    const pkColCount = this.primaryKeyColumns().length;
    const chunkSize = Math.max(1, Math.floor(30000 / pkColCount));
    let rows: Entity[];
    if (keys.length <= chunkSize) {
      rows = await this.mutex(() => this._getBulkInternal(keys));
    } else {
      rows = [];
      for (let i = 0; i < keys.length; i += chunkSize) {
        const chunk = keys.slice(i, i + chunkSize);
        const chunkRows = await this.mutex(() => this._getBulkInternal(chunk));
        rows.push(...chunkRows);
      }
    }
    safeEmit(this.events, "getBulk", keys, rows);
    return rows;
  }

  private async _getBulkInternal(keys: readonly PrimaryKey[]): Promise<Entity[]> {
    const db = await this.getDb();
    const pkCols = this.primaryKeyColumns() as string[];

    const params: ValueOptionType[] = [];
    const tuples: string[] = [];
    let p = 1;
    for (const key of keys) {
      const ordered = this.getPrimaryKeyAsOrderedArray(key);
      params.push(...ordered);
      const slots: string[] = [];
      for (let i = 0; i < pkCols.length; i++) {
        slots.push(`$${p++}`);
      }
      tuples.push(`(${slots.join(", ")})`);
    }

    const lhs =
      pkCols.length === 1 ? `"${pkCols[0]}"` : `(${pkCols.map((c) => `"${c}"`).join(", ")})`;
    const rhs =
      pkCols.length === 1 ? params.map((_, i) => `$${i + 1}`).join(", ") : tuples.join(", ");

    const sql = `SELECT * FROM "${this.table}" WHERE ${lhs} IN (${rhs})`;
    const result = await db.query(sql, params);
    return result.rows.map((row) => this.hydrateRow(row));
  }

  /**
   * Deletes a row from the database.
   *
   * @param key - The primary key object to delete
   * @emits "delete" event with the key when successful
   */
  async delete(value: PrimaryKey | Entity): Promise<void> {
    return this.mutex(() => this._deleteInternal(value));
  }

  private async _deleteInternal(value: PrimaryKey | Entity): Promise<void> {
    const db = await this.getDb();
    const { key } = this.separateKeyValueFromCombined(value as Entity);
    const whereClauses = (this.primaryKeyColumns() as string[])
      .map((col, i) => `"${col}" = $${i + 1}`)
      .join(" AND ");

    const params = this.getPrimaryKeyAsOrderedArray(key);
    await db.query(`DELETE FROM "${this.table}" WHERE ${whereClauses}`, params);
    safeEmit(this.events, "delete", key as Partial<Entity>);
  }

  /**
   * Retrieves all entries from the database table, with optional ordering, offset, and limit.
   * @param options - Optional ordering, limit, and offset options
   * @returns Promise resolving to an array of entries or undefined if not found
   */
  async getAll(options?: QueryOptions<Entity>): Promise<Entity[] | undefined> {
    return this.mutex(() => this._getAllInternal(options));
  }

  private async _getAllInternal(options?: QueryOptions<Entity>): Promise<Entity[] | undefined> {
    this.validateGetAllOptions(options);
    const db = await this.getDb();
    let sql = `SELECT * FROM "${this.table}"`;
    const params: ValueOptionType[] = [];

    if (options?.orderBy && options.orderBy.length > 0) {
      const orderClauses = options.orderBy.map((o) => `"${String(o.column)}" ${o.direction}`);
      sql += ` ORDER BY ${orderClauses.join(", ")}`;
    }

    if (options?.limit !== undefined) {
      sql += ` LIMIT $${params.length + 1}`;
      params.push(options.limit);
    }

    if (options?.offset !== undefined) {
      sql += ` OFFSET $${params.length + 1}`;
      params.push(options.offset);
    }

    const result = await db.query(sql, params);
    if (result.rows.length === 0) return undefined;
    return result.rows.map((row) => this.hydrateRow(row));
  }

  /**
   * Deletes all rows from the database table.
   * @emits "clearall" event when successful
   */
  async deleteAll(): Promise<void> {
    return this.mutex(() => this._deleteAllInternal());
  }

  private async _deleteAllInternal(): Promise<void> {
    const db = await this.getDb();
    await db.query(`DELETE FROM "${this.table}"`);
    safeEmit(this.events, "clearall");
  }

  /**
   * Returns the total number of rows in the database.
   */
  async size(): Promise<number> {
    return this.mutex(() => this._sizeInternal());
  }

  private async _sizeInternal(): Promise<number> {
    const db = await this.getDb();
    const result = await db.query<{ count: number }>(
      `SELECT COUNT(*) AS count FROM "${this.table}"`
    );
    return Number(result.rows[0]?.count ?? 0);
  }

  /**
   * Counts rows matching the specified search criteria.
   */
  override async count(criteria?: SearchCriteria<Entity>): Promise<number> {
    return this.mutex(() => this._countInternal(criteria));
  }

  private async _countInternal(criteria?: SearchCriteria<Entity>): Promise<number> {
    if (!criteria || Object.keys(criteria).length === 0) {
      return await this._sizeInternal();
    }

    this.validateQueryParams(criteria);
    const db = await this.getDb();
    const { whereClause, params } = this.buildDeleteSearchWhere(criteria);
    const result = await db.query<{ count: number }>(
      `SELECT COUNT(*) AS count FROM "${this.table}" WHERE ${whereClause}`,
      params
    );
    return Number(result.rows[0]?.count ?? 0);
  }

  /**
   * Fetches a page of records from the repository.
   * @param offset - Number of records to skip
   * @param limit - Maximum number of records to return
   * @returns Array of entities or undefined if no records found
   */
  async getOffsetPage(offset: number, limit: number): Promise<Entity[] | undefined> {
    return this.mutex(() => this._getOffsetPageInternal(offset, limit));
  }

  private async _getOffsetPageInternal(
    offset: number,
    limit: number
  ): Promise<Entity[] | undefined> {
    const db = await this.getDb();
    const orderByClause = this.primaryKeyColumns()
      .map((col) => `"${String(col)}"`)
      .join(", ");
    const result = await db.query(
      `SELECT * FROM "${this.table}" ORDER BY ${orderByClause} LIMIT $1 OFFSET $2`,
      [limit, offset]
    );

    if (result.rows.length === 0) {
      return undefined;
    }
    return result.rows.map((row) => this.hydrateRow(row));
  }

  /**
   * Builds WHERE clause conditions from delete search criteria. DuckDB uses
   * Postgres identifier quoting and `$N` placeholders, so the shared
   * Postgres dialect applies.
   */
  protected buildDeleteSearchWhere(criteria: DeleteSearchCriteria<Entity>): {
    whereClause: string;
    params: ValueOptionType[];
  } {
    const built = buildSearchWhere<Entity>(
      PostgresDialect,
      criteria,
      this.schema.properties as Record<string, unknown>,
      (column, value) => this.jsToSqlValue(column, value)
    );
    return { whereClause: built.whereClause, params: built.params };
  }

  /**
   * Like {@link buildDeleteSearchWhere} but also reports the next free
   * placeholder index so cursor pagination can chain its own predicates
   * after the criteria block.
   */
  private buildSearchWhereWithIndex(
    criteria: SearchCriteria<Entity>,
    startIndex: number
  ): { whereClause: string; params: ValueOptionType[]; nextIndex: number } {
    const built = buildSearchWhere<Entity>(
      PostgresDialect,
      criteria,
      this.schema.properties as Record<string, unknown>,
      (column, value) => this.jsToSqlValue(column, value),
      startIndex
    );
    return {
      whereClause: built.whereClause,
      params: built.params,
      nextIndex: startIndex + built.params.length,
    };
  }

  /**
   * Cursor-paginated read with keyset predicates pushed into SQL.
   *
   * Goes through the per-instance mutex so a `getPage` call issued while a
   * `withTransaction` is in flight queues behind the transaction instead of
   * running between its `BEGIN` and `COMMIT` on the shared connection.
   */
  override async getPage(request: PageRequest<Entity> = {}): Promise<Page<Entity>> {
    return this.mutex(() => this._getPageInternal(request));
  }

  private async _getPageInternal(request: PageRequest<Entity>): Promise<Page<Entity>> {
    return this.runSqlPage(undefined, request, this.duckDbDialect());
  }

  override async queryPage(
    criteria: SearchCriteria<Entity>,
    request: PageRequest<Entity> = {}
  ): Promise<Page<Entity>> {
    return this.mutex(() => this._queryPageInternal(criteria, request));
  }

  private async _queryPageInternal(
    criteria: SearchCriteria<Entity>,
    request: PageRequest<Entity>
  ): Promise<Page<Entity>> {
    this.validateQueryParams(criteria, undefined);
    return this.runSqlPage(criteria, request, this.duckDbDialect());
  }

  private duckDbDialect() {
    return {
      quote: '"',
      placeholder: (index: number) => `$${index}`,
      buildSearchWhere: (criteria: SearchCriteria<Entity>, startIndex: number) =>
        this.buildSearchWhereWithIndex(criteria, startIndex),
      executeSelect: async (sql: string, params: ValueOptionType[]): Promise<Entity[]> => {
        const db = await this.getDb();
        const result = await db.query(sql, params);
        return result.rows.map((row) => this.hydrateRow(row));
      },
    };
  }

  /**
   * Deletes all entries matching the specified search criteria.
   * Supports multiple columns with optional comparison operators.
   *
   * @param criteria - Object with column names as keys and values or SearchConditions
   */
  async deleteSearch(criteria: DeleteSearchCriteria<Entity>): Promise<void> {
    return this.mutex(() => this._deleteSearchInternal(criteria));
  }

  private async _deleteSearchInternal(criteria: DeleteSearchCriteria<Entity>): Promise<void> {
    const criteriaKeys = Object.keys(criteria) as Array<keyof Entity>;
    if (criteriaKeys.length === 0) {
      return;
    }

    const db = await this.getDb();
    const { whereClause, params } = this.buildDeleteSearchWhere(criteria);
    await db.query(`DELETE FROM "${this.table}" WHERE ${whereClause}`, params);
    safeEmit(this.events, "delete", this.deleteIdentity(criteria));
  }

  /**
   * Atomically updates the first row matching the search criteria and returns
   * the updated row. Constrained to a single row via a rowid sub-select so a
   * non-unique `match` updates exactly one row — matching the single-row
   * contract and the non-SQL backends.
   *
   * @param match - Object with column names as keys and values or SearchConditions
   * @param patch - Partial entity with the columns to update
   * @returns The updated entity, or undefined if no row matched
   */
  async updateWhere(
    match: SearchCriteria<Entity>,
    patch: Partial<Entity>
  ): Promise<Entity | undefined> {
    this.assertPatchKeepsPrimaryKey(patch);
    return this.mutex(() => this._updateWhereInternal(match, patch));
  }

  private async _updateWhereInternal(
    match: SearchCriteria<Entity>,
    patch: Partial<Entity>
  ): Promise<Entity | undefined> {
    const patchKeys = Object.keys(patch) as Array<keyof Entity>;
    if (patchKeys.length === 0) return undefined;

    const db = await this.getDb();
    const setClause = patchKeys.map((col, i) => `"${String(col)}" = $${i + 1}`).join(", ");
    const setParams = patchKeys.map((col) => this.jsToSqlValue(String(col), patch[col] as never));

    const { whereClause, params: whereParams } = this.buildSearchWhereWithIndex(
      match,
      patchKeys.length + 1
    );
    const subWhere = whereClause.length > 0 ? `WHERE ${whereClause}` : "";

    const result = await db.query(
      `UPDATE "${this.table}" SET ${setClause} ` +
        `WHERE rowid IN (SELECT rowid FROM "${this.table}" ${subWhere} LIMIT 1) RETURNING *`,
      [...setParams, ...whereParams]
    );
    if (result.rows.length === 0) return undefined;
    const updated = this.hydrateRow(result.rows[0]);
    this.emitPut(updated);
    return updated;
  }

  /**
   * Queries entries matching the specified search criteria with optional ordering, limit, and offset.
   *
   * @param criteria - Object with column names as keys and values or SearchConditions
   * @param options - Optional ordering, limit, and offset options
   * @returns Array of matching entities or undefined if no matches found
   */
  async query(
    criteria: SearchCriteria<Entity>,
    options?: QueryOptions<Entity>
  ): Promise<Entity[] | undefined> {
    return this.mutex(() => this._queryInternal(criteria, options));
  }

  private async _queryInternal(
    criteria: SearchCriteria<Entity>,
    options?: QueryOptions<Entity>
  ): Promise<Entity[] | undefined> {
    this.validateQueryParams(criteria, options);
    const db = await this.getDb();

    let sql = `SELECT * FROM "${this.table}"`;
    const { whereClause, params } = this.buildDeleteSearchWhere(criteria);
    sql += ` WHERE ${whereClause}`;

    if (options?.orderBy && options.orderBy.length > 0) {
      const orderClauses = options.orderBy.map((o) => `"${String(o.column)}" ${o.direction}`);
      sql += ` ORDER BY ${orderClauses.join(", ")}`;
    }

    if (options?.limit !== undefined) {
      sql += ` LIMIT $${params.length + 1}`;
      params.push(options.limit);
    }

    if (options?.offset !== undefined) {
      sql += ` OFFSET $${params.length + 1}`;
      params.push(options.offset);
    }

    const result = await db.query(sql, params);

    if (result.rows.length > 0) {
      const rows = result.rows.map((row) => this.hydrateRow(row));
      safeEmit(this.events, "query", criteria as Partial<Entity>, rows);
      return rows;
    }
    safeEmit(this.events, "query", criteria as Partial<Entity>, undefined);
    return undefined;
  }

  /**
   * Queries entries matching the specified search criteria, returning only the selected columns.
   * Requires a covering index that satisfies the criteria, orderBy, and select columns.
   *
   * @param criteria - Object with column names as keys and values or SearchConditions
   * @param options - Required select columns plus optional orderBy, limit, and offset
   * @returns Array of partial entities containing only the selected columns
   * @throws {CoveringIndexMissingError} when no registered index covers the query
   */
  override async queryIndex<K extends keyof Entity & string>(
    criteria: SearchCriteria<Entity>,
    options: CoveringIndexQueryOptions<Entity, K>
  ): Promise<Pick<Entity, K>[]> {
    return this.mutex(() => this._queryIndexInternal(criteria, options));
  }

  private async _queryIndexInternal<K extends keyof Entity & string>(
    criteria: SearchCriteria<Entity>,
    options: CoveringIndexQueryOptions<Entity, K>
  ): Promise<Pick<Entity, K>[]> {
    this.validateSelect(options);
    this.validateQueryParams(criteria, options);

    const registered = this.indexes.map((cols, i) => {
      const cs = Array.isArray(cols) ? (cols as string[]) : [cols as string];
      return { name: `idx_${i}`, keyPath: cs };
    });

    pickCoveringIndex({
      table: this.table,
      indexes: registered,
      criteriaColumns: Object.keys(criteria),
      orderByColumns: (options.orderBy ?? []).map((o) => ({
        column: String(o.column),
        direction: o.direction,
      })),
      selectColumns: options.select.map(String),
      primaryKeyColumns: this.primaryKeyNames.map(String),
    });

    const cols = options.select.map((c) => `"${String(c)}"`).join(", ");
    let sql = `SELECT ${cols} FROM "${this.table}"`;
    const { whereClause, params } = this.buildDeleteSearchWhere(criteria);
    sql += ` WHERE ${whereClause}`;

    if (options.orderBy && options.orderBy.length > 0) {
      sql +=
        ` ORDER BY ` +
        options.orderBy.map((o) => `"${String(o.column)}" ${o.direction}`).join(", ");
    }
    if (options.limit !== undefined) {
      sql += ` LIMIT $${params.length + 1}`;
      params.push(options.limit);
    }
    if (options.offset !== undefined) {
      sql += ` OFFSET $${params.length + 1}`;
      params.push(options.offset);
    }

    const db = await this.getDb();
    const result = await db.query(sql, params);
    for (const row of result.rows) {
      const record = row as Record<string, unknown>;
      for (const k of Object.keys(record)) {
        record[k] = this.sqlToJsValue(k, record[k] as ValueOptionType);
      }
    }
    return result.rows as Pick<Entity, K>[];
  }

  /**
   * Subscribes to changes in the repository.
   * NOT IMPLEMENTED for DuckDB storage.
   *
   * @throws Error always - subscribeToChanges is not supported for DuckDB storage
   */
  public override subscribeToChanges(
    callback: (change: TabularChangePayload<Entity>) => void,
    options?: TabularSubscribeOptions
  ): () => void {
    throw new Error("subscribeToChanges is not supported for DuckDbTabularStorage");
  }

  /**
   * Destroys the repository and frees up resources.
   */
  public override destroy(): void {
    super.destroy();
  }
}

class DuckDbTabularMigrationApplierImpl extends SqlTabularMigrationApplier {
  constructor(private readonly host: DuckDbTabularStorage<any, any, any, any, any, any>) {
    super();
  }
  private db(): Promise<DuckDbDatabase> {
    return (this.host as unknown as { getDb: () => Promise<DuckDbDatabase> }).getDb();
  }
  protected override dialectName(): "sqlite" | "postgres" {
    // DuckDB's DDL is Postgres-shaped (double-quoted identifiers,
    // TIMESTAMP WITH TIME ZONE, NOW()), so migration SQL is emitted with
    // the Postgres dialect.
    return "postgres";
  }
  protected override table(): string {
    return (this.host as unknown as { table: string }).table;
  }
  protected override storage(): AnyTabularStorage {
    return this.host as unknown as AnyTabularStorage;
  }
  protected override mapTypeToSQL(typeDef: JsonSchema): string {
    return (this.host as unknown as { mapTypeToSQL: (t: JsonSchema) => string }).mapTypeToSQL(
      typeDef
    );
  }
  protected override isNullableSchema(typeDef: JsonSchema): boolean {
    return (this.host as unknown as { isNullable: (t: JsonSchema) => boolean }).isNullable(typeDef);
  }
  protected override async executeSql(sql: string): Promise<void> {
    await (await this.db()).query(sql);
  }
  protected override async executeSqlTx(sql: string, _tx: AnyTabularStorage): Promise<void> {
    // DuckDB uses a single connection; the host's `withTransaction` already
    // issued BEGIN, so any statement on the same handle runs inside it.
    await (await this.db()).query(sql);
  }
  protected override async recordAppliedTx(
    component: string,
    version: number,
    description: string | undefined,
    _tx: AnyTabularStorage
  ): Promise<void> {
    await (
      await this.db()
    ).query(
      `INSERT INTO ${MIGRATIONS_TABLE}(component, version, description) VALUES ($1, $2, $3)`,
      [component, version, description ?? null]
    );
  }
  protected override async recordApplied(
    component: string,
    version: number,
    description: string | undefined
  ): Promise<void> {
    await (
      await this.db()
    ).query(
      `INSERT INTO ${MIGRATIONS_TABLE}(component, version, description) VALUES ($1, $2, $3)`,
      [component, version, description ?? null]
    );
  }
  protected override async queryAppliedVersions(component: string): Promise<Set<number>> {
    const r = await (
      await this.db()
    ).query<{ version: number }>(`SELECT version FROM ${MIGRATIONS_TABLE} WHERE component = $1`, [
      component,
    ]);
    return new Set(r.rows.map((row) => Number(row.version)));
  }
  protected override async probeTableExists(): Promise<boolean> {
    const r = await (
      await this.db()
    ).query(`SELECT 1 FROM information_schema.tables WHERE table_name = $1 LIMIT 1`, [
      (this.host as unknown as { table: string }).table,
    ]);
    return r.rows.length > 0;
  }
}
