/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { getLogger, getPortCodec } from "@workglow/util";
import type { DataPortSchema } from "@workglow/util/schema";
import { type CachePolicy, isPolicyCached, isPolicyPrivate } from "../cache/CachePolicy";
import type { CacheRef } from "../cache/CacheRef";
import { isCacheRef, makeCacheRef } from "../cache/CacheRef";
import type { CacheRegistry } from "../cache/CacheRegistry";
import { RunPrivateCacheRepo } from "../cache/RunPrivateCacheRepo";
import { streamRefViaBacking } from "../cache/resolveRef";
import { getStreamPortCodec } from "../cache/streamCodec";
import type { TaskOutputRepository } from "../storage/TaskOutputRepository";
import type { ITask } from "./ITask";
import type { BinaryRefSink, StreamSink } from "./StreamProcessor";
import type { StreamEvent } from "./StreamTypes";
import {
  assertBinaryFormat,
  getStreamingPorts,
  materializeBinary,
  REFUSAL_OUTPUT_KEY,
  USAGE_OUTPUT_KEY,
} from "./StreamTypes";
import { Task } from "./Task";
import type { TaskRunContext } from "./TaskRunContext";
import type { TaskInput, TaskOutput } from "./TaskTypes";
import { TaskStatus } from "./TaskTypes";

interface SchemaProperties {
  properties?: Record<string, { format?: string }>;
}

/**
 * Graph-computed consumer hints driving cache-hit behavior for binary
 * {@link CacheRef} output ports: hydrate bytes into the enriched finish event
 * for materializing consumers, replay chunked `binary-delta` events for
 * stream-capable consumers, or (neither flag set) leave refs untouched.
 */
export interface CacheReplayContext {
  readonly hasMaterializingConsumers: boolean;
  readonly hasStreamingConsumers: boolean;
}

/**
 * @internal
 * Cache key normalization, lookup, save, and cache-hit stream-event emission
 * for streamable tasks. The three previously module-private helpers
 * (serializeOutputPorts, deserializeOutputPorts, normalizeInputsForCacheKey)
 * are private statics here.
 *
 * outputCache is passed as a method argument (not stored as a class field)
 * because the facade resolves it per-run in handleStart and may differ
 * between runs.
 */
export class CacheCoordinator<Input extends TaskInput, Output extends TaskOutput> {
  constructor(private readonly task: ITask<Input, Output, any>) {}

  /**
   * Serializes format-annotated input properties (via their port codecs) so the
   * resulting object is a stable, serialization-equivalent representation
   * suitable for use as a cache key. Properties without a format annotation are
   * passed through unchanged. No-op when no cache is configured.
   *
   * IMPORTANT: this relies on each `PortCodec.serialize` producing a
   * DETERMINISTIC wire form for equal inputs. The PortCodec contract does not
   * itself guarantee determinism — a codec that embeds a timestamp, a fresh id,
   * or non-canonical ordering will fingerprint differently every run, so the
   * deterministic cache silently never hits for that port. Codecs used on
   * cacheable input ports MUST serialize deterministically.
   *
   * The reserved sentinel field `__cv` (cache version) is injected into the
   * normalized object before fingerprinting so that bumping a task's `static
   * version` automatically invalidates its cached outputs. Tasks must never
   * declare an input port named `__cv`.
   */
  async buildKey(inputs: Input, outputCache: TaskOutputRepository | undefined): Promise<Input> {
    if (!outputCache) return inputs;
    const inputSchema = (this.task.constructor as typeof Task).inputSchema();
    const normalized = await CacheCoordinator.normalizeInputsForCacheKey(
      inputs as Record<string, unknown>,
      inputSchema as unknown as SchemaProperties
    );
    (normalized as Record<string, unknown>).__cv = this.task.getCacheVersion();
    return normalized as Input;
  }

  /**
   * Looks up a cached output. On a hit for a streaming task, also emits the
   * synthetic stream_start / stream_chunk(finish) / stream_end events so
   * downstream consumers see the same event shape as a fresh run.
   *
   * Returns the deserialized output if found, undefined otherwise.
   */
  /**
   * Cache identity for the `taskType` axis of {@link TaskOutputRepository}.
   *
   * Deterministic entries key by task class. Private (run-resume) entries
   * normally key by task instance id so two nodes of the same type in one
   * graph do not collide — but only when the id is stable across restarts.
   * When the id is the autogenerated v4 UUID default (no caller pin), a
   * restart would mint a fresh id and orphan every prior row, so we fall
   * back to the task type to preserve a best-effort intra-type crash-resume.
   * The fallback is announced once per process via {@link RunPrivateCacheRepo}.
   */
  private cacheIdentityKey(policy: CachePolicy, outputCache: TaskOutputRepository): string {
    if (!isPolicyPrivate(policy)) return this.task.type;
    if (this.task.hasDeterministicId()) return String(this.task.id);
    if (outputCache instanceof RunPrivateCacheRepo) outputCache.noteFallbackKey();
    return this.task.type;
  }

  async lookup(
    keyInputs: Input,
    outputCache: TaskOutputRepository | undefined,
    policy: CachePolicy,
    isStreamable: boolean,
    ctx: TaskRunContext,
    replay?: CacheReplayContext
  ): Promise<Output | undefined> {
    if (!outputCache || !this.task.cacheable) return undefined;

    // A corrupt stored value or a codec/schema drift can make getOutput or
    // deserializeOutputPorts throw. Caching is a transparent optimization: a bad
    // entry should cost at most a recompute, never convert a runnable task into a
    // hard failure. Degrade any decode failure to a cache miss (the deterministic
    // path is safe to recompute by definition).
    let cached: unknown;
    let outputs: Output;
    try {
      cached = await outputCache.getOutput(this.cacheIdentityKey(policy, outputCache), keyInputs);
      if (cached === undefined) return undefined;

      const outputSchema = (this.task.constructor as typeof Task).outputSchema();
      outputs = (await CacheCoordinator.deserializeOutputPorts(
        cached as Record<string, unknown>,
        outputSchema as unknown as SchemaProperties
      )) as Output;
    } catch (err) {
      getLogger().warn(
        `CacheCoordinator: failed to read/decode cached output for ${this.task.type}; treating as cache miss`,
        { error: err }
      );
      return undefined;
    }

    ctx.telemetrySpan?.addEvent("workglow.task.cache_hit");

    if (isStreamable) {
      const replayed = await this.replayStreamRefs(
        outputs,
        outputCache,
        outputSchema as DataPortSchema,
        replay
      );
      // A dangling ref converts the hit into a miss: the caller re-executes
      // and the rewrite self-heals the cache entry.
      if (replayed === "miss") return undefined;
      if (replayed === "none") {
        this.task.runOutputData = outputs;
        this.task.emit("stream_start");
        this.task.emit("stream_chunk", { type: "finish", data: outputs } as StreamEvent);
        this.task.emit("stream_end", outputs);
      }
    } else {
      this.task.runOutputData = outputs;
    }

    return outputs;
  }

  /**
   * Cache-hit stream-out for {@link CacheRef} output ports of any streamable
   * mode (`append` / `object` / `binary`).
   *
   * Mirrors the fresh-run event contract: the emitted finish event carries the
   * materialized value (string / folded object / `Blob`/`ArrayBuffer`) for
   * consumers that need it, while the returned output keeps the small ref at the
   * port slot. When a stream-capable consumer exists, the cached bytes are
   * re-emitted as the mode's delta events first (binary chunked directly;
   * append/object decoded through the per-mode codec).
   *
   * Returns:
   *  - `"none"`    — nothing to replay (no refs at streamable ports, or no
   *                  consumer hint set); caller emits the default synthetic
   *                  finish.
   *  - `"handled"` — events were emitted here; caller must not re-emit.
   *  - `"miss"`    — a ref no longer resolves; caller treats the lookup as a
   *                  cache miss.
   */
  private async replayStreamRefs(
    outputs: Output,
    outputCache: TaskOutputRepository,
    outputSchema: DataPortSchema,
    replay: CacheReplayContext | undefined
  ): Promise<"none" | "handled" | "miss"> {
    const needBytes = replay?.hasMaterializingConsumers === true;
    const replayDeltas = replay?.hasStreamingConsumers === true;
    if (!needBytes && !replayDeltas) return "none";
    if (outputs === null || typeof outputs !== "object") return "none";

    const source = outputs as Record<string, unknown>;
    const refPorts = getStreamingPorts(outputSchema).filter(
      (p) =>
        (p.mode === "append" || p.mode === "object" || p.mode === "binary") &&
        isCacheRef(source[p.port])
    );
    if (refPorts.length === 0) return "none";

    // Resolve every ref before emitting any event so a dangling ref becomes a
    // clean miss with zero observable side effects.
    const streams = new Map<string, AsyncIterable<Uint8Array>>();
    for (const { port } of refPorts) {
      const stream = await streamRefViaBacking(source[port] as CacheRef, outputCache);
      if (stream === undefined) return "miss";
      streams.set(port, stream);
    }

    this.task.runOutputData = outputs;
    this.task.emit("stream_start");
    // Flipping to STREAMING before the first data event is what makes the
    // graph runner attach edge streams (same contract as StreamProcessor).
    this.task.status = TaskStatus.STREAMING;
    this.task.emit("status", this.task.status);

    const finishData: Record<string, unknown> = { ...source };
    for (const { port, mode } of refPorts) {
      const stream = streams.get(port)!;
      if (mode === "binary") {
        // Stream chunk-by-chunk so large binary stays memory-bounded when no
        // materializing consumer needs the whole artifact.
        const chunks: Uint8Array[] | undefined = needBytes ? [] : undefined;
        for await (const chunk of stream) {
          chunks?.push(chunk);
          if (replayDeltas) {
            this.task.emit("stream_chunk", {
              type: "binary-delta",
              port,
              binaryDelta: chunk,
            } as StreamEvent);
          }
        }
        if (chunks !== undefined) {
          finishData[port] = materializeBinary(chunks, assertBinaryFormat(outputSchema, port));
        }
      } else {
        // append / object: collect the encoded bytes once, then decode (deltas)
        // and/or materialize (value) from the same buffer via the mode codec.
        const codec = getStreamPortCodec(mode);
        const buf: Uint8Array[] = [];
        for await (const chunk of stream) buf.push(chunk);
        const bytesOf = async function* (): AsyncIterable<Uint8Array> {
          for (const c of buf) yield c;
        };
        if (replayDeltas) {
          for await (const ev of codec.decode(bytesOf(), port)) {
            this.task.emit("stream_chunk", ev as StreamEvent);
          }
        }
        if (needBytes) {
          finishData[port] = await codec.materialize(bytesOf(), port);
        }
      }
    }
    this.task.emit("stream_chunk", { type: "finish", data: finishData } as StreamEvent);
    this.task.emit("stream_end", finishData);
    return "handled";
  }

  /**
   * Serializes and saves output. No-op when no cache is configured or task is
   * not cacheable.
   */
  async save(
    keyInputs: Input,
    output: Output,
    outputCache: TaskOutputRepository | undefined,
    policy: CachePolicy
  ): Promise<void> {
    if (!outputCache || !this.task.cacheable || output === undefined) return;
    // Never memoize a refused output: a transient refusal (e.g. a safety-classifier
    // flake) would otherwise replay as "the answer" until a cache-version bump.
    if (
      output !== null &&
      typeof output === "object" &&
      (output as Record<string, unknown>)[REFUSAL_OUTPUT_KEY]
    ) {
      return;
    }
    // Token counts are a fact about ONE execution, not about the value. Serving
    // this entry later costs zero tokens, so replaying the original counts would
    // invent spend that never happened. Unlike a refusal (which blocks the save
    // entirely), the value itself is still worth memoizing — strip the field.
    const outputSchema = (this.task.constructor as typeof Task).outputSchema();
    const wireOutputs = await CacheCoordinator.serializeOutputPorts(
      CacheCoordinator.withoutUsage(output as Record<string, unknown>),
      outputSchema as unknown as SchemaProperties
    );
    await outputCache.saveOutput(
      this.cacheIdentityKey(policy, outputCache),
      keyInputs,
      wireOutputs as Output
    );
  }

  /**
   * Streams output bytes straight to a stream-capable cache sink. Returns the
   * {@link CacheRef} produced by the backing, or `undefined` when no cache is
   * configured, the task is not cacheable, or the repository does not
   * implement `saveOutputStream`.
   */
  async saveStream(
    keyInputs: Input,
    chunks: AsyncIterable<Uint8Array>,
    metadata: Record<string, unknown>,
    outputCache: TaskOutputRepository | undefined
  ): Promise<CacheRef | undefined> {
    if (!outputCache || !this.task.cacheable) return undefined;
    if (!outputCache.supportsStreaming()) return undefined;
    return outputCache.saveOutputStream!(this.task.type, keyInputs, chunks, metadata);
  }

  // ========================================================================
  // Policy-aware routing methods
  // ========================================================================

  /**
   * Resolve the repository slot to use given a registry and policy. Returns
   * `undefined` if the registry is missing, the policy is `kind: "none"`, or
   * the relevant slot is unregistered. All callers treat `undefined` as "skip
   * caching" — no errors, no warnings.
   */
  private repoFor(
    registry: CacheRegistry | undefined,
    policy: CachePolicy
  ): TaskOutputRepository | undefined {
    if (!registry || !isPolicyCached(policy)) return undefined;
    return isPolicyPrivate(policy) ? registry.private : registry.deterministic;
  }

  public async buildKeyForPolicy(
    inputs: Input,
    registry: CacheRegistry | undefined,
    policy: CachePolicy
  ): Promise<Input> {
    return this.buildKey(inputs, this.repoFor(registry, policy));
  }

  public async lookupByPolicy(
    keyInputs: Input,
    registry: CacheRegistry | undefined,
    policy: CachePolicy,
    isStreamable: boolean,
    ctx: TaskRunContext,
    replay?: CacheReplayContext
  ): Promise<Output | undefined> {
    return this.lookup(
      keyInputs,
      this.repoFor(registry, policy),
      policy,
      isStreamable,
      ctx,
      replay
    );
  }

  public async saveByPolicy(
    keyInputs: Input,
    output: Output,
    registry: CacheRegistry | undefined,
    policy: CachePolicy
  ): Promise<void> {
    return this.save(keyInputs, output, this.repoFor(registry, policy), policy);
  }

  /**
   * Best-effort cleanup of orphan blobs after a row commit fails. When
   * `saveByPolicy` rejects after the stream sink already wrote bytes and
   * minted a {@link CacheRef}, the blob has no row pointing at it and is
   * effectively leaked until the next janitor sweep. Walk the output's binary
   * ports, locate any {@link CacheRef} values, and ask the backing to delete
   * them. Per-ref deletion failures are swallowed and logged — they should
   * not mask the original save error the caller is about to re-throw.
   */
  public async cleanupOrphanBlobsForBinaryPorts(
    output: Output,
    registry: CacheRegistry | undefined,
    policy: CachePolicy,
    outputSchema: DataPortSchema
  ): Promise<void> {
    if (output === null || typeof output !== "object") return;
    const cache = this.repoFor(registry, policy);
    if (!cache || typeof cache.deleteOutputByRef !== "function") return;
    const source = output as Record<string, unknown>;
    const binaryPorts = getStreamingPorts(outputSchema)
      .filter((p) => p.mode === "binary")
      .map((p) => p.port);
    await Promise.all(
      binaryPorts.map(async (port) => {
        const value = source[port];
        if (!isCacheRef(value)) return;
        try {
          await cache.deleteOutputByRef!(value);
        } catch {
          // Best-effort: the periodic janitor sweep will reclaim what we miss.
        }
      })
    );
  }

  /**
   * Build the per-port `BinaryRefSink` map the runner passes to
   * `StreamProcessor.run()` so binary streams pipe straight to the cache and
   * `Output` carries a {@link CacheRef} at the port slot.
   *
   * Returns `undefined` when any of the conditions for the ref path are not
   * met: no cache is configured by policy, the cache does not implement
   * `saveOutputStream`, the task is not cacheable, or the output schema has
   * no `x-stream: "binary"` port. v1 supports single-binary-port tasks only;
   * tasks with multiple binary ports fall back to the accumulation path.
   *
   * The threshold ({@link IRunConfig.referenceThresholdBytes}) controls
   * whether the ref *survives* in the final Output, not whether the sink
   * runs: when total bytes streamed end up below the threshold, the runner
   * rehydrates the ref to an inline `Blob`/`ArrayBuffer` via
   * {@link hydrateRefsBelowThreshold}. Setting threshold to `0` forces
   * every binary port to a ref regardless of size.
   */
  public getBinaryRefSinksByPolicy(
    keyInputs: Input,
    registry: CacheRegistry | undefined,
    policy: CachePolicy,
    outputSchema: DataPortSchema
  ): ReadonlyMap<string, BinaryRefSink> | undefined {
    if (!this.task.cacheable) return undefined;
    const cache = this.repoFor(registry, policy);
    if (!cache || !cache.supportsStreaming()) return undefined;
    // The sink keys bytes by (taskType, inputs) with no port axis, so two
    // binary ports would overwrite each other in the backing. Enforce the
    // single-binary-port restriction here as well as in the accumulation
    // decision (StreamPump.canStreamBinaryToCache) — multi-port tasks fall
    // back to pure accumulation.
    const binaryPorts = getStreamingPorts(outputSchema).filter((p) => p.mode === "binary");
    if (binaryPorts.length !== 1) return undefined;
    const port = binaryPorts[0].port;
    const taskType = this.task.type;
    // Re-wrap the backing's CacheRef so legacy `saveOutputStream` implementations
    // that pre-date the `kind` brand still produce a discriminator-bearing ref.
    // Branded refs pass through unchanged (preserving size/mime hints).
    const sink: BinaryRefSink = async (chunks) => {
      const raw = await cache.saveOutputStream!(taskType, keyInputs, chunks, {});
      return isCacheRef(raw) ? raw : makeCacheRef(raw);
    };
    return new Map([[port, sink]]);
  }

  /**
   * Per-port {@link StreamSink} map for the no-accumulation path: every
   * streamable output port (`append` / `object` / `binary`) gets its own sink
   * keyed by `(taskType, inputs, port)` via {@link TaskOutputRepository.saveOutputStreamPort},
   * so a multi-port task stores each port's bytes independently — no overwrite,
   * no single-binary-port restriction. The {@link StreamProcessor} encodes each
   * port's deltas with the mode codec before handing the bytes to the sink.
   *
   * Returns `undefined` when no cache is configured by policy, the cache does
   * not implement `saveOutputStreamPort` (legacy backings keep the single
   * binary path via {@link getBinaryRefSinksByPolicy}), the task is not
   * cacheable, or the schema has no streamable port. `replace`-mode ports are
   * excluded — a snapshot-driven port has no single-port delta byte stream and
   * stays on the accumulation path.
   */
  public getRefSinksByPolicy(
    keyInputs: Input,
    registry: CacheRegistry | undefined,
    policy: CachePolicy,
    outputSchema: DataPortSchema
  ): ReadonlyMap<string, StreamSink> | undefined {
    if (!this.task.cacheable) return undefined;
    const cache = this.repoFor(registry, policy);
    if (!cache || !cache.supportsStreamingPorts()) return undefined;
    const ports = getStreamingPorts(outputSchema).filter(
      (p) => p.mode === "append" || p.mode === "object" || p.mode === "binary"
    );
    if (ports.length === 0) return undefined;
    const taskType = this.task.type;
    const sinks = new Map<string, StreamSink>();
    for (const { port, mode } of ports) {
      sinks.set(port, {
        mode,
        write: async (chunks) => {
          const raw = await cache.saveOutputStreamPort!(
            taskType,
            keyInputs,
            port,
            mode,
            chunks,
            {}
          );
          return isCacheRef(raw) ? raw : makeCacheRef(raw);
        },
      });
    }
    return sinks;
  }

  /**
   * Post-process the streaming task's `Output`: for every **binary streaming
   * port** (per the schema) whose value is a {@link CacheRef} with
   * `size < referenceThresholdBytes`, rehydrate the bytes via `getOutputByRef`
   * and inline them as `Blob`/`ArrayBuffer` (per the port's `format`
   * annotation). Refs at or above the threshold are left in place.
   * `referenceThresholdBytes === 0` forces every ref to survive regardless of
   * size.
   *
   * Restricted to schema-declared binary streaming ports so that legitimate
   * non-binary fields that happen to carry a `{$ref: string}` shape (e.g. a
   * JSON-Schema reference embedded in metadata) are not mistakenly resolved
   * against the cache.
   *
   * Refs without a known `size` are kept as-is (the writer didn't measure;
   * conservatively assume "large enough to keep as ref"). Backings that want
   * threshold-based rehydration MUST populate `size` on the CacheRef they
   * return from `saveOutputStream`.
   */
  public async hydrateRefsBelowThreshold(
    output: Output,
    registry: CacheRegistry | undefined,
    policy: CachePolicy,
    outputSchema: DataPortSchema,
    referenceThresholdBytes: number
  ): Promise<Output> {
    if (referenceThresholdBytes === 0) return output;
    if (output === null || typeof output !== "object") return output;
    const cache = this.repoFor(registry, policy);
    if (!cache || typeof cache.getOutputByRef !== "function") return output;

    // Every streamable mode can carry a ref now (append/object via the per-port
    // codec, binary via getOutputByRef). Rehydrate a below-threshold ref back to
    // its value: a string for append, the folded array/object for object, a
    // Blob/ArrayBuffer for binary.
    const ports = getStreamingPorts(outputSchema).filter(
      (p) => p.mode === "append" || p.mode === "object" || p.mode === "binary"
    );
    if (ports.length === 0) return output;

    const source = output as Record<string, unknown>;
    let out: Record<string, unknown> | undefined;
    const rehydrations = await Promise.all(
      ports.map(async ({ port, mode }) => {
        const value = source[port];
        if (!isCacheRef(value)) return undefined;
        const size = value.size;
        if (size === undefined || size >= referenceThresholdBytes) return undefined;
        if (mode === "binary") {
          const blob = await cache.getOutputByRef!(value);
          if (blob === undefined) return undefined;
          const format = assertBinaryFormat(outputSchema, port);
          const inlined = format === "binary" ? await blob.arrayBuffer() : blob;
          return { port, inlined };
        }
        // append / object: replay the encoded bytes through the mode codec.
        const stream = await streamRefViaBacking(value, cache);
        if (stream === undefined) return undefined;
        const inlined = await getStreamPortCodec(mode).materialize(stream, port);
        return { port, inlined };
      })
    );
    for (const r of rehydrations) {
      if (!r) continue;
      out ??= { ...source };
      out[r.port] = r.inlined;
    }
    return (out ?? source) as Output;
  }

  // ========================================================================
  // Private static helpers (lifted from current module-private functions in
  // TaskRunner.ts)
  // ========================================================================

  private static withoutUsage(output: Record<string, unknown>): Record<string, unknown> {
    if (output === null || typeof output !== "object" || !(USAGE_OUTPUT_KEY in output)) {
      return output;
    }
    const stripped = { ...output };
    delete stripped[USAGE_OUTPUT_KEY];
    return stripped;
  }

  private static async serializeOutputPorts(
    output: Record<string, unknown>,
    schema: SchemaProperties
  ): Promise<Record<string, unknown>> {
    if (!schema?.properties) return output;
    const out: Record<string, unknown> = { ...output };
    for (const [key, prop] of Object.entries(schema.properties)) {
      const codec = prop.format ? getPortCodec(prop.format) : undefined;
      if (codec && out[key] !== undefined) {
        out[key] = await codec.serialize(out[key]);
      }
    }
    return out;
  }

  private static async deserializeOutputPorts(
    output: Record<string, unknown>,
    schema: SchemaProperties
  ): Promise<Record<string, unknown>> {
    if (!schema?.properties) return output;
    const out: Record<string, unknown> = { ...output };
    for (const [key, prop] of Object.entries(schema.properties)) {
      const codec = prop.format ? getPortCodec(prop.format) : undefined;
      if (codec && out[key] !== undefined) {
        out[key] = await codec.deserialize(out[key]);
      }
    }
    return out;
  }

  private static async normalizeInputsForCacheKey(
    inputs: Record<string, unknown>,
    schema: SchemaProperties
  ): Promise<Record<string, unknown>> {
    if (!schema?.properties) return inputs;
    const out: Record<string, unknown> = { ...inputs };
    for (const [key, prop] of Object.entries(schema.properties)) {
      const codec = prop.format ? getPortCodec(prop.format) : undefined;
      if (codec && out[key] !== undefined) {
        out[key] = await codec.serialize(out[key]);
      }
    }
    return out;
  }
}
