/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { getPortCodec } from "@workglow/util";
import type { DataPortSchema } from "@workglow/util/schema";
import { type CachePolicy, isPolicyCached, isPolicyPrivate } from "../cache/CachePolicy";
import type { CacheRef } from "../cache/CacheRef";
import { isCacheRef } from "../cache/CacheRef";
import type { CacheRegistry } from "../cache/CacheRegistry";
import { RunPrivateCacheRepo } from "../cache/RunPrivateCacheRepo";
import type { TaskOutputRepository } from "../storage/TaskOutputRepository";
import type { BinaryRefSink } from "./StreamProcessor";
import { getBinaryPortFormat, getBinaryPortId, getStreamingPorts } from "./StreamTypes";
import type { ITask } from "./ITask";
import type { StreamEvent } from "./StreamTypes";
import { Task } from "./Task";
import type { TaskRunContext } from "./TaskRunContext";
import type { TaskInput, TaskOutput } from "./TaskTypes";

interface SchemaProperties {
  properties?: Record<string, { format?: string }>;
}

/**
 * @internal
 * Cache key normalization, lookup, save, and cache-hit stream-event emission
 * for streamable tasks. The three previously module-private helpers
 * (serializeOutputPorts, deserializeOutputPorts, normalizeInputsForCacheKey)
 * are private statics here.
 *
 * outputCache is passed as a method argument (not stored as a class field)
 * because the facade resolves it per-run in handleStart and may differ
 * between runs.
 */
export class CacheCoordinator<Input extends TaskInput, Output extends TaskOutput> {
  constructor(private readonly task: ITask<Input, Output, any>) {}

  /**
   * Serializes format-annotated input properties (via their port codecs) so the
   * resulting object is a stable, serialization-equivalent representation
   * suitable for use as a cache key. Properties without a format annotation are
   * passed through unchanged. No-op when no cache is configured.
   *
   * The reserved sentinel field `__cv` (cache version) is injected into the
   * normalized object before fingerprinting so that bumping a task's `static
   * version` automatically invalidates its cached outputs. Tasks must never
   * declare an input port named `__cv`.
   */
  async buildKey(inputs: Input, outputCache: TaskOutputRepository | undefined): Promise<Input> {
    if (!outputCache) return inputs;
    const inputSchema = (this.task.constructor as typeof Task).inputSchema();
    const normalized = await CacheCoordinator.normalizeInputsForCacheKey(
      inputs as Record<string, unknown>,
      inputSchema as unknown as SchemaProperties
    );
    (normalized as Record<string, unknown>).__cv = this.task.getCacheVersion();
    return normalized as Input;
  }

  /**
   * Looks up a cached output. On a hit for a streaming task, also emits the
   * synthetic stream_start / stream_chunk(finish) / stream_end events so
   * downstream consumers see the same event shape as a fresh run.
   *
   * Returns the deserialized output if found, undefined otherwise.
   */
  /**
   * Cache identity for the `taskType` axis of {@link TaskOutputRepository}.
   *
   * Deterministic entries key by task class. Private (run-resume) entries
   * normally key by task instance id so two nodes of the same type in one
   * graph do not collide — but only when the id is stable across restarts.
   * When the id is the autogenerated v4 UUID default (no caller pin), a
   * restart would mint a fresh id and orphan every prior row, so we fall
   * back to the task type to preserve a best-effort intra-type crash-resume.
   * The fallback is announced once per process via {@link RunPrivateCacheRepo}.
   */
  private cacheIdentityKey(policy: CachePolicy, outputCache: TaskOutputRepository): string {
    if (!isPolicyPrivate(policy)) return this.task.type;
    if (this.task.hasDeterministicId()) return String(this.task.id);
    if (outputCache instanceof RunPrivateCacheRepo) outputCache.noteFallbackKey();
    return this.task.type;
  }

  async lookup(
    keyInputs: Input,
    outputCache: TaskOutputRepository | undefined,
    policy: CachePolicy,
    isStreamable: boolean,
    ctx: TaskRunContext
  ): Promise<Output | undefined> {
    if (!outputCache || !this.task.cacheable) return undefined;

    const cached = await outputCache.getOutput(
      this.cacheIdentityKey(policy, outputCache),
      keyInputs
    );
    if (cached === undefined) return undefined;

    const outputSchema = (this.task.constructor as typeof Task).outputSchema();
    const outputs = (await CacheCoordinator.deserializeOutputPorts(
      cached as Record<string, unknown>,
      outputSchema as unknown as SchemaProperties
    )) as Output;

    ctx.telemetrySpan?.addEvent("workglow.task.cache_hit");

    if (isStreamable) {
      this.task.runOutputData = outputs;
      this.task.emit("stream_start");
      this.task.emit("stream_chunk", { type: "finish", data: outputs } as StreamEvent);
      this.task.emit("stream_end", outputs);
    } else {
      this.task.runOutputData = outputs;
    }

    return outputs;
  }

  /**
   * Serializes and saves output. No-op when no cache is configured or task is
   * not cacheable.
   */
  async save(
    keyInputs: Input,
    output: Output,
    outputCache: TaskOutputRepository | undefined,
    policy: CachePolicy
  ): Promise<void> {
    if (!outputCache || !this.task.cacheable || output === undefined) return;
    const outputSchema = (this.task.constructor as typeof Task).outputSchema();
    const wireOutputs = await CacheCoordinator.serializeOutputPorts(
      output as Record<string, unknown>,
      outputSchema as unknown as SchemaProperties
    );
    await outputCache.saveOutput(
      this.cacheIdentityKey(policy, outputCache),
      keyInputs,
      wireOutputs as Output
    );
  }

  /**
   * Streams output bytes straight to a stream-capable cache sink. Returns the
   * {@link CacheRef} produced by the backing, or `undefined` when no cache is
   * configured, the task is not cacheable, or the repository does not
   * implement `saveOutputStream`.
   */
  async saveStream(
    keyInputs: Input,
    chunks: AsyncIterable<Uint8Array>,
    metadata: Record<string, unknown>,
    outputCache: TaskOutputRepository | undefined
  ): Promise<CacheRef | undefined> {
    if (!outputCache || !this.task.cacheable) return undefined;
    if (!outputCache.supportsStreaming()) return undefined;
    return outputCache.saveOutputStream!(this.task.type, keyInputs, chunks, metadata);
  }

  // ========================================================================
  // Policy-aware routing methods
  // ========================================================================

  /**
   * Resolve the repository slot to use given a registry and policy. Returns
   * `undefined` if the registry is missing, the policy is `kind: "none"`, or
   * the relevant slot is unregistered. All callers treat `undefined` as "skip
   * caching" — no errors, no warnings.
   */
  private repoFor(
    registry: CacheRegistry | undefined,
    policy: CachePolicy
  ): TaskOutputRepository | undefined {
    if (!registry || !isPolicyCached(policy)) return undefined;
    return isPolicyPrivate(policy) ? registry.private : registry.deterministic;
  }

  public async buildKeyForPolicy(
    inputs: Input,
    registry: CacheRegistry | undefined,
    policy: CachePolicy
  ): Promise<Input> {
    return this.buildKey(inputs, this.repoFor(registry, policy));
  }

  public async lookupByPolicy(
    keyInputs: Input,
    registry: CacheRegistry | undefined,
    policy: CachePolicy,
    isStreamable: boolean,
    ctx: TaskRunContext
  ): Promise<Output | undefined> {
    return this.lookup(keyInputs, this.repoFor(registry, policy), policy, isStreamable, ctx);
  }

  public async saveByPolicy(
    keyInputs: Input,
    output: Output,
    registry: CacheRegistry | undefined,
    policy: CachePolicy
  ): Promise<void> {
    return this.save(keyInputs, output, this.repoFor(registry, policy), policy);
  }

  /**
   * Build the per-port `BinaryRefSink` map the runner passes to
   * `StreamProcessor.run()` so binary streams pipe straight to the cache and
   * `Output` carries a {@link CacheRef} at the port slot.
   *
   * Returns `undefined` when any of the conditions for the ref path are not
   * met: no cache is configured by policy, the cache does not implement
   * `saveOutputStream`, the task is not cacheable, or the output schema has
   * no `x-stream: "binary"` port. v1 supports single-binary-port tasks only;
   * tasks with multiple binary ports fall back to the accumulation path.
   *
   * The threshold ({@link IRunConfig.referenceThresholdBytes}) controls
   * whether the ref *survives* in the final Output, not whether the sink
   * runs: when total bytes streamed end up below the threshold, the runner
   * rehydrates the ref to an inline `Blob`/`ArrayBuffer` via
   * {@link hydrateRefsBelowThreshold}. Setting threshold to `0` forces
   * every binary port to a ref regardless of size.
   */
  public getBinaryRefSinksByPolicy(
    keyInputs: Input,
    registry: CacheRegistry | undefined,
    policy: CachePolicy,
    outputSchema: DataPortSchema
  ): ReadonlyMap<string, BinaryRefSink> | undefined {
    if (!this.task.cacheable) return undefined;
    const cache = this.repoFor(registry, policy);
    if (!cache || !cache.supportsStreaming()) return undefined;
    const port = getBinaryPortId(outputSchema);
    if (port === undefined) return undefined;
    const taskType = this.task.type;
    const sink: BinaryRefSink = (chunks) =>
      cache.saveOutputStream!(taskType, keyInputs, chunks, {});
    return new Map([[port, sink]]);
  }

  /**
   * Post-process the streaming task's `Output`: for every **binary streaming
   * port** (per the schema) whose value is a {@link CacheRef} with
   * `size < referenceThresholdBytes`, rehydrate the bytes via `getOutputByRef`
   * and inline them as `Blob`/`ArrayBuffer` (per the port's `format`
   * annotation). Refs at or above the threshold are left in place.
   * `referenceThresholdBytes === 0` forces every ref to survive regardless of
   * size.
   *
   * Restricted to schema-declared binary streaming ports so that legitimate
   * non-binary fields that happen to carry a `{$ref: string}` shape (e.g. a
   * JSON-Schema reference embedded in metadata) are not mistakenly resolved
   * against the cache.
   *
   * Refs without a known `size` are kept as-is (the writer didn't measure;
   * conservatively assume "large enough to keep as ref"). Backings that want
   * threshold-based rehydration MUST populate `size` on the CacheRef they
   * return from `saveOutputStream`.
   */
  public async hydrateRefsBelowThreshold(
    output: Output,
    registry: CacheRegistry | undefined,
    policy: CachePolicy,
    outputSchema: DataPortSchema,
    referenceThresholdBytes: number
  ): Promise<Output> {
    if (referenceThresholdBytes === 0) return output;
    if (output === null || typeof output !== "object") return output;
    const cache = this.repoFor(registry, policy);
    if (!cache || typeof cache.getOutputByRef !== "function") return output;

    const binaryPorts = getStreamingPorts(outputSchema)
      .filter((p) => p.mode === "binary")
      .map((p) => p.port);
    if (binaryPorts.length === 0) return output;

    const source = output as Record<string, unknown>;
    let out: Record<string, unknown> | undefined;
    const rehydrations = await Promise.all(
      binaryPorts.map(async (port) => {
        const value = source[port];
        if (!isCacheRef(value)) return undefined;
        const size = value.size;
        if (size === undefined || size >= referenceThresholdBytes) return undefined;
        const blob = await cache.getOutputByRef!(value);
        if (blob === undefined) return undefined;
        const format = getBinaryPortFormat(outputSchema, port);
        const inlined = format === "binary" ? await blob.arrayBuffer() : blob;
        return { port, inlined };
      })
    );
    for (const r of rehydrations) {
      if (!r) continue;
      out ??= { ...source };
      out[r.port] = r.inlined;
    }
    return (out ?? source) as Output;
  }

  // ========================================================================
  // Private static helpers (lifted from current module-private functions in
  // TaskRunner.ts)
  // ========================================================================

  private static async serializeOutputPorts(
    output: Record<string, unknown>,
    schema: SchemaProperties
  ): Promise<Record<string, unknown>> {
    if (!schema?.properties) return output;
    const out: Record<string, unknown> = { ...output };
    for (const [key, prop] of Object.entries(schema.properties)) {
      const codec = prop.format ? getPortCodec(prop.format) : undefined;
      if (codec && out[key] !== undefined) {
        out[key] = await codec.serialize(out[key]);
      }
    }
    return out;
  }

  private static async deserializeOutputPorts(
    output: Record<string, unknown>,
    schema: SchemaProperties
  ): Promise<Record<string, unknown>> {
    if (!schema?.properties) return output;
    const out: Record<string, unknown> = { ...output };
    for (const [key, prop] of Object.entries(schema.properties)) {
      const codec = prop.format ? getPortCodec(prop.format) : undefined;
      if (codec && out[key] !== undefined) {
        out[key] = await codec.deserialize(out[key]);
      }
    }
    return out;
  }

  private static async normalizeInputsForCacheKey(
    inputs: Record<string, unknown>,
    schema: SchemaProperties
  ): Promise<Record<string, unknown>> {
    if (!schema?.properties) return inputs;
    const out: Record<string, unknown> = { ...inputs };
    for (const [key, prop] of Object.entries(schema.properties)) {
      const codec = prop.format ? getPortCodec(prop.format) : undefined;
      if (codec && out[key] !== undefined) {
        out[key] = await codec.serialize(out[key]);
      }
    }
    return out;
  }
}
