/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CachePolicy } from "../cache/CachePolicy";
import { DEFAULT_CACHE_POLICY } from "../cache/CachePolicy";
import type { IRunConfig } from "./ITask";
import type { Task } from "./Task";
import type { TaskConfig } from "./TaskTypes";

/**
 * Matches a canonical lowercase RFC 4122 v4 UUID. Used to detect the
 * autogenerated default id produced when no `config.id` was supplied so the
 * cache layer can fall back to a deterministic per-type key.
 */
export const UUID_V4_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

/**
 * Whether `id` is a caller-pinned (deterministic) task id. The default Task
 * constructor mints a fresh v4 UUID when no id is supplied, so a
 * v4-UUID-shaped id is treated as autogenerated — not deterministic.
 */
export function isDeterministicId(id: unknown): boolean {
  if (typeof id !== "string" || id.length === 0) return false;
  return !UUID_V4_REGEX.test(id);
}

/**
 * Walks the prototype chain from `ctor` (leaf first) and joins the `version`
 * static of every class that declares its own, producing the dot-separated
 * cache-version component. Falls back to "1" when nothing in the chain owns a
 * numeric `version`.
 */
export function collectCacheVersion(ctor: unknown): string {
  const versions: number[] = [];
  let current: unknown = ctor;
  while (current && current !== Function.prototype) {
    if (
      Object.prototype.hasOwnProperty.call(current, "version") &&
      typeof (current as { version?: unknown }).version === "number"
    ) {
      versions.push((current as { version: number }).version);
    }
    current = Object.getPrototypeOf(current as object);
  }
  if (versions.length === 0) versions.push(1);
  return versions.join(".");
}

/**
 * Resolves the effective cache policy for a task class given its per-instance
 * config and runConfig.
 *
 * Resolution order:
 *   1. Per-instance `runConfig.cacheable === false` or `config.cacheable === false`
 *      → `{ kind: "none" }` (callsite opt-out wins).
 *   2. Class-static `cacheable === false` (declared on the subclass) →
 *      `{ kind: "none" }`. The coarse on/off flag remains supported alongside
 *      the canonical `cachePolicy`; setting it on the class is equivalent
 *      to declaring `static cachePolicy: CachePolicy = { kind: "none" }`.
 *   3. Class-static `cachePolicy` if declared.
 *   4. {@link DEFAULT_CACHE_POLICY}.
 */
export function resolveCachePolicy(
  ctor: typeof Task,
  config: TaskConfig | undefined,
  runConfig: Partial<IRunConfig> | undefined
): CachePolicy {
  if (runConfig?.cacheable === false || config?.cacheable === false) return { kind: "none" };
  if (
    Object.prototype.hasOwnProperty.call(ctor, "cacheable") &&
    (ctor as { cacheable?: unknown }).cacheable === false &&
    !Object.prototype.hasOwnProperty.call(ctor, "cachePolicy")
  ) {
    return { kind: "none" };
  }
  return ctor.cachePolicy ?? DEFAULT_CACHE_POLICY;
}
