/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import type { InsertEntity, IVectorStorage, VectorSearchOptions } from "@workglow/storage";
import {
  AutoGeneratedKeys,
  getMetadataProperty,
  getVectorProperty,
  StorageValidationError,
} from "@workglow/storage";
import type {
  DataPortSchemaObject,
  FromSchema,
  TypedArray,
  TypedArrayConstructor,
  TypedArraySchemaOptions,
} from "@workglow/util/schema";
import { SupabaseTabularStorage } from "./SupabaseTabularStorage";

/**
 * Regex for validating metadata filter keys to prevent SQL/filter injection.
 * Only allows alphanumeric characters and underscores, starting with a letter
 * or underscore. Mirrors {@link PostgresVectorStorage}.
 */
const SAFE_IDENTIFIER_RE = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

/** Scope a vector store is bound to before reads/writes are permitted. */
export interface VectorScope {
  readonly tenant_id: string;
  readonly project_id: string;
  readonly kb_id: string;
}

/**
 * Supabase-backed vector repository. Extends {@link SupabaseTabularStorage}
 * for row storage and delegates similarity search to a server-side
 * `match_<table>` RPC (pgvector). Every read and write is bound to a tenant /
 * project / knowledge-base scope set via {@link withScope}; scope columns are
 * stamped onto writes from the resolved scope rather than from client input.
 *
 * @template Schema - The schema definition for the entity
 * @template PrimaryKeyNames - Array of property names that form the primary key
 * @template Metadata - The metadata type used for filters
 */
export class SupabaseVectorStorage<
  Schema extends DataPortSchemaObject,
  PrimaryKeyNames extends ReadonlyArray<keyof Schema["properties"]>,
  Metadata extends Record<string, unknown> = Record<string, unknown>,
  Entity = FromSchema<Schema, TypedArraySchemaOptions>,
  InsertType extends InsertEntity<Entity, AutoGeneratedKeys<Schema>> = InsertEntity<
    Entity,
    AutoGeneratedKeys<Schema>
  >,
>
  extends SupabaseTabularStorage<Schema, PrimaryKeyNames, Entity>
  implements IVectorStorage<Metadata, Schema, Entity, PrimaryKeyNames>
{
  public readonly tableName: string;
  private readonly vectorDimensions: number;
  private readonly vectorCtor: TypedArrayConstructor;
  private readonly vectorPropertyName: keyof Entity;
  private readonly metadataPropertyName: keyof Entity | undefined;
  // Captured constructor args so withScope can build a real, independent
  // instance rather than a prototype clone that would alias base mutable
  // state (realtime channel, event listeners).
  private readonly initSchema: Schema;
  private readonly initPrimaryKeyNames: PrimaryKeyNames;
  private readonly initIndexes: readonly (
    | keyof NoInfer<Entity>
    | readonly (keyof NoInfer<Entity>)[]
  )[];
  private scope: VectorScope | undefined;

  /**
   * @param client - Supabase client instance
   * @param table - The name of the table (and the suffix of its `match_<table>` RPC)
   * @param schema - The schema definition for the entity
   * @param primaryKeyNames - Array of property names that form the primary key
   * @param indexes - Columns or column arrays to make searchable
   * @param dimensions - The number of dimensions of the vector
   * @param vectorCtor - TypedArray constructor used when hydrating vectors (default {@link Float32Array})
   */
  constructor(
    client: SupabaseClient,
    table: string,
    schema: Schema,
    primaryKeyNames: PrimaryKeyNames,
    indexes: readonly (keyof NoInfer<Entity> | readonly (keyof NoInfer<Entity>)[])[] = [],
    dimensions: number,
    vectorCtor: TypedArrayConstructor = Float32Array
  ) {
    super(client, table, schema, primaryKeyNames, indexes);

    this.tableName = table;
    this.vectorDimensions = dimensions;
    this.vectorCtor = vectorCtor;
    this.initSchema = schema;
    this.initPrimaryKeyNames = primaryKeyNames;
    this.initIndexes = indexes;

    const vectorProp = getVectorProperty(schema);
    if (!vectorProp) {
      throw new Error("Schema must have a property with type array and format TypedArray");
    }
    this.vectorPropertyName = vectorProp as keyof Entity;
    this.metadataPropertyName = getMetadataProperty(schema) as keyof Entity | undefined;
  }

  public getVectorDimensions(): number {
    return this.vectorDimensions;
  }

  /**
   * Returns an independent store instance bound to the given scope. A fresh
   * instance (not a prototype clone) is constructed so scoped views do not
   * alias the base storage's mutable state (realtime channel, event listeners)
   * while still sharing the same underlying client connection.
   */
  public withScope(scope: VectorScope): this {
    const Ctor = this.constructor as new (
      client: SupabaseClient,
      table: string,
      schema: Schema,
      primaryKeyNames: PrimaryKeyNames,
      indexes: readonly (keyof NoInfer<Entity> | readonly (keyof NoInfer<Entity>)[])[],
      dimensions: number,
      vectorCtor: TypedArrayConstructor
    ) => this;
    const clone = new Ctor(
      this.client,
      this.tableName,
      this.initSchema,
      this.initPrimaryKeyNames,
      this.initIndexes,
      this.vectorDimensions,
      this.vectorCtor
    );
    clone.scope = scope;
    return clone;
  }

  private getScopeFilter(): VectorScope {
    if (!this.scope) {
      throw new StorageValidationError("SupabaseVectorStorage used without scope");
    }
    return this.scope;
  }

  /**
   * Serialize the vector TypedArray to pgvector text (`[a,b,c]`) and stamp the
   * resolved scope columns. The base tabular upsert forwards values to the
   * driver unchanged, and PGlite/pgvector accept the text form for a `vector`
   * column — a raw TypedArray would be rejected. Scope columns always come from
   * the resolved scope, never from client-supplied input.
   */
  private prepareForWrite(entity: InsertType): InsertType {
    const scope = this.getScopeFilter();
    const record = { ...(entity as Record<string, unknown>) };

    record[this.vectorPropertyName as string] = this.toPgVectorText(
      record[this.vectorPropertyName as string]
    );
    if (this.metadataPropertyName !== undefined) {
      const metaCol = this.metadataPropertyName as string;
      if (record[metaCol] === undefined || record[metaCol] === null) {
        record[metaCol] = {};
      }
    }
    record.tenant_id = scope.tenant_id;
    record.project_id = scope.project_id;
    record.kb_id = scope.kb_id;

    return record as InsertType;
  }

  private toPgVectorText(value: unknown): string {
    const arr = value as ArrayLike<number>;
    return `[${Array.from(arr).join(",")}]`;
  }

  public override async put(entity: InsertType): Promise<Entity> {
    const saved = await super.put(this.prepareForWrite(entity));
    return this.restampVector(saved, entity);
  }

  public override async putBulk(entities: InsertType[]): Promise<Entity[]> {
    if (entities.length === 0) return [];
    const saved = await super.putBulk(entities.map((e) => this.prepareForWrite(e)));
    return saved.map((row, i) => this.restampVector(row, entities[i]));
  }

  /**
   * Returns the hydrated DB row (preserving any server-generated columns) with
   * the vector column restored to the caller's TypedArray — the persisted form
   * is pgvector text, but callers expect the original typed vector back.
   */
  private restampVector(saved: Entity, input: InsertType): Entity {
    const out = { ...(saved as Record<string, unknown>) };
    out[this.vectorPropertyName as string] = (input as Record<string, unknown>)[
      this.vectorPropertyName as string
    ];
    return out as Entity;
  }

  public async similaritySearch(
    query: TypedArray,
    options: VectorSearchOptions<Metadata> = {}
  ): Promise<Array<Entity & { score: number }>> {
    const { topK = 10, filter = {} as Partial<Metadata>, scoreThreshold = 0 } = options;
    const scope = this.getScopeFilter();

    for (const key of Object.keys(filter)) {
      if (!SAFE_IDENTIFIER_RE.test(key)) {
        throw new StorageValidationError(
          `Invalid metadata filter key: "${key}". Keys must match /^[a-zA-Z_][a-zA-Z0-9_]*$/.`
        );
      }
    }

    // The param-object key order matches the SQL function's parameter order;
    // the PGlite test mock routes RPC params positionally, so this ordering is
    // load-bearing and must not be reordered.
    const { data, error } = await this.client.rpc(`match_${this.tableName}`, {
      query_embedding: `[${Array.from(query).join(",")}]`,
      match_count: topK,
      score_threshold: scoreThreshold,
      p_tenant_id: scope.tenant_id,
      p_project_id: scope.project_id,
      p_kb_id: scope.kb_id,
      p_filter: filter,
    });

    if (error) throw error;

    const rows = (data ?? []) as Array<Record<string, unknown>>;
    const vectorCol = this.vectorPropertyName as string;

    return rows.map((row) => {
      const hydrated = { ...row } as Record<string, unknown>;
      hydrated[vectorCol] = new this.vectorCtor(this.parseVector(row[vectorCol]));
      hydrated.score = Number(row.score);
      return hydrated as Entity & { score: number };
    });
  }

  /** Parse a pgvector value into a plain number array; accepts text or array forms. */
  private parseVector(value: unknown): number[] {
    if (Array.isArray(value)) return value as number[];
    if (typeof value === "string") {
      const trimmed = value.trim();
      if (trimmed === "" || trimmed === "[]") return [];
      return trimmed
        .replace(/^\[/, "")
        .replace(/\]$/, "")
        .split(",")
        .map((s) => Number(s));
    }
    return [];
  }
}
