/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Source mode without touching `package.json`.
 *
 * `exports` stays in its committed `./dist/*` form forever; development mode is
 * expressed by writing re-export stubs into the (gitignored) `dist` folder, so
 * `dist/node.js` forwards to `src/node.ts`. Switching modes therefore produces
 * no git diff at all.
 *
 * Stubs are identified by {@link SOURCE_STUB_SENTINEL} in their first bytes, so
 * removal never deletes a real build artifact and no marker file is needed.
 *
 * Type stubs (`export * from "../src/browser"`) break under TypeScript project
 * references: the consumer redirects `dist/*.d.ts` to `src`, so the stub's
 * relative import resolves as a self-import and every export appears missing.
 * Example apps therefore omit `references` and resolve packages via
 * `node_modules` → stub → source.
 */

import { existsSync } from "node:fs";
import { chmod, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";

export const SOURCE_STUB_SENTINEL = "@workglow-source-stub";

const STUB_NOTE = `// ${SOURCE_STUB_SENTINEL}: generated by \`use-source\`. Run \`use-dist\` to restore the real build.`;

/** Extensions worth reading when hunting for the sentinel. */
const TEXT_ENTRY_EXTENSIONS = [".js", ".mjs", ".cjs", ".ts"] as const;

export interface PackageManifest {
  readonly name: string;
  readonly exports?: unknown;
  readonly bin?: unknown;
}

export type StubKind = "runtime" | "types" | "bin";

export interface StubSpec {
  /** Package-relative dist path, e.g. `./dist/node.js`. */
  readonly target: string;
  /** Package-relative source path, e.g. `./src/node.ts`. */
  readonly source: string;
  readonly kind: StubKind;
}

export async function readPackageManifest(packageDir: string): Promise<PackageManifest> {
  const raw = await readFile(join(packageDir, "package.json"), "utf-8");
  return JSON.parse(raw) as PackageManifest;
}

/** Every distinct `./dist/...` string anywhere in the `exports` tree. */
export function collectDistTargets(exportsField: unknown): string[] {
  const found = new Set<string>();
  const walk = (node: unknown): void => {
    if (typeof node === "string") {
      if (node.startsWith("./dist/")) found.add(node);
      return;
    }
    if (node !== null && typeof node === "object") {
      for (const value of Object.values(node as Record<string, unknown>)) walk(value);
    }
  };
  walk(exportsField);
  return [...found].sort();
}

/**
 * `./dist/media-node.d.ts` and `./dist/media-node.js` both come from
 * `./src/media-node.ts` — the inverse of what the build emits.
 */
export function sourceCounterpart(distTarget: string): string {
  const body = distTarget.slice("./dist/".length);
  const stem = body.endsWith(".d.ts")
    ? body.slice(0, -".d.ts".length)
    : body.endsWith(".js")
      ? body.slice(0, -".js".length)
      : undefined;
  if (stem === undefined) {
    throw new Error(`Cannot map ${distTarget} to a source file (expected a .js or .d.ts target)`);
  }
  return `./src/${stem}.ts`;
}

function specFor(distTarget: string, kind: StubKind): StubSpec {
  return { target: distTarget, source: sourceCounterpart(distTarget), kind };
}

function collectBinTargets(bin: unknown): string[] {
  if (typeof bin === "string") return bin.startsWith("./dist/") ? [bin] : [];
  if (bin !== null && typeof bin === "object") {
    return Object.values(bin as Record<string, unknown>).filter(
      (value): value is string => typeof value === "string" && value.startsWith("./dist/")
    );
  }
  return [];
}

/** Stub specs for a manifest: every `exports` target, plus `bin` when present. */
export function stubSpecsFor(manifest: PackageManifest): StubSpec[] {
  const specs = collectDistTargets(manifest.exports).map((target) =>
    specFor(target, target.endsWith(".d.ts") ? "types" : "runtime")
  );

  for (const binTarget of collectBinTargets(manifest.bin)) {
    if (specs.some((spec) => spec.target === binTarget)) continue;
    specs.push(specFor(binTarget, "bin"));
  }
  return specs;
}

function importSpecifier(stubFile: string, sourceFile: string, keepExtension: boolean): string {
  const rel = relative(dirname(stubFile), sourceFile).split(sep).join("/");
  const withPrefix = rel.startsWith(".") ? rel : `./${rel}`;
  // A `.d.ts` stub must point at an extensionless specifier so tsc resolves the
  // `.ts` source; a runtime stub keeps the extension so bun/vite load it directly.
  return keepExtension ? withPrefix : withPrefix.replace(/\.ts$/, "");
}

function stubBody(kind: StubKind, specifier: string): string {
  if (kind === "bin") {
    return `#!/usr/bin/env bun\n${STUB_NOTE}\nimport "${specifier}";\n`;
  }
  return `${STUB_NOTE}\nexport * from "${specifier}";\n`;
}

/**
 * Write every stub for a package. Throws if a dist target has no source
 * counterpart rather than emitting a stub that resolves to nothing.
 */
export async function writeSourceStubs(
  packageDir: string,
  specs: readonly StubSpec[]
): Promise<string[]> {
  const written: string[] = [];
  for (const spec of specs) {
    const sourceFile = join(packageDir, spec.source);
    if (!existsSync(sourceFile)) {
      throw new Error(`${spec.target} has no source counterpart at ${spec.source}`);
    }
    const stubFile = join(packageDir, spec.target);
    await mkdir(dirname(stubFile), { recursive: true });
    await writeFile(
      stubFile,
      stubBody(spec.kind, importSpecifier(stubFile, sourceFile, spec.kind !== "types"))
    );
    if (spec.kind === "bin") await chmod(stubFile, 0o755);
    written.push(spec.target);
  }
  return written;
}

export async function isSourceStub(file: string): Promise<boolean> {
  if (!TEXT_ENTRY_EXTENSIONS.some((ext) => file.endsWith(ext))) return false;
  try {
    return (await Bun.file(file).slice(0, 512).text()).includes(SOURCE_STUB_SENTINEL);
  } catch {
    return false;
  }
}

/**
 * Every stub under `<packageDir>/dist`. Walks the whole tree rather than the
 * current `exports` so a stub left behind by a renamed entry is still found.
 */
export async function findSourceStubs(packageDir: string): Promise<string[]> {
  const stubs: string[] = [];
  const walk = async (dir: string): Promise<void> => {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (entry.isFile() && (await isSourceStub(full))) {
        stubs.push(full);
      }
    }
  };
  await walk(join(packageDir, "dist"));
  return stubs;
}

export async function removeSourceStubs(packageDir: string): Promise<string[]> {
  const stubs = await findSourceStubs(packageDir);
  for (const stub of stubs) await rm(stub);
  return stubs;
}
