/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import type {
  DataPortSchemaObject,
  FromSchema,
  JsonSchema,
  TypedArraySchemaOptions,
} from "@workglow/util/schema";
import type { ISqlDialect } from "../sql/Dialect";
import type { SqlJoinSide } from "../sql/JoinSql";
import {
  buildJoinSelect,
  JOIN_LEFT_ALIAS,
  JOIN_RIGHT_ALIAS,
  joinColumnAlias,
} from "../sql/JoinSql";
import type { ClientProvidedKeysOption } from "./BaseTabularStorage";
import { BaseTabularStorage } from "./BaseTabularStorage";
import { getNonNullSchema, isNullableSchema } from "./columnConstraints";
import { assertCursorMatches, decodeCursor } from "./Cursor";
import type {
  AutoGeneratedKeys,
  InsertEntity,
  ITabularStorage,
  JoinedRow,
  JoinSpec,
  JoinType,
  OrderBy,
  Page,
  PageRequest,
  SearchCriteria,
  SimplifyPrimaryKey,
  ValueOptionType,
} from "./ITabularStorage";
import { resolveJoinDelegate } from "./joinDelegate";
import { pkFingerprint } from "./pkFingerprint";

/**
 * Per-dialect hooks for the shared multi-row bulk-insert engine. Mirrors the
 * dialect object used by {@link BaseSqlTabularStorage.runSqlPage}: it captures
 * only the parts of an `INSERT … VALUES … RETURNING *` statement that differ
 * between SQLite and the Postgres-shaped engines.
 */
export interface BulkPutDialect {
  /** Identifier quote character. */
  readonly quote: string;
  /** Renders the placeholder for a 1-based parameter index. */
  placeholder(index: number): string;
  /**
   * Opening clause including the table and parenthesized column list, e.g.
   * `` INSERT OR REPLACE INTO `t` (`a`, `b`) `` or `INSERT INTO "t" ("a", "b")`.
   */
  insertInto(quotedColumnList: string): string;
  /**
   * Upsert tail for the given ordered insert columns, or `""` when the dialect
   * expresses conflict handling in {@link insertInto} (SQLite `OR REPLACE`) or
   * when no column can be updated.
   */
  conflictClause(insertColumns: readonly string[]): string;
  /**
   * When true, a UUID auto-generated key that a row omits is minted here on the
   * client (SQLite, DuckDB), so the row's key is known before insert. When
   * false (Postgres) the server fills it via `DEFAULT`, leaving the row unkeyed.
   */
  readonly mintUuidClientSide: boolean;
}

/** A single VALUES cell: either a bound parameter or the literal `DEFAULT`. */
type BulkCell = { readonly value: ValueOptionType } | { readonly isDefault: true };

/**
 * What a backend supplies so {@link BaseSqlTabularStorage.join} can run a
 * join as one statement: the dialect that renders it and a raw executor that
 * returns un-hydrated rows keyed by output column name.
 */
export interface SqlJoinDialect {
  readonly dialect: ISqlDialect;
  readonly executeRaw: (
    sql: string,
    params: ValueOptionType[]
  ) => Promise<Record<string, unknown>[]>;
}

/** The right-hand storage and SQL dialect a pushed-down join runs against. */
interface SqlJoinPlan {
  readonly right: BaseSqlTabularStorage<any, any, any, any, any, any>;
  readonly dialect: ISqlDialect;
}

/**
 * Base class for SQL-based tabular repositories, shared by SQLite and PostgreSQL
 * implementations.
 */
export abstract class BaseSqlTabularStorage<
  Schema extends DataPortSchemaObject,
  PrimaryKeyNames extends ReadonlyArray<keyof Schema["properties"]>,
  // computed types
  Entity = FromSchema<Schema, TypedArraySchemaOptions>,
  PrimaryKey = SimplifyPrimaryKey<Entity, PrimaryKeyNames>,
  Value = Omit<Entity, PrimaryKeyNames[number] & keyof Entity>,
  InsertType extends InsertEntity<Entity, AutoGeneratedKeys<Schema>> = InsertEntity<
    Entity,
    AutoGeneratedKeys<Schema>
  >,
> extends BaseTabularStorage<Schema, PrimaryKeyNames, Entity, PrimaryKey, Value, InsertType> {
  /** Caches for computed column definition strings, keyed by quote delimiter. */
  private readonly _pkColsCache = new Map<string, string>();
  private readonly _valColsCache = new Map<string, string>();
  private readonly _pkColListCache = new Map<string, string>();
  private readonly _valColListCache = new Map<string, string>();

  constructor(
    protected readonly table: string = "tabular_store",
    schema: Schema,
    primaryKeyNames: PrimaryKeyNames,
    indexes: readonly (keyof NoInfer<Entity> | readonly (keyof NoInfer<Entity>)[])[] = [],
    clientProvidedKeys: ClientProvidedKeysOption = "if-missing",
    tabularMigrations?: ReadonlyArray<import("../migrations").ITabularMigration>,
    migrationName?: string,
    uniqueIndexes: readonly (readonly (keyof NoInfer<Entity>)[])[] = []
  ) {
    super(
      schema,
      primaryKeyNames,
      indexes,
      clientProvidedKeys,
      tabularMigrations,
      migrationName ?? table,
      uniqueIndexes
    );
    this.validateTableAndSchema();
  }

  /** Maps a JSON Schema type to its dialect-specific SQL type. */
  protected abstract mapTypeToSQL(typeDef: JsonSchema): string;

  /**
   * Returns the underlying connection handle when this storage may share it
   * with other in-process storage instances (SQLite `Database`, PGlite
   * session). A backend whose isolation is per-connection (a real `pg.Pool`
   * that hands out a fresh client per query) returns `null` so writes stay
   * un-serialized. When non-null the value keys the shared
   * `ConnectionMutex` chain, so every instance that binds the same handle
   * queues through one lock and can detect cross-instance re-entry.
   */
  protected connectionHandle(): object | null {
    return null;
  }

  /**
   * Public view of {@link connectionHandle} used by
   * {@link withConnectionTransaction} to group participants. Postgres overrides
   * this so a real `pg.Pool` still groups by pool identity even though
   * {@link connectionHandle} stays `null` (pool writes must not serialize).
   */
  public sharedConnectionHandle(): object | null {
    return this.connectionHandle();
  }

  /**
   * True while this instance is between `BEGIN` and `COMMIT`/`ROLLBACK`. Fails
   * fast when a `withTransaction` callback captures the *original* storage
   * instead of the `tx` handle and recursively opens a transaction, which
   * would deadlock against its own {@link mutex}. Calls routed through `tx`
   * hit the proxy's override before reaching here.
   */
  protected inTransaction: boolean = false;

  /**
   * Sets {@link inTransaction} for the whole life of a connection-scoped
   * transaction.
   *
   * Public only because a connection transaction flags every PARTICIPANT, not
   * just the instance hosting it, so the driving code sits outside the class
   * hierarchy and cannot reach a `protected` member. Not for general use — the
   * flag is meaningless unless a `BEGIN` really is open on the connection.
   *
   * @internal
   */
  public setConnectionTransactionActive(active: boolean): void {
    this.inTransaction = active;
  }

  /**
   * Per-instance promise-chain mutex. On a backend that runs every statement
   * on one shared connection, all public read/write methods queue behind the
   * previous holder, and `withTransaction` holds the lock for the duration of
   * the user's callback — so concurrent calls from outside `fn` queue behind
   * the transaction instead of slipping into it.
   *
   * The Proxy returned by a backend's `createTxView` routes back to the private
   * `_*Internal` methods, so calls made *through* the `tx` handle inside `fn`
   * do not deadlock against the lock `withTransaction` is holding.
   *
   * `protected` so subclasses that fully override `put`/`putBulk` (e.g.
   * `SqliteAiVectorStorage`, which builds its own vector-encoding SQL) can
   * serialize through the same lock instead of running their statements on the
   * shared connection while a `BEGIN` is open. A backend whose isolation is
   * per-connection overrides this to a no-op rather than serializing queries
   * the database is happy to run in parallel.
   */
  private mutexChain: Promise<void> = Promise.resolve();
  protected async mutex<T>(fn: () => Promise<T>): Promise<T> {
    const prev = this.mutexChain;
    let release!: () => void;
    this.mutexChain = new Promise<void>((resolve) => {
      release = resolve;
    });
    await prev;
    try {
      return await fn();
    } finally {
      release();
    }
  }

  protected constructPrimaryKeyColumns($delimiter: string = ""): string {
    let cached = this._pkColsCache.get($delimiter);
    if (cached === undefined) {
      cached = Object.entries<JsonSchema>(this.primaryKeySchema.properties)
        .map(([key, typeDef]) => {
          const sqlType = this.mapTypeToSQL(typeDef);
          return `${$delimiter}${key}${$delimiter} ${sqlType} NOT NULL`;
        })
        .join(", ");
      this._pkColsCache.set($delimiter, cached);
    }
    return cached;
  }

  protected constructValueColumns($delimiter: string = ""): string {
    let cached = this._valColsCache.get($delimiter);
    if (cached === undefined) {
      const requiredSet = new Set(this.valueSchema.required ?? []);
      const cols = Object.entries<JsonSchema>(this.valueSchema.properties)
        .map(([key, typeDef]) => {
          const sqlType = this.mapTypeToSQL(typeDef);
          const isRequired = requiredSet.has(key);
          const nullable = !isRequired || this.isNullable(typeDef);
          return `${$delimiter}${key}${$delimiter} ${sqlType}${nullable ? " NULL" : " NOT NULL"}`;
        })
        .join(", ");
      cached = cols.length > 0 ? `, ${cols}` : "";
      this._valColsCache.set($delimiter, cached);
    }
    return cached;
  }

  protected isNullable(typeDef: JsonSchema): boolean {
    return isNullableSchema(typeDef);
  }

  protected primaryKeyColumnList($delimiter: string = ""): string {
    let cached = this._pkColListCache.get($delimiter);
    if (cached === undefined) {
      cached =
        $delimiter + this.primaryKeyColumns().join(`${$delimiter}, ${$delimiter}`) + $delimiter;
      this._pkColListCache.set($delimiter, cached);
    }
    return cached;
  }

  protected valueColumnList($delimiter: string = ""): string {
    let cached = this._valColListCache.get($delimiter);
    if (cached === undefined) {
      cached = $delimiter + this.valueColumns().join(`${$delimiter}, ${$delimiter}`) + $delimiter;
      this._valColListCache.set($delimiter, cached);
    }
    return cached;
  }

  /** Extracts the non-null branch from a `T | null` union schema. */
  protected getNonNullType(typeDef: JsonSchema): JsonSchema {
    return getNonNullSchema(typeDef);
  }

  /**
   * Determines if a numeric field should be treated as unsigned, i.e. it is a
   * `number`/`integer` schema with a `minimum` of zero or greater. Shared by
   * the Postgres-shaped backends when selecting integer range types.
   */
  protected shouldBeUnsigned(typeDef: JsonSchema): boolean {
    const actualType = this.getNonNullType(typeDef);
    if (typeof actualType === "boolean") {
      return false;
    }
    return (
      (actualType.type === "number" || actualType.type === "integer") &&
      typeof actualType.minimum === "number" &&
      actualType.minimum >= 0
    );
  }

  /** Returns value fields ordered to match the schema declaration. */
  protected getValueAsOrderedArray(value: Value): ValueOptionType[] {
    const orderedParams: ValueOptionType[] = [];
    const valueAsRecord = value as Record<string, Entity[keyof Entity]>;
    const requiredSet = new Set(this.valueSchema.required ?? []);
    for (const key in this.valueSchema.properties) {
      if (Object.prototype.hasOwnProperty.call(valueAsRecord, key)) {
        const val = valueAsRecord[key];
        if (val === undefined && !requiredSet.has(key)) {
          orderedParams.push(null);
        } else {
          orderedParams.push(this.jsToSqlValue(key, val));
        }
      } else {
        if (requiredSet.has(key)) {
          throw new Error(`Missing required value field: ${key}`);
        }
        orderedParams.push(null);
      }
    }
    return orderedParams;
  }

  protected override getPrimaryKeyAsOrderedArray(key: PrimaryKey): ValueOptionType[] {
    const orderedParams: ValueOptionType[] = [];
    const keyObj = key as Record<string, Entity[keyof Entity]>;
    for (const k of Object.keys(this.primaryKeySchema.properties)) {
      if (k in keyObj) {
        const value = keyObj[k];
        if (value === null) {
          throw new Error(`Primary key field ${k} cannot be null`);
        }
        orderedParams.push(this.jsToSqlValue(k, value));
      } else {
        throw new Error(`Missing required primary key field: ${k}`);
      }
    }
    return orderedParams;
  }

  protected jsToSqlValue(column: string, value: Entity[keyof Entity]): ValueOptionType {
    const typeDef = this.schema.properties[column];
    if (!typeDef) {
      return value as ValueOptionType;
    }

    if (value === null && this.isNullable(typeDef)) {
      return null;
    }

    const actualType = this.getNonNullType(typeDef);
    if (typeof actualType === "boolean") {
      return value as ValueOptionType;
    }

    if (actualType.contentEncoding === "blob") {
      if (value instanceof Uint8Array) {
        return value;
      }
      if (typeof Buffer !== "undefined" && value instanceof Buffer) {
        return new Uint8Array(value);
      }
      if (Array.isArray(value)) {
        return new Uint8Array(value);
      }
      return value as ValueOptionType;
    } else if (value instanceof Date) {
      // Always coerce Date to ISO string regardless of declared column type.
      return value.toISOString();
    } else {
      return value as ValueOptionType;
    }
  }

  protected sqlToJsValue(column: string, value: ValueOptionType): Entity[keyof Entity] {
    const typeDef = this.schema.properties[column];
    if (!typeDef) {
      return value as Entity[keyof Entity];
    }

    if (value === null && this.isNullable(typeDef)) {
      return null as Entity[keyof Entity];
    }

    const actualType = this.getNonNullType(typeDef);
    if (typeof actualType === "boolean") {
      return value as Entity[keyof Entity];
    }

    if (actualType.contentEncoding === "blob") {
      if (typeof Buffer !== "undefined" && value instanceof Buffer) {
        return new Uint8Array(value) as Entity[keyof Entity];
      }
      if (value instanceof Uint8Array) {
        return value as Entity[keyof Entity];
      }
      return value as Entity[keyof Entity];
    } else {
      return value as Entity[keyof Entity];
    }
  }

  /**
   * Rejects table names and schema keys that cannot be safely interpolated into
   * DDL, and rejects schemas where PK and value keys collide.
   */
  protected validateTableAndSchema(): void {
    if (!/^[a-z]\w*$/i.test(this.table)) {
      throw new Error(
        "Table name must start with a letter and contain only letters, digits, and underscores, got: " +
          this.table
      );
    }

    const validateSchemaKeys = (schema: DataPortSchemaObject) => {
      for (const key in schema.properties) {
        if (!/^[a-z]\w*$/i.test(key)) {
          throw new Error(
            "Schema keys must start with a letter and contain only letters, digits, and underscores, got: " +
              key
          );
        }
      }
    };

    validateSchemaKeys(this.primaryKeySchema);
    validateSchemaKeys(this.valueSchema);

    const primaryKeys = new Set(Object.keys(this.primaryKeySchema.properties));
    const valueKeys = Object.keys(this.valueSchema.properties);
    const duplicates = valueKeys.filter((key) => primaryKeys.has(key));
    if (duplicates.length > 0) {
      throw new Error(`Duplicate keys found in schemas: ${duplicates.join(", ")}`);
    }
  }

  /**
   * Builds a keyset (seek) WHERE clause that selects rows strictly after
   * the cursor position according to the provided ordering. Handles mixed
   * ASC/DESC by expanding into the OR-of-AND form:
   *
   *   (col1 OP1 v1)
   *   OR (col1 = v1 AND col2 OP2 v2)
   *   OR (col1 = v1 AND col2 = v2 AND col3 OP3 v3)
   *   ...
   *
   * NULL handling. We adopt the same NULL ordering as the in-memory
   * comparator: NULLs sort *before* non-null values for ASC, *after* them
   * for DESC. The pair `runSqlPage` / `buildKeysetWhere` enforce this with
   * explicit `NULLS FIRST` / `NULLS LAST` in the ORDER BY plus NULL-aware
   * predicates here. Because the cursor's values are known at SQL-build
   * time, we branch at build time on NULL vs non-NULL rather than relying
   * on dialect-specific operators like `IS NOT DISTINCT FROM`:
   *
   *   - Equality on a preceding column:
   *       NULL  -> `col IS NULL`
   *       value -> `col = ?`
   *   - Strict comparison on the i-th column:
   *       ASC, NULL  -> `col IS NOT NULL`              (NULL is the smallest)
   *       ASC, value -> `col > ?`                       (NULLs sort before, excluded)
   *       DESC, NULL -> `1 = 0`                         (nothing comes after a NULL trailer)
   *       DESC, value-> `(col < ? OR col IS NULL)`      (smaller, then NULLs)
   *
   * @param effectiveOrderBy - Ordering to satisfy; must include the primary
   *   key columns at the tail so the comparison is total.
   * @param cursorValues - Values pulled from the cursor in the same order
   *   as `effectiveOrderBy`.
   * @param quote - Identifier quote character (e.g. `` ` `` or `"`).
   * @param placeholder - Function returning the placeholder string for the
   *   given 1-based parameter index.
   * @param startIndex - Param index to start numbering from. Returns the
   *   index to use after this clause's params.
   */
  protected buildKeysetWhere(
    effectiveOrderBy: ReadonlyArray<OrderBy<Entity>>,
    cursorValues: ReadonlyArray<ValueOptionType>,
    quote: string,
    placeholder: (index: number) => string,
    startIndex: number
  ): { whereClause: string; params: ValueOptionType[]; nextIndex: number } {
    if (effectiveOrderBy.length !== cursorValues.length) {
      throw new Error(
        `Keyset arity mismatch: ${effectiveOrderBy.length} order columns vs ${cursorValues.length} cursor values`
      );
    }
    const clauses: string[] = [];
    const params: ValueOptionType[] = [];
    let idx = startIndex;
    for (let i = 0; i < effectiveOrderBy.length; i++) {
      const parts: string[] = [];
      // Equality on all preceding columns. NULL-aware: collapse to IS NULL
      // when the cursor value is null, since SQL `col = NULL` is never true.
      for (let j = 0; j < i; j++) {
        const colExpr = `${quote}${String(effectiveOrderBy[j].column)}${quote}`;
        if (cursorValues[j] === null) {
          parts.push(`${colExpr} IS NULL`);
        } else {
          parts.push(`${colExpr} = ${placeholder(idx)}`);
          params.push(cursorValues[j]);
          idx++;
        }
      }
      // Strict comparison on the i-th column in its declared direction.
      const colExpr = `${quote}${String(effectiveOrderBy[i].column)}${quote}`;
      const v = cursorValues[i];
      const dir = effectiveOrderBy[i].direction;
      if (v === null) {
        // ASC NULLS FIRST: anything non-null comes after a NULL cursor.
        // DESC NULLS LAST: NULL is the trailing run; nothing comes after.
        parts.push(dir === "ASC" ? `${colExpr} IS NOT NULL` : `1 = 0`);
      } else {
        if (dir === "ASC") {
          parts.push(`${colExpr} > ${placeholder(idx)}`);
        } else {
          // DESC: rows smaller than v, then any NULLs after them.
          parts.push(`(${colExpr} < ${placeholder(idx)} OR ${colExpr} IS NULL)`);
        }
        params.push(v);
        idx++;
      }
      clauses.push(`(${parts.join(" AND ")})`);
    }
    return { whereClause: clauses.join(" OR "), params, nextIndex: idx };
  }

  /**
   * Shared SQL `getPage`/`queryPage` driver. Builds a single SELECT that
   * pushes the keyset predicate, ordering, and limit down to the database
   * so memory and wire traffic are O(pageSize) regardless of table size.
   *
   * Concrete SQL backends call this from their `getPage`/`queryPage`
   * overrides, supplying the dialect-specific quoting, placeholder
   * formatting, search-criteria WHERE builder, and select executor.
   */
  protected async runSqlPage(
    criteria: SearchCriteria<Entity> | undefined,
    request: PageRequest<Entity>,
    dialect: {
      readonly quote: string;
      readonly placeholder: (index: number) => string;
      readonly buildSearchWhere: (
        criteria: SearchCriteria<Entity>,
        startIndex: number
      ) => { whereClause: string; params: ValueOptionType[]; nextIndex: number };
      readonly executeSelect: (sql: string, params: ValueOptionType[]) => Promise<Entity[]>;
    }
  ): Promise<Page<Entity>> {
    // Validate before we interpolate any column names into SQL — the caller
    // is the trust boundary for orderBy contents.
    this.validatePageRequest(request);
    const limit = request.limit ?? 100;
    const pkColumns = this.primaryKeyColumns() as unknown as Array<keyof Entity>;
    const orderBy = request.orderBy;
    const effectiveOrderBy = this.buildEffectiveOrderBy(orderBy, pkColumns);
    const effectiveOrderForCursor = effectiveOrderBy.map((o) => ({
      column: String(o.column),
      direction: o.direction,
    }));

    let cursorPayload;
    if (request.cursor !== undefined) {
      cursorPayload = decodeCursor(request.cursor);
      assertCursorMatches(cursorPayload, effectiveOrderForCursor);
    }

    const params: ValueOptionType[] = [];
    let paramIdx = 1;
    const whereClauses: string[] = [];

    if (criteria && Object.keys(criteria).length > 0) {
      const built = dialect.buildSearchWhere(criteria, paramIdx);
      whereClauses.push(built.whereClause);
      params.push(...built.params);
      paramIdx = built.nextIndex;
    }

    if (cursorPayload) {
      // Re-encode cursor values through `jsToSqlValue` so dates and other
      // non-primitive types round-trip through the SQL driver the same way
      // the original row values did.
      const cursorValues = (cursorPayload.c as ValueOptionType[]).map((v, i) =>
        this.jsToSqlValue(String(effectiveOrderBy[i].column), v as Entity[keyof Entity])
      );
      const built = this.buildKeysetWhere(
        effectiveOrderBy,
        cursorValues,
        dialect.quote,
        dialect.placeholder,
        paramIdx
      );
      whereClauses.push(`(${built.whereClause})`);
      params.push(...built.params);
      paramIdx = built.nextIndex;
    }

    const q = dialect.quote;
    // Emit NULLS FIRST / NULLS LAST explicitly because SQLite (NULLS first
    // for ASC) and Postgres (NULLS last for ASC) disagree by default. The
    // keyset predicates in `buildKeysetWhere` assume NULLs-first-for-ASC,
    // NULLs-last-for-DESC; the ORDER BY must match that for resumed pages
    // to land in the right slot.
    const orderByClause = effectiveOrderBy
      .map((o) => {
        const nulls = o.direction === "ASC" ? "NULLS FIRST" : "NULLS LAST";
        return `${q}${String(o.column)}${q} ${o.direction} ${nulls}`;
      })
      .join(", ");

    let sql = `SELECT * FROM ${q}${this.table}${q}`;
    if (whereClauses.length > 0) {
      sql += ` WHERE ${whereClauses.join(" AND ")}`;
    }
    sql += ` ORDER BY ${orderByClause}`;
    sql += ` LIMIT ${dialect.placeholder(paramIdx)}`;
    params.push(limit);

    const items = await dialect.executeSelect(sql, params);

    const nextCursor =
      items.length === limit
        ? this.buildCursor(items[items.length - 1], effectiveOrderBy)
        : undefined;

    return { items, nextCursor };
  }

  /**
   * The dialect and executor for a pushed-down join, or `null` for a backend
   * that cannot run raw SQL (Supabase's PostgREST client). `null` keeps the
   * inherited hash join.
   */
  protected sqlJoinDialect(): SqlJoinDialect | null {
    return null;
  }

  /**
   * Decides whether `right` can be joined in one statement: it must be a SQL
   * storage speaking the same dialect on the same connection. The dialect is
   * compared by identity, not name — DuckDB's reports itself as Postgres.
   *
   * Only the SQL dialect is carried into the plan. The executor is resolved
   * again at execution time from whatever receiver runs the join, because a
   * backend's `executeRaw` closes over the connection its `this` names — and
   * inside `withTransaction` that receiver is the transaction proxy, whose
   * connection is the transaction's, not the instance's.
   */
  private planSqlJoin(right: unknown): SqlJoinPlan | null {
    if (!(right instanceof BaseSqlTabularStorage)) return null;
    const mine = this.sqlJoinDialect();
    const theirs = right.sqlJoinDialect();
    if (mine === null || theirs === null || mine.dialect !== theirs.dialect) return null;
    const handle = this.sharedConnectionHandle();
    if (handle === null || handle !== right.sharedConnectionHandle()) return null;
    // The pushdown reads the RIGHT table while holding only the LEFT's lock,
    // so it never queues behind a transaction the right side has open. On a
    // shared connection that would read rows a pending ROLLBACK is about to
    // erase; on a real pool it would run on a different client from the one
    // the right side is enlisted on and miss its uncommitted rows entirely.
    // The hash fallback goes through `right.query()`, which does serialize on
    // the right's own lock and does resolve its enlisted client, so hand this
    // case to it. `this.inTransaction` means the join is already inside that
    // transaction, where reading its own uncommitted rows is correct.
    if (right.inTransaction && !this.inTransaction) return null;
    return { right, dialect: mine.dialect };
  }

  /**
   * Runs the join as one `JOIN` statement when {@link planSqlJoin} allows it,
   * otherwise falls back to the hash join.
   *
   * The plan is computed ONCE and the pushdown runs from it directly. Taking
   * the mutex and then re-planning would let the hash-join fallback run while
   * this instance's lock is held, and that fallback reaches the public
   * `query`/`getAll`, which take the same non-reentrant lock — a deadlock that
   * wedges the instance for every later call. So the only thing that may run
   * under the lock here is the pushdown, which touches the driver directly.
   */
  override async join<R, T extends JoinType>(
    spec: JoinSpec<Entity, R, T>,
    right: ITabularStorage<any, any, R, any, any>
  ): Promise<JoinedRow<Entity, R, T>[]> {
    const target = resolveJoinDelegate(right) as ITabularStorage<any, any, R, any, any>;
    const plan = this.planSqlJoin(target);
    if (plan === null) return super.join(spec, target);
    return this.mutex(() => this.runSqlJoin(spec, plan.right, plan.dialect));
  }

  /**
   * Transaction-proxy entry point for {@link join}. The `_*Internal` name is
   * load-bearing: each backend's `createTxView` routes `tx.join()` here, bound
   * to the proxy, so the call bypasses the lock `withTransaction` is holding.
   * Re-planning (and falling back) is safe here precisely because no lock is
   * held on this path — `super.join`'s `query`/`getAll` re-enter the proxy and
   * route to `_queryInternal`/`_getAllInternal`.
   */
  protected async _joinInternal<R, T extends JoinType>(
    spec: JoinSpec<Entity, R, T>,
    right: ITabularStorage<any, any, R, any, any>
  ): Promise<JoinedRow<Entity, R, T>[]> {
    const target = resolveJoinDelegate(right) as ITabularStorage<any, any, R, any, any>;
    const plan = this.planSqlJoin(target);
    if (plan === null) return super.join(spec, target);
    return this.runSqlJoin(spec, plan.right, plan.dialect);
  }

  /**
   * Builds, executes and hydrates a pushed-down join.
   *
   * The executor comes from `this.sqlJoinDialect()` here rather than from the
   * plan: a backend binds `executeRaw` to the connection its `this` names, so
   * resolving it anywhere but the receiver that runs the statement can send it
   * down a connection that has since been released, or past an open
   * transaction whose uncommitted rows the join is supposed to see.
   */
  protected async runSqlJoin<R, T extends JoinType>(
    spec: JoinSpec<Entity, R, T>,
    right: BaseSqlTabularStorage<any, any, any, any, any, any>,
    dialect: ISqlDialect
  ): Promise<JoinedRow<Entity, R, T>[]> {
    const executor = this.sqlJoinDialect();
    if (executor === null) {
      throw new Error(`${this.constructor.name} cannot execute a pushed-down join.`);
    }
    // The right schema is always in hand here, so every column named by the
    // spec is checked before anything is quoted into SQL.
    this.validateJoinSpec(spec, right);
    const leftSide = this.sqlJoinSide(JOIN_LEFT_ALIAS);
    const rightSide = right.sqlJoinSide(JOIN_RIGHT_ALIAS);
    const { sql, params } = buildJoinSelect(dialect, spec, leftSide, rightSide);
    const rows = await executor.executeRaw(sql, params);

    // Built once for the whole result rather than per cell: the alias depends
    // only on the side and the column's position.
    const leftAliases = leftSide.columns.map((_, i) => joinColumnAlias("left", i));
    const rightAliases = rightSide.columns.map((_, i) => joinColumnAlias("right", i));
    // Primary-key columns are NOT NULL, so a right side whose key columns all
    // came back NULL is the NULL-extended half of an unmatched LEFT JOIN row.
    const rightKeyAliases = (right.primaryKeyColumns() as string[]).map((column) =>
      joinColumnAlias("right", rightSide.columns.indexOf(column))
    );
    return rows.map((row) => {
      const left: Record<string, unknown> = {};
      leftSide.columns.forEach((column, i) => {
        left[column] = this.sqlToJsValue(column, row[leftAliases[i]] as ValueOptionType);
      });
      const matched = rightKeyAliases.every(
        (alias) => row[alias] !== null && row[alias] !== undefined
      );
      let rightRow: Record<string, unknown> | undefined;
      if (matched) {
        rightRow = {};
        rightSide.columns.forEach((column, i) => {
          rightRow![column] = right.sqlToJsValue(column, row[rightAliases[i]] as ValueOptionType);
        });
      }
      return { left, right: rightRow } as unknown as JoinedRow<Entity, R, T>;
    });
  }

  /** This storage as one side of a join statement. */
  protected sqlJoinSide(alias: string): SqlJoinSide {
    return {
      table: this.table,
      alias,
      columns: [...(this.primaryKeyColumns() as string[]), ...(this.valueColumns() as string[])],
      schemaProps: this.schema.properties as Record<string, unknown>,
      convertValue: (column, value) => this.jsToSqlValue(column, value as Entity[keyof Entity]),
    };
  }

  /**
   * Stringifies a row's primary-key columns (run through `jsToSqlValue` so the
   * value shape matches what was bound) for matching `RETURNING` rows back to
   * the emitted VALUES rows. Both sides call this so int/uuid/date encodings
   * compare identically.
   */
  protected bulkKeyOf(row: Record<string, unknown>): string {
    const pkCols = this.primaryKeyColumns() as unknown as string[];
    return pkFingerprint(pkCols.map((c) => this.jsToSqlValue(c, row[c] as Entity[keyof Entity])));
  }

  /**
   * Resolves the auto-generated key policy for one entity, returning the value
   * to bind for the auto-key column, whether the row is "keyed" (its PK is
   * known before insert), and the entity augmented with any client-minted UUID.
   */
  private resolveBulkAutoKey(
    entity: InsertType,
    dialect: BulkPutDialect
  ): { entity: Record<string, unknown>; keyed: boolean } {
    const record = entity as Record<string, unknown>;
    if (!this.hasAutoGeneratedKey() || this.autoGeneratedKeyName === null) {
      return { entity: record, keyed: true };
    }
    const keyName = String(this.autoGeneratedKeyName);
    const provided = record[keyName];
    const hasProvided = provided !== undefined && provided !== null;

    if (this.clientProvidedKeys === "always") {
      if (!hasProvided) {
        throw new Error(
          `Auto-generated key "${keyName}" is required when clientProvidedKeys is "always"`
        );
      }
      return { entity: record, keyed: true };
    }

    const useClient = this.clientProvidedKeys === "if-missing" && hasProvided;
    if (useClient) return { entity: record, keyed: true };

    // Not using a client value. Mint a UUID here when the dialect does so.
    if (this.autoGeneratedKeyStrategy === "uuid" && dialect.mintUuidClientSide) {
      const minted = this.generateKeyValue(keyName, "uuid");
      return { entity: { ...record, [keyName]: minted }, keyed: true };
    }
    // Server assigns (integer autoincrement, or Postgres UUID DEFAULT): unkeyed.
    // Under "never" a client may still have supplied a value; drop it so the
    // row binds DEFAULT and the server generates the key — matching single-row
    // `put`, which ignores client values in this mode.
    if (hasProvided) {
      const stripped = { ...record };
      delete stripped[keyName];
      return { entity: stripped, keyed: false };
    }
    return { entity: record, keyed: false };
  }

  /**
   * Builds the ordered insert-column list and per-row cells for a chunk of
   * already-resolved entities. The only column whose cell can vary per row is
   * the auto-generated key (a `DEFAULT` literal for rows the server fills); all
   * other columns bind a parameter in every row (null for absent non-required).
   */
  private buildBulkCells(
    rows: ReadonlyArray<Record<string, unknown>>,
    includeAutoKey: boolean
  ): { columns: string[]; cells: BulkCell[][] } {
    const autoKey =
      this.hasAutoGeneratedKey() && this.autoGeneratedKeyName !== null
        ? String(this.autoGeneratedKeyName)
        : null;
    const pkCols = (this.primaryKeyColumns() as unknown as string[]).filter(
      (c) => c !== autoKey || includeAutoKey
    );
    const valCols = this.valueColumns() as unknown as string[];
    const columns = [...pkCols, ...valCols];

    const cells: BulkCell[][] = rows.map((row) => {
      const rowCells: BulkCell[] = [];
      for (const col of columns) {
        if (col === autoKey) {
          const v = row[col];
          if (v === undefined || v === null) {
            rowCells.push({ isDefault: true });
          } else {
            rowCells.push({ value: this.jsToSqlValue(col, v as Entity[keyof Entity]) });
          }
          continue;
        }
        const raw = row[col];
        rowCells.push({
          value: this.jsToSqlValue(col, (raw === undefined ? null : raw) as Entity[keyof Entity]),
        });
      }
      return rowCells;
    });
    return { columns, cells };
  }

  /**
   * Assembles one multi-row `INSERT … VALUES … RETURNING *` statement for a
   * chunk. Pure — dedup, key resolution, and chunking happen in
   * {@link runBulkPut} before this is called.
   */
  protected buildBulkPutValues(
    columns: string[],
    cells: BulkCell[][],
    dialect: BulkPutDialect
  ): { sql: string; params: ValueOptionType[] } {
    const q = dialect.quote;
    const quotedColumnList = columns.map((c) => `${q}${c}${q}`).join(", ");
    const params: ValueOptionType[] = [];
    let idx = 1;
    const valuesSql = cells
      .map((rowCells) => {
        const slots = rowCells.map((cell) => {
          if ("isDefault" in cell) return "DEFAULT";
          params.push(cell.value);
          return dialect.placeholder(idx++);
        });
        return `(${slots.join(", ")})`;
      })
      .join(", ");

    const head = dialect.insertInto(quotedColumnList);
    const tail = dialect.conflictClause(columns);
    const sql = `${head} VALUES ${valuesSql}${tail ? ` ${tail}` : ""} RETURNING *`;
    return { sql, params };
  }

  /**
   * Shared multi-row bulk-put driver. Resolves auto keys, dedups duplicate
   * primary keys last-wins (only when every row is keyed), chunks by
   * `maxBulkParams`, executes one statement per chunk via `exec`, and re-aligns
   * the returned rows so `aligned[i]` corresponds to `entities[i]`.
   *
   * `exec` MUST return rows already hydrated through the backend's
   * `sqlToJsValue`. The caller owns the surrounding transaction and event
   * emission; this method performs no I/O beyond `exec`.
   */
  protected async runBulkPut(
    entities: InsertType[],
    dialect: BulkPutDialect,
    maxBulkParams: number,
    exec: (sql: string, params: ValueOptionType[]) => Promise<Entity[]>
  ): Promise<{ aligned: Entity[]; distinct: Entity[] }> {
    if (entities.length === 0) return { aligned: [], distinct: [] };

    // 1. Resolve auto keys; a batch is keyed only if every row is keyed.
    const resolved = entities.map((e) => this.resolveBulkAutoKey(e, dialect));
    const keyed = resolved.every((r) => r.keyed);

    // 2. Determine whether the auto-key column appears in the statement.
    const autoKey =
      this.hasAutoGeneratedKey() && this.autoGeneratedKeyName !== null
        ? String(this.autoGeneratedKeyName)
        : null;
    const includeAutoKey =
      autoKey !== null &&
      resolved.some((r) => r.entity[autoKey] !== undefined && r.entity[autoKey] !== null);

    // 3. Dedup last-wins (keyed only) and record input -> unique-row mapping.
    const uniqueRows: Record<string, unknown>[] = [];
    const uniqueKeys: string[] = [];
    const inputToUnique: number[] = new Array(resolved.length);
    if (keyed) {
      const posByKey = new Map<string, number>();
      for (let i = 0; i < resolved.length; i++) {
        const key = this.bulkKeyOf(resolved[i].entity);
        const existing = posByKey.get(key);
        if (existing === undefined) {
          posByKey.set(key, uniqueRows.length);
          inputToUnique[i] = uniqueRows.length;
          uniqueKeys.push(key);
          uniqueRows.push(resolved[i].entity);
        } else {
          inputToUnique[i] = existing;
          uniqueRows[existing] = resolved[i].entity; // last write wins
        }
      }
    } else {
      for (let i = 0; i < resolved.length; i++) {
        inputToUnique[i] = i;
        uniqueRows.push(resolved[i].entity);
      }
    }

    // 4. Chunk by parameter budget, execute, collect per-unique-row results.
    const perRowParams = Math.max(
      1,
      this.buildBulkCells([uniqueRows[0]], includeAutoKey).columns.length
    );
    const chunkSize = Math.max(1, Math.floor(maxBulkParams / perRowParams));
    const uniqueResults: Entity[] = new Array(uniqueRows.length);
    for (let start = 0; start < uniqueRows.length; start += chunkSize) {
      const chunk = uniqueRows.slice(start, start + chunkSize);
      const { columns, cells } = this.buildBulkCells(chunk, includeAutoKey);
      const { sql, params } = this.buildBulkPutValues(columns, cells, dialect);
      const returned = await exec(sql, params);
      if (keyed) {
        const byKey = new Map<string, Entity>();
        for (const row of returned) byKey.set(this.bulkKeyOf(row as Record<string, unknown>), row);
        for (let j = 0; j < chunk.length; j++) {
          const match = byKey.get(uniqueKeys[start + j]);
          uniqueResults[start + j] = match ?? returned[j];
        }
      } else {
        for (let j = 0; j < returned.length; j++) uniqueResults[start + j] = returned[j];
      }
    }

    const aligned = inputToUnique.map((u) => uniqueResults[u]);
    return { aligned, distinct: uniqueResults };
  }
}
