/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { createServiceToken, EventEmitter, makeFingerprint } from "@workglow/util";
import { DataPortSchemaObject, FromSchema, TypedArraySchemaOptions } from "@workglow/util/schema";
import {
  AnyTabularStorage,
  AutoGeneratedKeys,
  CoveringIndexQueryOptions,
  DeleteSearchCriteria,
  InsertEntity,
  isSearchCondition,
  ITabularStorage,
  QueryOptions,
  SearchCriteria,
  SimplifyPrimaryKey,
  TabularChangePayload,
  TabularEventListener,
  TabularEventListeners,
  TabularEventName,
  TabularEventParameters,
  TabularSubscribeOptions,
  ValueOptionType,
} from "./ITabularStorage";
import { CoveringIndexMissingError } from "./CoveringIndexMissingError";
import {
  StorageEmptyCriteriaError,
  StorageInvalidColumnError,
  StorageInvalidLimitError,
  StorageValidationError,
} from "./StorageError";

export const TABULAR_REPOSITORY = createServiceToken<AnyTabularStorage>(
  "storage.tabularRepository"
);

/**
 * Options for controlling how client-provided values for auto-generated keys are handled
 */
export type ClientProvidedKeysOption = "never" | "if-missing" | "always";

/**
 * Generation strategy for auto-generated keys
 */
export type KeyGenerationStrategy = "autoincrement" | "uuid";

/**
 * Abstract base class for tabular storage repositories.
 * Provides functionality for storing and retrieving data with typed
 * primary keys and values, and supports compound keys and partial key lookup.
 * Has a basic event emitter for listening to repository events.
 *
 * @template Schema - The schema definition for the entity using JSON Schema
 * @template PrimaryKeyNames - Array of property names that form the primary key
 */
export abstract class BaseTabularStorage<
  Schema extends DataPortSchemaObject,
  PrimaryKeyNames extends ReadonlyArray<keyof Schema["properties"]>,
  // computed types
  Entity = FromSchema<Schema, TypedArraySchemaOptions>,
  PrimaryKey = SimplifyPrimaryKey<Entity, PrimaryKeyNames>,
  Value = Omit<Entity, PrimaryKeyNames[number] & keyof Entity>,
  InsertType = InsertEntity<Entity, AutoGeneratedKeys<Schema>>,
> implements ITabularStorage<Schema, PrimaryKeyNames, Entity, PrimaryKey, InsertType> {
  /** Event emitter for repository events */
  protected events = new EventEmitter<TabularEventListeners<PrimaryKey, Entity>>();

  protected indexes: Array<keyof Entity>[];
  protected primaryKeySchema: DataPortSchemaObject;
  protected valueSchema: DataPortSchemaObject;

  /** Name of the auto-generated key column (at most one primary key column may be auto-generated) */
  protected autoGeneratedKeyName: keyof Entity | null = null;
  /** Strategy for generating the auto-generated key */
  protected autoGeneratedKeyStrategy: KeyGenerationStrategy | null = null;
  /** How to handle client-provided values for auto-generated keys */
  protected clientProvidedKeys: ClientProvidedKeysOption;

  /**
   * Creates a new BaseTabularStorage instance
   * @param schema - Schema defining the structure of the entity
   * @param primaryKeyNames - Array of property names that form the primary key
   * @param indexes - Array of columns or column arrays to make searchable. Each string or single column creates a single-column index,
   *                    while each array creates a compound index with columns in the specified order.
   * @param clientProvidedKeys - How to handle client-provided values for auto-generated keys
   */
  constructor(
    protected schema: Schema,
    protected primaryKeyNames: PrimaryKeyNames,
    indexes: readonly (keyof NoInfer<Entity> | readonly (keyof NoInfer<Entity>)[])[] = [],
    clientProvidedKeys: ClientProvidedKeysOption = "if-missing"
  ) {
    this.clientProvidedKeys = clientProvidedKeys;
    const primaryKeyProps: Record<string, any> = {};
    const valueProps: Record<string, any> = {};
    const primaryKeySet = new Set(primaryKeyNames);

    // Split the schema properties into primary key and value properties
    for (const [key, typeDef] of Object.entries(schema.properties)) {
      if (primaryKeySet.has(key as keyof Schema["properties"])) {
        primaryKeyProps[key] = Object.assign({}, typeDef);
      } else {
        valueProps[key] = Object.assign({}, typeDef);
      }
    }

    // Filter required array to only include primary key fields
    const primaryKeyRequired =
      schema.required?.filter((key) => primaryKeySet.has(key as keyof Schema["properties"])) ?? [];
    // Filter required array to only include value fields
    const valueRequired =
      schema.required?.filter((key) => !primaryKeySet.has(key as keyof Schema["properties"])) ?? [];

    this.primaryKeySchema = {
      type: "object",
      properties: primaryKeyProps,
      required: primaryKeyRequired,
      additionalProperties: false,
    } as DataPortSchemaObject;
    this.valueSchema = {
      type: "object",
      properties: valueProps,
      required: valueRequired,
      additionalProperties: false,
    } as DataPortSchemaObject;

    // validate all combined columns names are "identifier" names
    const combinedColumns = [...this.primaryKeyColumns(), ...this.valueColumns()];
    for (const column of combinedColumns) {
      if (typeof column !== "string") {
        throw new Error("Column names must be strings");
      }
      if (!/^[a-zA-Z][a-zA-Z0-9_]*$/.test(column)) {
        throw new Error(
          "Column names must start with a letter and contain only letters, digits, and underscores"
        );
      }
    }

    // Normalize searchable into array of arrays
    this.indexes = indexes.map((spec) => (Array.isArray(spec) ? spec : [spec])) as Array<
      Array<keyof Entity>
    >;

    // searchable is an array of compound keys, which are arrays of columns
    // clean up searchable array by removing any compoundkeys that are a prefix of another compoundkey
    // or a prefix of the primary key
    this.indexes = this.filterCompoundKeys(
      this.primaryKeyColumns() as unknown as Array<keyof Entity>,
      this.indexes
    );

    // Validate searchable columns
    for (const compoundIndex of this.indexes) {
      for (const column of compoundIndex) {
        if (
          !(column in this.primaryKeySchema.properties) &&
          !(column in this.valueSchema.properties)
        ) {
          throw new Error(
            `Searchable column ${String(column)} is not in the primary key schema or value schema`
          );
        }
      }
    }

    // Detect and validate auto-generated keys (at most one PK column; any PK position is allowed).
    // Composite keys often put a scope column first (e.g. kb_id) and auto-generate a second id.
    const autoGeneratedKeys: string[] = [];
    for (const key of primaryKeyNames) {
      const keyStr = String(key);
      const propDef = (schema.properties as any)[keyStr];
      if (propDef && typeof propDef === "object" && "x-auto-generated" in propDef) {
        if (propDef["x-auto-generated"] === true) {
          autoGeneratedKeys.push(keyStr);
        }
      }
    }

    if (autoGeneratedKeys.length > 1) {
      throw new Error(
        `Multiple auto-generated keys detected: ${autoGeneratedKeys.join(", ")}. ` +
          `At most one primary key column can be auto-generated.`
      );
    }

    if (autoGeneratedKeys.length > 0) {
      const autoGenKeyName = autoGeneratedKeys[0];

      this.autoGeneratedKeyName = autoGenKeyName as keyof Entity;
      this.autoGeneratedKeyStrategy = this.determineGenerationStrategy(
        autoGenKeyName,
        schema.properties[autoGenKeyName as keyof Schema["properties"]]
      );
    }
  }

  protected filterCompoundKeys(
    primaryKey: Array<keyof Entity>,
    potentialKeys: Array<keyof Entity>[]
  ): Array<keyof Entity>[] {
    // Function to check if one array is a prefix of another
    const isPrefix = (prefix: Array<keyof Entity>, arr: Array<keyof Entity>): boolean => {
      if (prefix.length > arr.length) return false;
      return prefix.every((val, index) => val === arr[index]);
    };

    // Sort potential keys by length
    potentialKeys.sort((a, b) => a.length - b.length);

    let filteredKeys: Array<keyof Entity>[] = [];

    for (let i = 0; i < potentialKeys.length; i++) {
      let key = potentialKeys[i];

      if (isPrefix(key, primaryKey)) continue;

      // Keep single-column indexes regardless of being a prefix
      if (key.length === 1) {
        filteredKeys.push(key);
        continue;
      }

      // Skip if the key is a prefix of a later key in the list
      let isRedundant = potentialKeys.some((otherKey, j) => j > i && isPrefix(key, otherKey));

      if (!isRedundant) {
        filteredKeys.push(key);
      }
    }

    return filteredKeys;
  }

  /**
   * Adds an event listener for a specific event
   * @param name The name of the event to listen for
   * @param fn The callback function to execute when the event occurs
   */
  on<Event extends TabularEventName>(
    name: Event,
    fn: TabularEventListener<Event, PrimaryKey, Entity>
  ) {
    this.events.on(name, fn);
  }

  /**
   * Removes an event listener for a specific event
   * @param name The name of the event to remove the listener from
   * @param fn The callback function to remove
   */
  off<Event extends TabularEventName>(
    name: Event,
    fn: TabularEventListener<Event, PrimaryKey, Entity>
  ) {
    this.events.off(name, fn);
  }

  /**
   * Adds an event listener that will only be called once
   * @param name The name of the event to listen for
   * @param fn The callback function to execute when the event occurs
   */
  once<Event extends TabularEventName>(
    name: Event,
    fn: TabularEventListener<Event, PrimaryKey, Entity>
  ) {
    this.events.once(name, fn);
  }

  /**
   * Emits an event with the specified name and arguments
   * @param name The name of the event to emit
   * @param args The arguments to pass to the event listeners
   */
  emit<Event extends TabularEventName>(
    name: Event,
    ...args: TabularEventParameters<Event, PrimaryKey, Entity>
  ) {
    this.events.emit(name, ...args);
  }

  /**
   * Returns when the event was emitted (promise form of once)
   * @param name The name of the event to check
   * @returns true if the event has listeners, false otherwise
   */
  waitOn<Event extends TabularEventName>(
    name: Event
  ): Promise<TabularEventParameters<Event, PrimaryKey, Entity>> {
    return this.events.waitOn(name) as Promise<TabularEventParameters<Event, PrimaryKey, Entity>>;
  }

  /**
   * Core abstract methods that must be implemented by concrete repositories
   */
  abstract put(value: InsertType): Promise<Entity>;
  abstract putBulk(values: InsertType[]): Promise<Entity[]>;
  abstract get(key: PrimaryKey): Promise<Entity | undefined>;
  abstract delete(key: PrimaryKey | Entity): Promise<void>;
  abstract getAll(options?: QueryOptions<Entity>): Promise<Entity[] | undefined>;
  abstract deleteAll(): Promise<void>;
  abstract size(): Promise<number>;

  /**
   * Counts entries matching the specified search criteria.
   * Concrete storage implementations can override this with native count APIs.
   */
  async count(criteria?: SearchCriteria<Entity>): Promise<number> {
    if (!criteria || Object.keys(criteria).length === 0) {
      return await this.size();
    }
    const entities = await this.query(criteria);
    return entities?.length ?? 0;
  }

  /**
   * Deletes all entries matching the specified search criteria.
   * Supports multiple columns with optional comparison operators.
   *
   * @param criteria - Object with column names as keys and values or SearchConditions
   */
  abstract deleteSearch(criteria: DeleteSearchCriteria<Entity>): Promise<void>;

  /**
   * Queries entries matching the specified search criteria with optional ordering and limit.
   * Unlike `search`, this method does not require an index and supports comparison operators,
   * ORDER BY, and LIMIT.
   *
   * @param criteria - Object with column names as keys and values or SearchConditions
   * @param options - Optional ordering and limit options
   * @returns Array of matching entities or undefined if no matches found
   */
  abstract query(
    criteria: SearchCriteria<Entity>,
    options?: QueryOptions<Entity>
  ): Promise<Entity[] | undefined>;

  /**
   * Strict, projected query served entirely by a covering compound index.
   * Subclasses that support index-only reads (e.g. IndexedDB, InMemory) should
   * override this with an efficient implementation. The default throws
   * {@link CoveringIndexMissingError} so callers get a consistent error when
   * the storage backend has not implemented index-only projection.
   */
  queryIndex<K extends keyof Entity & string>(
    criteria: SearchCriteria<Entity>,
    options: CoveringIndexQueryOptions<Entity, K>
  ): Promise<Pick<Entity, K>[]> {
    this.validateSelect(options);
    const requiredColumns = [
      ...Object.keys(criteria),
      ...(options.orderBy ?? []).map((o) => String(o.column)),
      ...options.select.map(String),
    ];
    throw new CoveringIndexMissingError(this.constructor.name, requiredColumns, []);
  }

  /**
   * Abstract method to fetch a page of records.
   * @param offset - Number of records to skip
   * @param limit - Maximum number of records to return
   * @returns Promise resolving to an array of entities or undefined if no records found
   */
  abstract getBulk(offset: number, limit: number): Promise<Entity[] | undefined>;

  /**
   * Async generator that yields records one at a time.
   * Uses getBulk internally to fetch pages of data.
   * @param pageSize - Number of records to fetch per page (default: 100)
   * @yields Individual entity records
   */
  async *records(pageSize: number = 100): AsyncGenerator<Entity, void, undefined> {
    if (pageSize <= 0) {
      throw new RangeError(`pageSize must be greater than 0, got ${pageSize}`);
    }
    let offset = 0;
    while (true) {
      const page = await this.getBulk(offset, pageSize);
      if (!page || page.length === 0) {
        break;
      }
      for (const entity of page) {
        yield entity;
      }
      if (page.length < pageSize) {
        break;
      }
      offset += pageSize;
    }
  }

  /**
   * Async generator that yields pages of records.
   * Uses getBulk internally to fetch pages of data.
   * @param pageSize - Number of records per page (default: 100)
   * @yields Arrays of entities
   */
  async *pages(pageSize: number = 100): AsyncGenerator<Entity[], void, undefined> {
    if (pageSize <= 0) {
      throw new RangeError(`pageSize must be greater than 0, got ${pageSize}`);
    }
    let offset = 0;
    while (true) {
      const page = await this.getBulk(offset, pageSize);
      if (!page || page.length === 0) {
        break;
      }
      yield page;
      if (page.length < pageSize) {
        break;
      }
      offset += pageSize;
    }
  }

  /**
   * Subscribes to changes in the repository (including remote changes).
   * Default implementation throws an error - override in subclasses that support subscriptions.
   *
   * @param callback - Function called when a change occurs
   * @param options - Optional subscription options (e.g., polling interval)
   * @returns Unsubscribe function
   * @throws Error if not implemented by the concrete repository
   */
  public subscribeToChanges(
    _callback: (change: TabularChangePayload<Entity>) => void,
    _options?: TabularSubscribeOptions
  ): () => void {
    throw new Error(
      `subscribeToChanges is not implemented for ${this.constructor.name}. ` +
        `All concrete repository implementations should override this method.`
    );
  }

  /**
   * Validates query parameters: criteria columns, options, and operator values.
   * @throws StorageEmptyCriteriaError if criteria is empty
   * @throws StorageInvalidLimitError if limit <= 0
   * @throws StorageValidationError if offset < 0
   * @throws StorageInvalidColumnError if any column name is not in the schema
   */
  protected validateQueryParams(
    criteria: SearchCriteria<Entity>,
    options?: QueryOptions<Entity>
  ): void {
    const criteriaKeys = Object.keys(criteria) as Array<keyof Entity>;

    if (criteriaKeys.length === 0) {
      throw new StorageEmptyCriteriaError();
    }

    if (options?.limit !== undefined && options.limit <= 0) {
      throw new StorageInvalidLimitError(options.limit);
    }

    if (options?.offset !== undefined && options.offset < 0) {
      throw new StorageValidationError(`Query offset must be non-negative, got ${options.offset}`);
    }

    // Validate criteria column names exist in schema
    for (const column of criteriaKeys) {
      if (!(column in this.schema.properties)) {
        throw new StorageInvalidColumnError(String(column));
      }
      // Validate operator values at runtime
      const criterion = criteria[column];
      if (isSearchCondition(criterion)) {
        const validOperators = ["=", "<", "<=", ">", ">="];
        if (!validOperators.includes(criterion.operator)) {
          throw new StorageValidationError(
            `Invalid operator "${criterion.operator}". Must be one of: ${validOperators.join(", ")}`
          );
        }
      }
    }

    // Validate orderBy column names
    if (options?.orderBy) {
      const validDirections = ["ASC", "DESC"];
      for (const { column, direction } of options.orderBy) {
        if (!(column in this.schema.properties)) {
          throw new StorageInvalidColumnError(String(column));
        }
        if (!validDirections.includes(direction)) {
          throw new StorageValidationError(
            `Invalid sort direction "${direction}". Must be "ASC" or "DESC"`
          );
        }
      }
    }
  }

  /**
   * Validates getAll options (orderBy, limit, offset) without criteria.
   */
  protected validateGetAllOptions(options?: QueryOptions<Entity>): void {
    if (!options) return;

    if (options.limit !== undefined && options.limit <= 0) {
      throw new StorageInvalidLimitError(options.limit);
    }

    if (options.offset !== undefined && options.offset < 0) {
      throw new StorageValidationError(`Query offset must be non-negative, got ${options.offset}`);
    }

    if (options.orderBy) {
      const validDirections = ["ASC", "DESC"];
      for (const { column, direction } of options.orderBy) {
        if (!(column in this.schema.properties)) {
          throw new StorageInvalidColumnError(String(column));
        }
        if (!validDirections.includes(direction)) {
          throw new StorageValidationError(
            `Invalid sort direction "${direction}". Must be "ASC" or "DESC"`
          );
        }
      }
    }
  }

  /**
   * Validates the `select` array in a {@link CoveringIndexQueryOptions}.
   * Throws {@link StorageValidationError} when `select` is empty or contains
   * a column that is not in the schema's `properties`.
   */
  protected validateSelect<K extends keyof Entity & string>(
    options: CoveringIndexQueryOptions<Entity, K>
  ): void {
    if (!options.select || options.select.length === 0) {
      throw new StorageValidationError("queryIndex requires a non-empty select array");
    }
    const schemaProps = Object.keys(this.schema.properties);
    for (const col of options.select) {
      const colStr = String(col);
      if (!schemaProps.includes(colStr)) {
        throw new StorageValidationError(`queryIndex select column "${colStr}" is not in schema`);
      }
    }
  }

  protected primaryKeyColumns(): Array<keyof PrimaryKey> {
    const columns: Array<keyof PrimaryKey> = [];
    for (const key of Object.keys(this.primaryKeySchema.properties)) {
      columns.push(key as keyof PrimaryKey);
    }
    return columns;
  }

  protected valueColumns(): Array<keyof Value> {
    const columns: Array<keyof Value> = [];
    for (const key of Object.keys(this.valueSchema.properties)) {
      columns.push(key as keyof Value);
    }
    return columns;
  }

  /**
   * Utility method to separate a combined object into its key and value components
   * for storage.
   * @param obj - Entity row object
   * @returns Separated key and value objects
   */
  protected separateKeyValueFromCombined(obj: Entity): { value: Value; key: PrimaryKey } {
    if (obj === null) {
      console.warn("Key is null");
      return { value: {} as Value, key: {} as PrimaryKey };
    }
    if (typeof obj !== "object") {
      console.warn("Object is not an object");
      return { value: {} as Value, key: {} as PrimaryKey };
    }
    const primaryKeyNames = this.primaryKeyColumns();
    const valueNames = this.valueColumns();
    const value: Partial<Value> = {};
    const key: Partial<PrimaryKey> = {};
    const objRecord = obj as Record<string, unknown>;
    for (const k of primaryKeyNames) {
      (key as Record<string, unknown>)[k as string] = objRecord[k as string];
    }
    for (const k of valueNames) {
      (value as Record<string, unknown>)[k as string] = objRecord[k as string];
    }

    return { value: value as Value, key: key as PrimaryKey };
  }

  /**
   * Generates a consistent string identifier for a given key.
   *
   * @param key - Primary key to convert
   * @returns Promise resolving to a string fingerprint of the key
   */
  protected async getKeyAsIdString(key: PrimaryKey): Promise<string> {
    return await makeFingerprint(key);
  }

  /**
   * Converts a primary key object into an ordered array based on the schema
   * This ensures consistent parameter ordering for storage operations
   * @param key - The primary key object to convert
   * @returns Array of key values ordered according to the schema
   */
  protected getPrimaryKeyAsOrderedArray(key: PrimaryKey): ValueOptionType[] {
    const orderedParams: ValueOptionType[] = [];
    const keyObj = key as Record<string, ValueOptionType>;
    for (const k in this.primaryKeySchema.properties) {
      if (k in keyObj) {
        orderedParams.push(keyObj[k]);
      } else {
        throw new Error(`Missing required primary key field: ${k}`);
      }
    }
    return orderedParams;
  }

  /**
   * Finds the best matching index for a set of search keys.
   * @param unorderedSearchKey - Unordered array of keys being searched, can be reordered
   * @returns Array of column names representing the best matching index, or undefined if no suitable index is found
   */
  public findBestMatchingIndex(
    unorderedSearchKey: Array<keyof Entity>
  ): Array<keyof Entity> | undefined {
    if (!unorderedSearchKey.length) return undefined;

    const allKeys: Array<keyof Entity>[] = [
      this.primaryKeyColumns() as unknown as Array<keyof Entity>,
      ...(this.indexes as Array<keyof Entity>[]),
    ];

    const searchKeySet = new Set(unorderedSearchKey);

    const hasMatchingPrefix = (index: Array<keyof Entity>): boolean => {
      // Check if the first column of the index is in our search keys
      return index.length > 0 && searchKeySet.has(index[0]);
    };

    let bestMatch: Array<keyof Entity> | undefined;
    let bestMatchScore = 0;

    for (const index of allKeys) {
      if (hasMatchingPrefix(index)) {
        // Calculate how many consecutive search keys we can use from this index
        let score = 0;
        for (const col of index) {
          if (!searchKeySet.has(col)) break;
          score++;
        }

        if (score > bestMatchScore) {
          bestMatch = index;
          bestMatchScore = score;
        }
      }
    }

    return bestMatch;
  }

  /**
   * Checks if this storage has an auto-generated key configured
   * @returns true if an auto-generated key is configured
   */
  protected hasAutoGeneratedKey(): boolean {
    return this.autoGeneratedKeyName !== null;
  }

  /**
   * Checks if a given column name is the auto-generated key
   * @param name - Column name to check
   * @returns true if the column is the auto-generated key
   */
  protected isAutoGeneratedKey(name: string): boolean {
    return this.autoGeneratedKeyName !== null && String(this.autoGeneratedKeyName) === name;
  }

  /**
   * Determines the generation strategy for an auto-generated key based on its type
   * @param columnName - Name of the column
   * @param typeDef - JSON Schema type definition for the column
   * @returns The generation strategy to use
   */
  protected determineGenerationStrategy(columnName: string, typeDef: any): KeyGenerationStrategy {
    // Extract the actual type if it's a union with null
    let actualType = typeDef;
    if (typeDef && typeof typeDef === "object") {
      if (typeDef.anyOf && Array.isArray(typeDef.anyOf)) {
        actualType = typeDef.anyOf.find((t: any) => t.type !== "null") || typeDef;
      } else if (typeDef.oneOf && Array.isArray(typeDef.oneOf)) {
        actualType = typeDef.oneOf.find((t: any) => t.type !== "null") || typeDef;
      }
    }

    if (typeof actualType !== "object") {
      return "uuid";
    }

    // Integer types use autoincrement
    if (actualType.type === "integer") {
      return "autoincrement";
    }

    // Default to UUID for strings and other types
    return "uuid";
  }

  /**
   * Generates a key value for client-side key generation
   * Override in storage classes that generate keys client-side (InMemory, IndexedDB for UUIDs)
   * SQL-based storages typically generate keys server-side
   * @param columnName - Name of the column to generate a key for
   * @param strategy - The generation strategy to use
   * @returns The generated key value
   */
  protected generateKeyValue(
    columnName: string,
    strategy: KeyGenerationStrategy
  ): Promise<string | number> | string | number {
    throw new Error(
      `generateKeyValue not implemented for ${this.constructor.name}. ` +
        `Column: ${columnName}, Strategy: ${strategy}`
    );
  }

  /**
   * Runs `fn` inside a transaction. The default implementation provides no
   * rollback semantics — it simply invokes `fn(this)`. Concrete subclasses
   * with native transaction support (SQLite, PostgreSQL) override this.
   */
  async withTransaction<T>(fn: (tx: this) => Promise<T>): Promise<T> {
    return await fn(this);
  }

  /**
   * Sets up the database/storage for the repository.
   * Must be called before using any other methods (except for in-memory implementations).
   * Default implementation is a no-op - override in subclasses that need setup.
   */
  async setupDatabase(): Promise<void> {
    // no op by default
  }

  /**
   * Destroys the repository and frees up resources.
   */
  destroy(): void {
    // no op by default
  }

  async [Symbol.asyncDispose](): Promise<void> {
    this.destroy();
  }

  [Symbol.dispose](): void {
    this.destroy();
  }
}
