/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { createServiceToken } from "@workglow/util";
import { DataPortSchemaObject, FromSchema, TypedArraySchemaOptions } from "@workglow/util/schema";
import { BaseTabularStorage, ClientProvidedKeysOption } from "./BaseTabularStorage";
import type {
  AnyTabularStorage,
  AutoGeneratedKeys,
  DeleteSearchCriteria,
  InsertEntity,
  QueryOptions,
  SearchCriteria,
  SimplifyPrimaryKey,
} from "./ITabularStorage";

export const HTTP_TABULAR_PROXY_REPOSITORY = createServiceToken<AnyTabularStorage>(
  "storage.tabularRepository.httpProxy"
);

/**
 * Fetch-shaped function used to forward operations to the server. The signature
 * matches the DOM `fetch` so a real browser fetch, an in-process Hono `app.fetch`,
 * or the Electron `window.desktop.api` shim all work without adaptation.
 */
export type HttpTabularProxyFetch = (path: string, init?: RequestInit) => Promise<Response>;

export interface HttpTabularProxyOptions<
  Schema extends DataPortSchemaObject,
  PrimaryKeyNames extends ReadonlyArray<keyof Schema["properties"]>,
> {
  readonly fetch: HttpTabularProxyFetch;
  readonly table: string;
  readonly schema: Schema;
  readonly primaryKey: PrimaryKeyNames;
  readonly secondaryKeys?: readonly (
    | keyof Schema["properties"]
    | readonly (keyof Schema["properties"])[]
  )[];
  /** Optional base path. Defaults to `/api/storage`. Must NOT have a trailing slash. */
  readonly basePath?: string;
  /** Forwarded to BaseTabularStorage. Defaults to "if-missing". */
  readonly clientProvidedKeys?: ClientProvidedKeysOption;
}

/**
 * Storage adapter that forwards every {@link ITabularStorage} operation as
 * `POST {basePath}/{table}/{op}` through an injected fetch impl.
 *
 * Transport is the fetch impl's concern — this class doesn't know whether the
 * request crosses a socket (dev), a `MessageChannelMain` port (Electron prod),
 * or runs in-process against `app.fetch` (tests / web mode).
 */
export class HttpTabularProxyStorage<
  Schema extends DataPortSchemaObject,
  PrimaryKeyNames extends ReadonlyArray<keyof Schema["properties"]>,
  Entity = FromSchema<Schema, TypedArraySchemaOptions>,
  PrimaryKey = SimplifyPrimaryKey<Entity, PrimaryKeyNames>,
  Value = Omit<Entity, PrimaryKeyNames[number] & keyof Entity>,
  InsertType = InsertEntity<Entity, AutoGeneratedKeys<Schema>>,
> extends BaseTabularStorage<Schema, PrimaryKeyNames, Entity, PrimaryKey, Value, InsertType> {
  protected readonly fetchImpl: HttpTabularProxyFetch;
  protected readonly table: string;
  protected readonly basePath: string;

  constructor(opts: HttpTabularProxyOptions<Schema, PrimaryKeyNames>) {
    const secondaryKeys = (opts.secondaryKeys ?? []) as readonly (
      | keyof Entity
      | readonly (keyof Entity)[]
    )[];
    super(opts.schema, opts.primaryKey, secondaryKeys, opts.clientProvidedKeys ?? "if-missing");
    this.fetchImpl = opts.fetch;
    this.table = opts.table;
    this.basePath = (opts.basePath ?? "/api/storage").replace(/\/+$/, "");
  }

  /**
   * Build the URL for an operation under this table.
   */
  protected url(op: string): string {
    return `${this.basePath}/${encodeURIComponent(this.table)}/${op}`;
  }

  /**
   * Send a POST with a JSON body. Throws on non-2xx, propagating the server's
   * `{ error }` body when present.
   */
  protected async call<T>(op: string, body: unknown): Promise<T> {
    const res = await this.fetchImpl(this.url(op), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body ?? {}),
    });
    if (!res.ok) {
      let message: string;
      try {
        const data = (await res.json()) as { error?: string };
        message = data?.error ?? `HTTP ${res.status}`;
      } catch {
        message = `HTTP ${res.status}`;
      }
      throw new Error(`HttpTabularProxyStorage(${this.table}/${op}): ${message}`);
    }
    return (await res.json()) as T;
  }

  // Method implementations land in later tasks.

  put(_value: InsertType): Promise<Entity> {
    throw new Error("Not implemented");
  }
  putBulk(_values: InsertType[]): Promise<Entity[]> {
    throw new Error("Not implemented");
  }
  get(_key: PrimaryKey): Promise<Entity | undefined> {
    throw new Error("Not implemented");
  }
  delete(_key: PrimaryKey | Entity): Promise<void> {
    throw new Error("Not implemented");
  }
  getAll(_options?: QueryOptions<Entity>): Promise<Entity[] | undefined> {
    throw new Error("Not implemented");
  }
  deleteAll(): Promise<void> {
    throw new Error("Not implemented");
  }
  size(): Promise<number> {
    throw new Error("Not implemented");
  }
  deleteSearch(_criteria: DeleteSearchCriteria<Entity>): Promise<void> {
    throw new Error("Not implemented");
  }
  query(
    _criteria: SearchCriteria<Entity>,
    _options?: QueryOptions<Entity>
  ): Promise<Entity[] | undefined> {
    throw new Error("Not implemented");
  }
  getOffsetPage(_offset: number, _limit: number): Promise<Entity[] | undefined> {
    throw new Error("Not implemented");
  }
}
